# 📈 US Stock Price Collector

Fetches full daily OHLCV history (2010 → today) for US stocks using **yfinance** (Yahoo Finance, free, no API key).
Filters to tickers that have **ever traded above $20**, then stores results on GitHub.

## Universe
Starts with ~1,200 tickers from S&P 500 + NASDAQ 100 + Russell 1000, then keeps only those with max close ≥ $20.

## Architecture
```
Yahoo Finance (yfinance)  →  this notebook  →  GitHub (CSV per ticker + master index)
```

## Files written to GitHub
| File | Contents |
|------|----------|
| `stocks/prices_{TICKER}.csv` | Daily OHLCV for one ticker |
| `stocks/index.csv` | Master index: ticker, name, sector, max_price, row_count, last_updated |

---
## 0. Install dependencies

---
## 1. Configuration

In [1]:
import os
from datetime import datetime, timezone
from dotenv import load_dotenv
load_dotenv()

# ── GitHub settings (same repo as HN data) ────────────────────────────────
GITHUB_REPO   = "annhmartin/dataviz-historical-stocks-AnnetteMartin"
GITHUB_TOKEN  = os.environ.get("GITHUB_TOKEN", None)
STOCKS_PREFIX = "stocks"           # folder inside the repo

# ── Filter settings ───────────────────────────────────────────────────────
MIN_PRICE     = 20.0               # keep tickers where max(close) >= this
START_DATE    = "2010-01-01"       # match HN historical window
END_DATE      = datetime.now(timezone.utc).strftime("%Y-%m-%d")

print("Configuration loaded ✓")
print(f"  Repo        : {GITHUB_REPO}")
print(f"  Token       : {'set ✓' if GITHUB_TOKEN else 'NOT SET'}")
print(f"  Price filter: max close >= ${MIN_PRICE}")
print(f"  Date range  : {START_DATE} → {END_DATE}")

Configuration loaded ✓
  Repo        : annhmartin/dataviz-historical-stocks-AnnetteMartin
  Token       : set ✓
  Price filter: max close >= $20.0
  Date range  : 2010-01-01 → 2026-06-28

---
## 2. Build the ticker universe

Pulls S&P 500 from Wikipedia, NASDAQ 100 and Russell 1000 from known sources, deduplicates.

In [2]:
import requests
import pandas as pd
import io


def _fetch_html(url: str) -> str:
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) "
                      "Chrome/120.0.0.0 Safari/537.36"
    }
    resp = requests.get(url, headers=headers, timeout=20)
    resp.raise_for_status()
    return resp.text


def get_all_us_tickers() -> pd.DataFrame:
    frames = []

    for exchange in ["nasdaq", "nyse", "amex"]:
        url  = f"https://www.nasdaqtrader.com/dynamic/SymDir/{exchange}listed.txt"
        resp = requests.get(url, timeout=20)
        resp.raise_for_status()

        rows = []
        lines = resp.text.strip().split("\n")
        for line in lines[1:]:  # skip header
            parts = line.split("|")
            if len(parts) >= 2:
                ticker = parts[0].strip()
                name   = parts[1].strip()
                rows.append({"ticker": ticker, "name": name,
                             "sector": exchange.upper(), "source": exchange.upper()})

        df = pd.DataFrame(rows)

        # Filter junk symbols
        df = df[~df["ticker"].str.contains(r'[\$\^\+\*\#]', regex=True, na=False)]
        df = df[df["ticker"].str.len() <= 5]
        df = df[df["ticker"].str.match(r'^[A-Z]+$')]
        df = df[df["ticker"].notna()]
        df = df[df["ticker"] != "nan"]

        frames.append(df)
        print(f"  {exchange.upper()}: {len(df)} tickers")

    universe = (
        pd.concat(frames, ignore_index=True)
        .drop_duplicates(subset="ticker")
        .reset_index(drop=True)
    )
    return universe


print("Fetching all US tickers …")
universe = get_all_us_tickers()
print(f"\n✓ Total universe: {len(universe)} tickers")
universe.head()


print("Fetching all US tickers …")
universe = get_all_us_tickers()
print(f"\n✓ Total universe: {len(universe)} tickers")
universe.head()

Fetching all US tickers …
  NASDAQ: 5533 tickers
  NYSE: 0 tickers
  AMEX: 0 tickers

✓ Total universe: 5533 tickers
Fetching all US tickers …
  NASDAQ: 5533 tickers
  NYSE: 0 tickers
  AMEX: 0 tickers

✓ Total universe: 5533 tickers

  ticker                                               name  sector  source
0   AAAP                  Pacer Barings CLO Market Flex ETF  NASDAQ  NASDAQ
1   AACB  Artius II Acquisition Inc. - Class A Ordinary ...  NASDAQ  NASDAQ
2  AACBR                Artius II Acquisition Inc. - Rights  NASDAQ  NASDAQ
3  AACBU                 Artius II Acquisition Inc. - Units  NASDAQ  NASDAQ
4   AACG  ATA Creativity Global - American Depositary Sh...  NASDAQ  NASDAQ

---
## 3. GitHub helpers

In [3]:
import base64
import io
import time

GITHUB_API = "https://api.github.com"


def _gh_headers(token: str) -> dict:
    return {
        "Authorization"       : f"Bearer {token}",
        "Accept"              : "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def push_csv_to_github(
    df: pd.DataFrame,
    repo: str,
    path: str,
    token: str,
    commit_message: str,
) -> None:
    buf = io.StringIO()
    df.to_csv(buf, index=False)
    encoded = base64.b64encode(buf.getvalue().encode()).decode()

    url     = f"{GITHUB_API}/repos/{repo}/contents/{path}"
    headers = _gh_headers(token)

    existing_sha = None
    check = requests.get(url, headers=headers, timeout=15)
    if check.status_code == 200:
        existing_sha = check.json().get("sha")

    payload = {"message": commit_message, "content": encoded}
    if existing_sha:
        payload["sha"] = existing_sha

    resp = requests.put(url, headers=headers, json=payload, timeout=60)
    resp.raise_for_status()


def load_csv_from_github(repo: str, path: str, token: str | None = None) -> pd.DataFrame:
    """Load via raw URL — handles large files."""
    raw_url = f"https://raw.githubusercontent.com/{repo}/main/{path}"
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    resp = requests.get(raw_url, headers=headers, timeout=60)
    if resp.status_code == 404:
        raise FileNotFoundError(f"Not found: {path}")
    resp.raise_for_status()
    content = resp.text.strip()
    if not content:
        return pd.DataFrame()
    return pd.read_csv(io.StringIO(content))


def file_exists_on_github(repo: str, path: str, token: str) -> bool:
    url  = f"{GITHUB_API}/repos/{repo}/contents/{path}"
    resp = requests.get(url, headers=_gh_headers(token), timeout=10)
    return resp.status_code == 200


print("GitHub helpers loaded ✓")

GitHub helpers loaded ✓

---
## 4. FULL HISTORICAL FETCH

> Fetches OHLCV for every ticker in the universe, applies the $20 price filter,
> and saves one CSV per ticker to `stocks/` in your GitHub repo.
> Skips tickers already stored — safe to re-run if interrupted.
> **Expect 30–90 minutes** for ~600 tickers.

In [5]:
!pip install yfinance
import yfinance as yf

if GITHUB_TOKEN is None:
    print("  GITHUB_TOKEN not set.")
else:
    tickers      = universe["ticker"].tolist()
    meta_lookup  = universe.set_index("ticker")[["name", "sector"]].to_dict("index")

    index_rows   = []   # master index entries
    skipped      = []   # below $20
    failed       = []   # API errors

    print(f"Fetching {len(tickers)} tickers ({START_DATE} → {END_DATE}) …\n")

    for i, ticker in enumerate(tickers, 1):
        path = f"{STOCKS_PREFIX}/prices_{ticker}.csv"

        # ── Skip if already on GitHub ──────────────────────────────────────
        if file_exists_on_github(GITHUB_REPO, path, GITHUB_TOKEN):
            print(f"  [{i}/{len(tickers)}] {ticker:6s} — already stored, skipping")
            # Still add to index so it appears in the master list
            try:
                df_existing = load_csv_from_github(GITHUB_REPO, path, GITHUB_TOKEN)
                if not df_existing.empty:
                    index_rows.append({
                        "ticker"       : ticker,
                        "name"         : meta_lookup.get(ticker, {}).get("name", ""),
                        "sector"       : meta_lookup.get(ticker, {}).get("sector", ""),
                        "max_price"    : round(df_existing["Close"].max(), 2),
                        "row_count"    : len(df_existing),
                        "start_date"   : df_existing["Date"].min(),
                        "last_updated" : datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                    })
            except Exception:
                pass
            continue

        # ── Fetch from Yahoo Finance ───────────────────────────────────────
        try:
            df = yf.download(
                ticker,
                start    = START_DATE,
                end      = END_DATE,
                progress = False,
                auto_adjust = True,
            )

            if df.empty:
                print(f"  [{i}/{len(tickers)}] {ticker:6s} — no data")
                failed.append(ticker)
                continue

            # Flatten MultiIndex columns if present
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)

            df = df.reset_index()
            df["ticker"] = ticker

            # ── Apply $20 price filter ─────────────────────────────────────
            max_price = df["Close"].max()
            if max_price < MIN_PRICE:
                print(f"  [{i}/{len(tickers)}] {ticker:6s} — max ${max_price:.2f} < ${MIN_PRICE} — skipped")
                skipped.append(ticker)
                continue

            # ── Push to GitHub ─────────────────────────────────────────────
            push_csv_to_github(
                df             = df,
                repo           = GITHUB_REPO,
                path           = path,
                token          = GITHUB_TOKEN,
                commit_message = f"Add {ticker} prices ({len(df)} rows, max ${max_price:.2f})",
            )

            index_rows.append({
                "ticker"       : ticker,
                "name"         : meta_lookup.get(ticker, {}).get("name", ""),
                "sector"       : meta_lookup.get(ticker, {}).get("sector", ""),
                "max_price"    : round(max_price, 2),
                "row_count"    : len(df),
                "start_date"   : str(df["Date"].min())[:10],
                "last_updated" : datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            })
            print(f"  [{i}/{len(tickers)}] {ticker:6s} — {len(df)} rows, max ${max_price:.2f} ✓")

            time.sleep(0.3)   # be polite to Yahoo

        except Exception as e:
            print(f"  [{i}/{len(tickers)}] {str(ticker):6s} — ERROR: {e}")
            failed.append(ticker)
            continue

    # ── Push master index ──────────────────────────────────────────────────
    if index_rows:
        df_index = pd.DataFrame(index_rows).sort_values("ticker").reset_index(drop=True)
        push_csv_to_github(
            df             = df_index,
            repo           = GITHUB_REPO,
            path           = f"{STOCKS_PREFIX}/index.csv",
            token          = GITHUB_TOKEN,
            commit_message = f"Update stock index — {len(df_index)} tickers",
        )

    print(f"\n Done!")
    print(f"   Stored  : {len(index_rows)} tickers")
    print(f"   Skipped : {len(skipped)} tickers below ${MIN_PRICE}")
    print(f"   Failed  : {len(failed)} tickers — {failed}")

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.4.1)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2025.2)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.1.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2026.1.4)
Requirement already satisfied: rich in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Fetching 5533 tickers (2010-01-01 → 2026-06-27) …

  [1/5533] AAAP   — 4 rows, max $25.16 ✓
  [2/5533] AACB   — max $10.55 < $20.0 — skipped
  [3/5533] AACBR  — max $0.21 < $20.0 — skipped
  [4/5533] AACBU  — max $12.79 < $20.0 — skipped
  [5/5533] AACG   — max $14.30 < $20.0 — skipped
  [6/5533] AACI   — max $9.98 < $20.0 — skipped
  [7/5533] AACIU  — max $10.30 < $20.0 — skipped
  [8/5533] AACIW  — max $0.65 < $20.0 — skipped
  [9/5533] AACO   — max $9.94 < $20.0 — skipped
  [10/5533] AACOU  — max $10.20 < $20.0 — skipped
  [11/5533] AACOW  — max $0.42 < $20.0 — skipped
  [12/5533] AACP   — max $10.00 < $20.0 — skipped
  [13/5533] AACPR  — max $0.21 < $20.0 — skipped
  [14/5533] AACPU  — max $10.35 < $20.0 — skipped
  [15/5533] AACPW  — max $0.13 < $20.0 — skipped
  [16/5533] AADR   — 4008 rows, max $96.52 ✓
  [17/5533] AAEQ   — 134 rows, max $54.13 ✓
  [18/5533] AAL    — 4145 rows, max $56.99 ✓
  [19/5533] AALG   — 242 rows, max $20.04 ✓
  [20/5533] AAME   — max $6.24 < $20.0 — skipped
  [21/5533] AAOI   — 3206 rows, max $223.10 ✓
  [22/5533] AAON   — 4145 rows, max $148.15 ✓
  [23/5533] AAPB   — 973 rows, max $41.02 ✓
  [24/5533] AAPD   — 973 rows, max $27.77 ✓
  [25/5533] AAPG   — 357 rows, max $47.90 ✓
  [26/5533] AAPL   — already stored, skipping
  [27/5533] AAPU   — 974 rows, max $42.14 ✓
  [28/5533] AARD   — max $17.41 < $20.0 — skipped
  [29/5533] AAUS   — 234 rows, max $60.78 ✓
  [30/5533] AAVM   — 2299 rows, max $34.81 ✓
  [31/5533] AAXJ   — 4145 rows, max $124.21 ✓
  [32/5533] ABAT   — 2600 rows, max $61.12 ✓
  [33/5533] ABCL   — 1390 rows, max $58.90 ✓
  [34/5533] ABCS   — 630 rows, max $33.29 ✓
  [35/5533] ABEO   — 4145 rows, max $4112.50 ✓
  [36/5533] ABI    — 252 rows, max $24.87 ✓
  [37/5533] ABIG   — 305 rows, max $34.54 ✓
  [38/5533] ABLV   — max $12.31 < $20.0 — skipped
  [39/5533] ABLVW  — max $0.02 < $20.0 — skipped
  [40/5533] ABNB   — already stored, skipping
  [41/5533] ABNG   — max $19.29 < $20.0 — skipped
  [42/5533] ABOS   — 1252 rows, max $20.28 ✓
  [43/5533] ABSI   — 1238 rows, max $30.29 ✓
  [44/5533] ABTC   — 2095 rows, max $99600.00 ✓
  [45/5533] ABTS   — 3071 rows, max $65.00 ✓
  [46/5533] ABUS   — 4145 rows, max $30.94 ✓
  [47/5533] ABVC   — 4145 rows, max $415605.09 ✓
  [48/5533] ABVX   — 672 rows, max $145.31 ✓
  [49/5533] ACAA   — max $10.05 < $20.0 — skipped
  [50/5533] ACAAU  — max $10.18 < $20.0 — skipped
  [51/5533] ACAAW  — max $0.64 < $20.0 — skipped
  [52/5533] ACAD   — 4145 rows, max $57.00 ✓
  [53/5533] ACB    — 3006 rows, max $1401.60 ✓
  [54/5533] ACCL   — max $4.51 < $20.0 — skipped
  [55/5533] ACDC   — 1033 rows, max $25.72 ✓
  [56/5533] ACEP   — 147 rows, max $20.41 ✓
  [57/5533] ACET   — 2115 rows, max $2335.20 ✓
  [58/5533] ACFN   — 4145 rows, max $202.07 ✓
  [59/5533] ACGC   — max $9.95 < $20.0 — skipped
  [60/5533] ACGCU  — max $10.11 < $20.0 — skipped
  [61/5533] ACGCW  — max $0.33 < $20.0 — skipped
  [62/5533] ACGL   — already stored, skipping
  [63/5533] ACGLN  — 1272 rows, max $20.02 ✓
  [64/5533] ACGLO  — 2224 rows, max $21.30 ✓
  [65/5533] ACHC   — 4145 rows, max $89.06 ✓
  [66/5533] ACHV   — 4145 rows, max $49434.00 ✓
  [67/5533] ACIC   — 4145 rows, max $21.47 ✓
  [68/5533] ACIU   — max $19.30 < $20.0 — skipped
  [69/5533] ACIW   — 4145 rows, max $59.20 ✓
  [70/5533] ACLS   — 4145 rows, max $200.48 ✓
  [71/5533] ACMR   — 2172 rows, max $109.87 ✓
  [72/5533] ACNB   — 4145 rows, max $58.39 ✓
  [73/5533] ACNT   — 4145 rows, max $24.18 ✓
  [74/5533] ACOG   — max $11.24 < $20.0 — skipped
  [75/5533] ACON   — 1048 rows, max $393638.41 ✓
  [76/5533] ACONW  — max $0.04 < $20.0 — skipped
  [77/5533] ACRS   — 2696 rows, max $32.99 ✓
  [78/5533] ACRV   — 905 rows, max $23.20 ✓
  [79/5533] ACT    — 1199 rows, max $44.64 ✓
  [80/5533] ACTG   — 4145 rows, max $41.98 ✓
  [81/5533] ACTU   — max $11.90 < $20.0 — skipped
  [82/5533] ACWI   — 4145 rows, max $158.94 ✓
  [83/5533] ACWX   — 4145 rows, max $77.38 ✓
  [84/5533] ACXP   — 1256 rows, max $157.80 ✓
  [85/5533] ADAC   — max $10.03 < $20.0 — skipped
  [86/5533] ADACU  — max $10.25 < $20.0 — skipped
  [87/5533] ADACW  — max $0.71 < $20.0 — skipped
  [88/5533] ADAG   — 1351 rows, max $29.99 ✓
  [89/5533] ADAM   — max $12.05 < $20.0 — skipped
  [90/5533] ADAMG  — 363 rows, max $25.30 ✓
  [91/5533] ADAMH  — 244 rows, max $25.59 ✓
  [92/5533] ADAMI  — 498 rows, max $25.21 ✓
  [93/5533] ADAML  — 1253 rows, max $24.38 ✓
  [94/5533] ADAMM  — 1680 rows, max $25.59 ✓
  [95/5533] ADAMN  — 2175 rows, max $23.95 ✓
  [96/5533] ADAMO  — 113 rows, max $25.15 ✓
  [97/5533] ADAMZ  — max $19.41 < $20.0 — skipped
  [98/5533] ADBE   — already stored, skipping
  [99/5533] ADBG   — max $16.83 < $20.0 — skipped
  [100/5533] ADEA   — 4145 rows, max $33.57 ✓
  [101/5533] ADGM   — max $9.05 < $20.0 — skipped
  [102/5533] ADI    — already stored, skipping
  [103/5533] ADIL   — 1989 rows, max $5206.25 ✓
  [104/5533] ADMA   — 3191 rows, max $24.51 ✓
  [105/5533] ADP    — already stored, skipping
  [106/5533] ADPT   — 1759 rows, max $67.74 ✓
  [107/5533] ADSE   — max $16.18 < $20.0 — skipped
  [108/5533] ADSEW  — max $0.78 < $20.0 — skipped
  [109/5533] ADSK   — already stored, skipping
  [110/5533] ADTN   — 4145 rows, max $36.38 ✓
  [111/5533] ADUR   — max $17.39 < $20.0 — skipped
  [112/5533] ADUS   — 4145 rows, max $135.92 ✓
  [113/5533] ADV    — 1629 rows, max $338.50 ✓
  [114/5533] ADVB   — 329 rows, max $80.00 ✓
  [115/5533] ADXN   — 1601 rows, max $483.80 ✓
  [116/5533] AEAQ   — max $10.02 < $20.0 — skipped
  [117/5533] AEAQU  — max $10.15 < $20.0 — skipped
  [118/5533] AEAQW  — max $0.28 < $20.0 — skipped
  [119/5533] AEBI   — max $15.58 < $20.0 — skipped
  [120/5533] AEC    — 3592 rows, max $1725.00 ✓
  [121/5533] AEHL   — 4145 rows, max $510258.84 ✓
  [122/5533] AEHR   — 4145 rows, max $116.58 ✓
  [123/5533] AEI    — 1401 rows, max $550.00 ✓
  [124/5533] AEIS   — 4145 rows, max $388.93 ✓
  [125/5533] AEMD   — 4145 rows, max $342000.00 ✓
  [126/5533] AENT   — max $10.50 < $20.0 — skipped
  [127/5533] AENTW  — max $0.73 < $20.0 — skipped
  [128/5533] AEP    — already stored, skipping
  [129/5533] AERT   — 1134 rows, max $87.86 ✓
  [130/5533] AERTW  — max $0.02 < $20.0 — skipped
  [131/5533] AESPU  — max $10.07 < $20.0 — skipped
  [132/5533] AEVA   — 1591 rows, max $100.00 ✓
  [133/5533] AEYE   — 3312 rows, max $43.67 ✓
  [134/5533] AFBI   — 2303 rows, max $22.59 ✓
  [135/5533] AFCG   — max $9.43 < $20.0 — skipped
  [136/5533] AFJK   — 610 rows, max $88.50 ✓
  [137/5533] AFJKR  — max $0.34 < $20.0 — skipped
  [138/5533] AFJKU  — 641 rows, max $75.37 ✓
  [139/5533] AFOS   — 252 rows, max $47.03 ✓
  [140/5533] AFRI   — max $12.10 < $20.0 — skipped
  [141/5533] AFRIW  — max $0.81 < $20.0 — skipped
  [142/5533] AFRM   — 1369 rows, max $168.52 ✓
  [143/5533] AFSC   — 341 rows, max $38.88 ✓
  [144/5533] AFYA   — 1744 rows, max $30.55 ✓
  [145/5533] AGCC   — 170 rows, max $23.96 ✓
  [146/5533] AGEM   — 340 rows, max $51.12 ✓
  [147/5533] AGEN   — 4145 rows, max $191.95 ✓
  [148/5533] AGGA   — 289 rows, max $25.15 ✓
  [149/5533] AGIO   — 3251 rows, max $135.01 ✓
  [150/5533] AGIX   — 487 rows, max $49.40 ✓
  [151/5533] AGMB   — max $16.21 < $20.0 — skipped
  [152/5533] AGMH   — 2059 rows, max $2120.00 ✓
  [153/5533] AGMI   — 538 rows, max $89.65 ✓
  [154/5533] AGNC   — max $11.51 < $20.0 — skipped
  [155/5533] AGNCL  — 952 rows, max $25.21 ✓
  [156/5533] AGNCM  — 1838 rows, max $25.20 ✓
  [157/5533] AGNCN  — 2227 rows, max $25.95 ✓
  [158/5533] AGNCO  — 1695 rows, max $25.62 ✓
  [159/5533] AGNCP  — 1606 rows, max $25.31 ✓
  [160/5533] AGNCZ  — 204 rows, max $25.69 ✓
  [161/5533] AGNG   — 2547 rows, max $38.44 ✓
  [162/5533] AGNT   — 2107 rows, max $74.25 ✓
  [163/5533] AGPU   — 4063 rows, max $3937500.00 ✓
  [164/5533] AGRZ   — max $6.23 < $20.0 — skipped
  [165/5533] AGYS   — 4145 rows, max $141.74 ✓
  [166/5533] AGZD   — 3148 rows, max $22.68 ✓
  [167/5533] AHCO   — 2029 rows, max $40.15 ✓
  [168/5533] AHD    — 27 rows, max $25.96 ✓
  [169/5533] AHG    — 2171 rows, max $40.16 ✓
  [170/5533] AHMA   — 171 rows, max $37.11 ✓
  [171/5533] AIA    — 4145 rows, max $150.17 ✓
  [172/5533] AIAI   — max $18.21 < $20.0 — skipped
  [173/5533] AIBZ   — max $9.45 < $20.0 — skipped
  [174/5533] AIDX   — 89 rows, max $23.85 ✓
  [175/5533] AIFA   — 2178 rows, max $64.86 ✓
  [176/5533] AIFC   — 4145 rows, max $32.85 ✓
  [177/5533] AIFD   — 537 rows, max $57.29 ✓
  [178/5533] AIFF   — 4145 rows, max $175.50 ✓
  [179/5533] AIFU   — 4145 rows, max $12006.60 ✓
  [180/5533] AIHS   — 2080 rows, max $806.00 ✓
  [181/5533] AIIO   — 1575 rows, max $368.00 ✓
  [182/5533] AIIOW  — max $0.03 < $20.0 — skipped
  [183/5533] AIIR   — max $15.00 < $20.0 — skipped
  [184/5533] AIMD   — 1372 rows, max $783.75 ✓
  [185/5533] AIMDW  — max $0.13 < $20.0 — skipped
  [186/5533] AIMS   — 95 rows, max $28.82 ✓
  [187/5533] AIOS   — 2387 rows, max $4798.00 ✓
  [188/5533] AIOT   — max $9.10 < $20.0 — skipped
  [189/5533] AIP    — 1170 rows, max $44.50 ✓
  [190/5533] AIPI   — 517 rows, max $38.41 ✓
  [191/5533] AIPO   — 232 rows, max $34.77 ✓
  [192/5533] AIQ    — 2039 rows, max $70.14 ✓
  [193/5533] AIRE   — 671 rows, max $10166.75 ✓
  [194/5533] AIRG   — 2481 rows, max $28.00 ✓
  [195/5533] AIRJ   — 1104 rows, max $29.27 ✓
  [196/5533] AIRJW  — max $0.75 < $20.0 — skipped
  [197/5533] AIRO   — 260 rows, max $31.00 ✓
  [198/5533] AIRR   — 3093 rows, max $133.25 ✓
  [199/5533] AIRS   — max $17.24 < $20.0 — skipped
  [200/5533] AIRT   — 4145 rows, max $40.50 ✓
  [201/5533] AIRTP  — max $19.95 < $20.0 — skipped
  [202/5533] AISP   — max $13.47 < $20.0 — skipped
  [203/5533] AISPW  — max $0.98 < $20.0 — skipped
  [204/5533] AIX    — 1 rows, max $24.09 ✓
  [205/5533] AIXC   — 2769 rows, max $625000.00 ✓
  [206/5533] AIXI   — 828 rows, max $90.36 ✓
  [207/5533] AKAM   — already stored, skipping
  [208/5533] AKAN   — 1075 rows, max $664977.50 ✓
  [209/5533] AKBA   — 3086 rows, max $29.17 ✓
  [210/5533] AKTS   — 116 rows, max $31.15 ✓
  [211/5533] AKTX   — 3137 rows, max $88000.00 ✓
  [212/5533] ALAB   — 569 rows, max $439.66 ✓
  [213/5533] ALAR   — 1974 rows, max $2550.00 ✓
  [214/5533] ALBG   — 114 rows, max $20.92 ✓
  [215/5533] ALBT   — 2074 rows, max $1882.50 ✓
  [216/5533] ALCO   — 4145 rows, max $48.95 ✓
  [217/5533] ALDF   — max $10.68 < $20.0 — skipped
  [218/5533] ALDFU  — max $11.78 < $20.0 — skipped
  [219/5533] ALDFW  — max $0.47 < $20.0 — skipped
  [220/5533] ALDX   — max $14.85 < $20.0 — skipped
  [221/5533] ALEC   — 1856 rows, max $39.49 ✓
  [222/5533] ALF    — max $10.89 < $20.0 — skipped
  [223/5533] ALFUU  — max $12.09 < $20.0 — skipped
  [224/5533] ALFUW  — max $0.21 < $20.0 — skipped
  [225/5533] ALGM   — 1420 rows, max $61.58 ✓
  [226/5533] ALGN   — already stored, skipping
  [227/5533] ALGS   — 1429 rows, max $873.50 ✓
  [228/5533] ALGT   — 4145 rows, max $259.82 ✓
  [229/5533] ALHC   — 1319 rows, max $27.27 ✓
  [230/5533] ALIL   — 305 rows, max $32.96 ✓

Failed to get ticker 'ALIS' reason: Failed to perform, curl: (28) Connection timed out after 39541 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

  [231/5533] ALIS   — max $10.15 < $20.0 — skipped
  [232/5533] ALISR  — max $0.80 < $20.0 — skipped
  [233/5533] ALISU  — max $11.36 < $20.0 — skipped
  [234/5533] ALKS   — 4145 rows, max $80.14 ✓
  [235/5533] ALKT   — 1307 rows, max $47.69 ✓
  [236/5533] ALLO   — 1936 rows, max $54.04 ✓
  [237/5533] ALLR   — 1132 rows, max $10605000.00 ✓
  [238/5533] ALLT   — 4145 rows, max $28.03 ✓
  [239/5533] ALLW   — 329 rows, max $30.26 ✓
  [240/5533] ALM    — 3277 rows, max $23.42 ✓
  [241/5533] ALMR   — 49 rows, max $26.87 ✓
  [242/5533] ALMS   — 500 rows, max $29.98 ✓
  [243/5533] ALMU   — 835 rows, max $31.49 ✓
  [244/5533] ALNT   — 4145 rows, max $102.26 ✓
  [245/5533] ALNY   — already stored, skipping
  [246/5533] ALOT   — 4145 rows, max $28.57 ✓
  [247/5533] ALOV   — max $9.95 < $20.0 — skipped
  [248/5533] ALOVU  — max $10.24 < $20.0 — skipped
  [249/5533] ALOVW  — max $0.45 < $20.0 — skipped
  [250/5533] ALOY   — 2490 rows, max $63.00 ✓
  [251/5533] ALP    — 4145 rows, max $1236.00 ✓
  [252/5533] ALPS   — max $2.56 < $20.0 — skipped
  [253/5533] ALPXU  — max $10.00 < $20.0 — skipped
  [254/5533] ALRM   — 2766 rows, max $107.69 ✓
  [255/5533] ALRS   — 4145 rows, max $31.17 ✓
  [256/5533] ALT    — 2283 rows, max $133.20 ✓
  [257/5533] ALTI   — max $15.40 < $20.0 — skipped
  [258/5533] ALTO   — 4145 rows, max $254.10 ✓
  [259/5533] ALTY   — max $12.34 < $20.0 — skipped
  [260/5533] ALVO   — max $17.27 < $20.0 — skipped
  [261/5533] ALVOW  — max $0.37 < $20.0 — skipped
  [262/5533] ALXO   — 1493 rows, max $112.26 ✓
  [263/5533] ALZN   — 1264 rows, max $18225.00 ✓
  [264/5533] AMA    — 39 rows, max $51.73 ✓
  [265/5533] AMAL   — 1980 rows, max $45.80 ✓
  [266/5533] AMAN   — max $10.15 < $20.0 — skipped
  [267/5533] AMAT   — already stored, skipping
  [268/5533] AMBA   — 3446 rows, max $216.84 ✓
  [269/5533] AMBR   — 2138 rows, max $183.00 ✓
  [270/5533] AMCI   — 858 rows, max $22.20 ✓
  [271/5533] AMCX   — 3779 rows, max $86.27 ✓
  [272/5533] AMD    — already stored, skipping
  [273/5533] AMDD   — 344 rows, max $32.48 ✓
  [274/5533] AMDG   — 357 rows, max $130.08 ✓
  [275/5533] AMDL   — 571 rows, max $77.00 ✓
  [276/5533] AMEI   — 3 rows, max $25.67 ✓
  [277/5533] AMEM   — 3 rows, max $24.93 ✓
  [278/5533] AMGN   — already stored, skipping
  [279/5533] AMGR   — 3 rows, max $24.98 ✓
  [280/5533] AMID   — 968 rows, max $37.34 ✓
  [281/5533] AMIX   — 605 rows, max $118.80 ✓
  [282/5533] AMKR   — 4145 rows, max $93.55 ✓
  [283/5533] AMLX   — 1120 rows, max $40.93 ✓
  [284/5533] AMOD   — 1168 rows, max $533.20 ✓
  [285/5533] AMODW  — max $0.08 < $20.0 — skipped
  [286/5533] AMPG   — max $18.00 < $20.0 — skipped
  [287/5533] AMPGR  — max $1.42 < $20.0 — skipped
  [288/5533] AMPGZ  — max $1.16 < $20.0 — skipped
  [289/5533] AMPH   — 3019 rows, max $65.00 ✓
  [290/5533] AMPL   — 1191 rows, max $84.80 ✓
  [291/5533] AMRN   — 4145 rows, max $482.40 ✓
  [292/5533] AMRX   — 2046 rows, max $24.27 ✓
  [293/5533] AMSC   — 4145 rows, max $434.20 ✓
  [294/5533] AMSF   — 4145 rows, max $51.57 ✓
  [295/5533] AMSS   — max $11.35 < $20.0 — skipped
  [296/5533] AMST   — 1444 rows, max $102.00 ✓
  [297/5533] AMTX   — 4145 rows, max $26.19 ✓
  [298/5533] AMUN   — 171 rows, max $26.07 ✓
  [299/5533] AMUU   — 309 rows, max $267.64 ✓
  [300/5533] AMYY   — max $15.68 < $20.0 — skipped
  [301/5533] AMZD   — 953 rows, max $30.57 ✓
  [302/5533] AMZN   — already stored, skipping
  [303/5533] AMZU   — 954 rows, max $46.91 ✓
  [304/5533] AMZZ   — 571 rows, max $42.01 ✓
  [305/5533] ANAB   — 2367 rows, max $85.70 ✓
  [306/5533] ANDE   — 4145 rows, max $79.42 ✓
  [307/5533] ANEL   — 204 rows, max $26.19 ✓
  [308/5533] ANGH   — 1468 rows, max $288.80 ✓
  [309/5533] ANGHW  — max $0.01 < $20.0 — skipped
  [310/5533] ANGI   — 3671 rows, max $280.00 ✓
  [311/5533] ANGL   — 3573 rows, max $29.24 ✓
  [312/5533] ANGO   — 4145 rows, max $30.97 ✓
  [313/5533] ANIK   — 4145 rows, max $73.36 ✓
  [314/5533] ANIP   — 4145 rows, max $137.16 ✓
  [315/5533] ANIX   — max $16.00 < $20.0 — skipped
  [316/5533] ANL    — max $16.60 < $20.0 — skipped
  [317/5533] ANNA   — max $16.83 < $20.0 — skipped
  [318/5533] ANNAW  — max $0.33 < $20.0 — skipped
  [319/5533] ANNX   — 1488 rows, max $35.01 ✓
  [320/5533] ANPA   — 245 rows, max $157.89 ✓
  [321/5533] ANSC   — max $11.44 < $20.0 — skipped
  [322/5533] ANSCU  — max $12.75 < $20.0 — skipped
  [323/5533] ANSCW  — max $0.25 < $20.0 — skipped
  [324/5533] ANTA   — max $16.38 < $20.0 — skipped
  [325/5533] ANTX   — 1067 rows, max $22.29 ✓
  [326/5533] ANV    — 99 rows, max $25.23 ✓
  [327/5533] ANY    — 3238 rows, max $156800.00 ✓
  [328/5533] AOHY   — max $11.09 < $20.0 — skipped
  [329/5533] AOSL   — 4065 rows, max $65.72 ✓
  [330/5533] AOTG   — 1002 rows, max $66.87 ✓
  [331/5533] AOUT   — 1468 rows, max $36.03 ✓
  [332/5533] APA    — already stored, skipping
  [333/5533] APAC   — max $10.17 < $20.0 — skipped
  [334/5533] APACR  — max $0.16 < $20.0 — skipped
  [335/5533] APACU  — max $10.56 < $20.0 — skipped
  [336/5533] APC    — 93 rows, max $21.55 ✓
  [337/5533] APEI   — 4145 rows, max $60.86 ✓
  [338/5533] APGE   — 741 rows, max $132.88 ✓
  [339/5533] API    — 1507 rows, max $106.14 ✓
  [340/5533] APLD   — 1054 rows, max $49.65 ✓
  [341/5533] APLM   — 1149 rows, max $2940.00 ✓
  [342/5533] APLMW  — max $0.13 < $20.0 — skipped
  [343/5533] APM    — 1890 rows, max $325.50 ✓
  [344/5533] APMCU  — max $10.00 < $20.0 — skipped
  [345/5533] APOG   — 4145 rows, max $83.89 ✓
  [346/5533] APP    — already stored, skipping
  [347/5533] APPF   — 2766 rows, max $321.25 ✓
  [348/5533] APPN   — 2284 rows, max $235.24 ✓
  [349/5533] APPS   — 4145 rows, max $94.74 ✓
  [350/5533] APPX   — 294 rows, max $136.74 ✓
  [351/5533] APRE   — 1691 rows, max $990.60 ✓
  [352/5533] APUR   — max $10.09 < $20.0 — skipped
  [353/5533] APURR  — max $0.16 < $20.0 — skipped
  [354/5533] APVO   — 2498 rows, max $65640960.00 ✓
  [355/5533] APWC   — max $7.51 < $20.0 — skipped
  [356/5533] APXT   — max $10.06 < $20.0 — skipped
  [357/5533] APXTU  — max $10.25 < $20.0 — skipped
  [358/5533] APXTW  — max $0.26 < $20.0 — skipped
  [359/5533] APYX   — max $17.40 < $20.0 — skipped
  [360/5533] AQB    — 2377 rows, max $529.80 ✓
  [361/5533] AQLG   — 14 rows, max $25.45 ✓
  [362/5533] AQMS   — 2742 rows, max $4378.00 ✓
  [363/5533] AQST   — max $18.96 < $20.0 — skipped
  [364/5533] AQWA   — 1309 rows, max $20.89 ✓
  [365/5533] ARAI   — max $13.25 < $20.0 — skipped
  [366/5533] ARAY   — max $11.02 < $20.0 — skipped
  [367/5533] ARBB   — 809 rows, max $69.75 ✓
  [368/5533] ARBE   — max $14.79 < $20.0 — skipped
  [369/5533] ARBEW  — max $0.08 < $20.0 — skipped
  [370/5533] ARBK   — 1194 rows, max $4440.96 ✓
  [371/5533] ARCB   — 4145 rows, max $173.22 ✓
  [372/5533] ARCC   — 4145 rows, max $21.10 ✓
  [373/5533] ARCI   — max $9.99 < $20.0 — skipped
  [374/5533] ARCIU  — max $10.15 < $20.0 — skipped
  [375/5533] ARCIW  — max $0.75 < $20.0 — skipped
  [376/5533] ARCL   — max $9.96 < $20.0 — skipped
  [377/5533] ARCLR  — max $0.25 < $20.0 — skipped
  [378/5533] ARCLU  — max $10.50 < $20.0 — skipped
  [379/5533] ARCLW  — max $0.12 < $20.0 — skipped
  [380/5533] ARCT   — 3294 rows, max $178.57 ✓
  [381/5533] ARDX   — 3023 rows, max $32.89 ✓
  [382/5533] AREC   — max $14.00 < $20.0 — skipped
  [383/5533] ARGX   — 2289 rows, max $929.61 ✓
  [384/5533] ARHS   — max $18.76 < $20.0 — skipped
  [385/5533] ARKO   — max $15.58 < $20.0 — skipped
  [386/5533] ARKR   — 4145 rows, max $22.37 ✓
  [387/5533] ARLP   — 4145 rows, max $28.31 ✓
  [388/5533] ARM    — already stored, skipping
  [389/5533] ARMG   — 364 rows, max $62.49 ✓
  [390/5533] ARMY   — 189 rows, max $28.74 ✓
  [391/5533] AROW   — 4145 rows, max $40.36 ✓
  [392/5533] ARQ    — 4145 rows, max $21.95 ✓
  [393/5533] ARQQ   — 1315 rows, max $951.50 ✓
  [394/5533] ARQQW  — max $0.61 < $20.0 — skipped
  [395/5533] ARQT   — 1609 rows, max $36.98 ✓
  [396/5533] ARRY   — 1430 rows, max $51.05 ✓
  [397/5533] ARTC   — max $9.93 < $20.0 — skipped
  [398/5533] ARTCU  — max $10.05 < $20.0 — skipped
  [399/5533] ARTCW  — max $0.37 < $20.0 — skipped
  [400/5533] ARTL   — 1763 rows, max $1331.10 ✓
  [401/5533] ARTNA  — 4145 rows, max $55.37 ✓
  [402/5533] ARTV   — max $15.83 < $20.0 — skipped
  [403/5533] ARTW   — max $13.76 < $20.0 — skipped
  [404/5533] ARVN   — 1946 rows, max $107.87 ✓
  [405/5533] ARVR   — 1050 rows, max $58.44 ✓
  [406/5533] ARWR   — 4145 rows, max $90.47 ✓
  [407/5533] ARXS   — 50 rows, max $46.83 ✓
  [408/5533] ASBP   — 1056 rows, max $560.40 ✓
  [409/5533] ASBPW  — max $0.60 < $20.0 — skipped
  [410/5533] ASCI   — 172 rows, max $38.12 ✓
  [411/5533] ASD    — 18 rows, max $26.05 ✓
  [412/5533] ASEC   — 21 rows, max $50.14 ✓
  [413/5533] ASLE   — 1842 rows, max $23.83 ✓
  [414/5533] ASMB   — 3903 rows, max $1215.00 ✓
  [415/5533] ASMG   — 364 rows, max $62.54 ✓
  [416/5533] ASML   — already stored, skipping
  [417/5533] ASMU   — 94 rows, max $40.84 ✓
  [418/5533] ASND   — 2870 rows, max $261.58 ✓
  [419/5533] ASO    — 1439 rows, max $73.38 ✓
  [420/5533] ASPC   — 369 rows, max $27.58 ✓
  [421/5533] ASPCR  — max $0.10 < $20.0 — skipped
  [422/5533] ASPCU  — 407 rows, max $27.91 ✓
  [423/5533] ASPI   — max $14.05 < $20.0 — skipped
  [424/5533] ASPS   — 4145 rows, max $1361.52 ✓
  [425/5533] ASPSW  — max $0.43 < $20.0 — skipped
  [426/5533] ASPSZ  — max $0.33 < $20.0 — skipped
  [427/5533] ASRV   — max $4.01 < $20.0 — skipped
  [428/5533] ASST   — 851 rows, max $355.00 ✓
  [429/5533] ASTC   — 4145 rows, max $591.00 ✓
  [430/5533] ASTE   — 4145 rows, max $74.49 ✓
  [431/5533] ASTH   — 4145 rows, max $119.45 ✓
  [432/5533] ASTI   — 963 rows, max $181900.00 ✓
  [433/5533] ASTL   — max $11.79 < $20.0 — skipped
  [434/5533] ASTLW  — max $0.13 < $20.0 — skipped
  [435/5533] ASTS   — 1670 rows, max $133.09 ✓
  [436/5533] ASUR   — max $19.06 < $20.0 — skipped
  [437/5533] ASYS   — 4145 rows, max $29.07 ✓
  [438/5533] ATAI   — max $19.89 < $20.0 — skipped
  [439/5533] ATAT   — 907 rows, max $42.21 ✓
  [440/5533] ATC    — 31 rows, max $24.32 ✓
  [441/5533] ATCX   — max $12.36 < $20.0 — skipped
  [442/5533] ATEC   — 4145 rows, max $87.84 ✓
  [443/5533] ATER   — 1770 rows, max $571.92 ✓
  [444/5533] ATEX   — 2866 rows, max $83.01 ✓
  [445/5533] ATGL   — 664 rows, max $47.00 ✓
  [446/5533] ATHE   — 4145 rows, max $739.80 ✓
  [447/5533] ATHR   — max $17.39 < $20.0 — skipped
  [448/5533] ATII   — max $11.38 < $20.0 — skipped
  [449/5533] ATIIU  — max $16.15 < $20.0 — skipped
  [450/5533] ATIIW  — max $0.78 < $20.0 — skipped
  [451/5533] ATLC   — 4145 rows, max $108.27 ✓
  [452/5533] ATLCL  — 1151 rows, max $25.22 ✓
  [453/5533] ATLCP  — 1265 rows, max $24.44 ✓
  [454/5533] ATLCZ  — 603 rows, max $25.71 ✓
  [455/5533] ATLN   — 1212 rows, max $220.40 ✓
  [456/5533] ATLO   — 4145 rows, max $30.85 ✓
  [457/5533] ATLX   — 3352 rows, max $412500.00 ✓
  [458/5533] ATNI   — 4145 rows, max $72.75 ✓
  [459/5533] ATOM   — 2485 rows, max $46.45 ✓
  [460/5533] ATOS   — 3427 rows, max $33399.00 ✓
  [461/5533] ATPC   — 701 rows, max $18000.00 ✓
  [462/5533] ATRA   — 2940 rows, max $1600.50 ✓
  [463/5533] ATRC   — 4145 rows, max $87.14 ✓
  [464/5533] ATRO   — 4145 rows, max $87.15 ✓
  [465/5533] ATXG   — 2089 rows, max $98481.00 ✓
  [466/5533] ATYR   — 2801 rows, max $390.32 ✓
  [467/5533] AUBN   — 4145 rows, max $49.45 ✓
  [468/5533] AUC    — 1797 rows, max $89.10 ✓
  [469/5533] AUDC   — 4145 rows, max $38.48 ✓
  [470/5533] AUGO   — 239 rows, max $108.01 ✓
  [471/5533] AUID   — 1265 rows, max $141.44 ✓
  [472/5533] AUMI   — 635 rows, max $122.22 ✓
  [473/5533] AUPH   — 2971 rows, max $33.08 ✓
  [474/5533] AUR    — max $17.11 < $20.0 — skipped
  [475/5533] AURA   — 1168 rows, max $24.89 ✓
  [476/5533] AURE   — 746 rows, max $252.00 ✓
  [477/5533] AUROW  — max $0.29 < $20.0 — skipped
  [478/5533] AUTL   — 2013 rows, max $48.01 ✓
  [479/5533] AUUD   — 1346 rows, max $24445.74 ✓
  [480/5533] AVAH   — max $12.89 < $20.0 — skipped
  [481/5533] AVAT   — max $10.62 < $20.0 — skipped
  [482/5533] AVAV   — 4145 rows, max $409.83 ✓
  [483/5533] AVBH   — 4145 rows, max $32.71 ✓
  [484/5533] AVBP   — 606 rows, max $35.63 ✓
  [485/5533] AVGB   — 299 rows, max $51.19 ✓
  [486/5533] AVGG   — 279 rows, max $46.78 ✓
  [487/5533] AVGO   — already stored, skipping
  [488/5533] AVGU   — 240 rows, max $60.06 ✓
  [489/5533] AVGX   — 462 rows, max $80.33 ✓
  [490/5533] AVIR   — 1419 rows, max $88.44 ✓
  [491/5533] AVL    — 428 rows, max $75.76 ✓
  [492/5533] AVLN   — 40 rows, max $32.97 ✓
  [493/5533] AVNW   — 4145 rows, max $47.22 ✓
  [494/5533] AVO    — 1439 rows, max $22.69 ✓
  [495/5533] AVOS   — 78 rows, max $27.21 ✓
  [496/5533] AVPT   — max $19.99 < $20.0 — skipped
  [497/5533] AVR    — max $10.40 < $20.0 — skipped
  [498/5533] AVS    — 428 rows, max $26.34 ✓
  [499/5533] AVT    — 4145 rows, max $92.93 ✓
  [500/5533] AVTX   — 2690 rows, max $20793.60 ✓
  [501/5533] AVUQ   — 309 rows, max $67.46 ✓
  [502/5533] AVX    — 1248 rows, max $3024000.00 ✓
  [503/5533] AVXC   — 568 rows, max $88.40 ✓
  [504/5533] AVXL   — 4145 rows, max $28.86 ✓
  [505/5533] AVXX   — 168 rows, max $65.07 ✓
  [506/5533] AWRE   — max $6.40 < $20.0 — skipped
  [507/5533] AXG    — 703 rows, max $47.00 ✓
  [508/5533] AXGN   — 4145 rows, max $55.90 ✓
  [509/5533] AXIN   — max $10.42 < $20.0 — skipped
  [510/5533] AXINR  — max $0.37 < $20.0 — skipped
  [511/5533] AXINU  — max $11.17 < $20.0 — skipped
  [512/5533] AXON   — already stored, skipping
  [513/5533] AXPG   — max $14.95 < $20.0 — skipped
  [514/5533] AXSM   — 2664 rows, max $255.17 ✓
  [515/5533] AXTI   — 4145 rows, max $140.83 ✓
  [516/5533] AYA    — 4068 rows, max $21.63 ✓
  [517/5533] AYTU   — 4145 rows, max $11356098.00 ✓
  [518/5533] AZ     — 1372 rows, max $30.15 ✓
  [519/5533] AZI    — 458 rows, max $1535.00 ✓
  [520/5533] AZTA   — 4145 rows, max $124.04 ✓
  [521/5533] AZYY   — max $18.24 < $20.0 — skipped
  [522/5533] BABU   — 93 rows, max $22.46 ✓
  [523/5533] BABX   — 886 rows, max $63.85 ✓
  [524/5533] BACC   — max $10.48 < $20.0 — skipped
  [525/5533] BACCR  — max $0.40 < $20.0 — skipped
  [526/5533] BACCU  — max $11.30 < $20.0 — skipped
  [527/5533] BAER   — 1326 rows, max $22.08 ✓
  [528/5533] BAERW  — max $0.51 < $20.0 — skipped
  [529/5533] BAFE   — 400 rows, max $29.23 ✓
  [530/5533] BAFN   — 1372 rows, max $30.05 ✓
  [531/5533] BAIG   — 213 rows, max $310.74 ✓
  [532/5533] BAIV   — 84 rows, max $25.89 ✓
  [533/5533] BALQ   — 141 rows, max $58.16 ✓
  [534/5533] BAND   — 2167 rows, max $193.08 ✓
  [535/5533] BANF   — 4145 rows, max $134.73 ✓
  [536/5533] BANFP  — 4145 rows, max $27.04 ✓
  [537/5533] BANL   — max $19.95 < $20.0 — skipped
  [538/5533] BANR   — 4145 rows, max $72.78 ✓
  [539/5533] BANX   — 3176 rows, max $21.03 ✓
  [540/5533] BAOS   — 1352 rows, max $53.16 ✓
  [541/5533] BASG   — 259 rows, max $27.54 ✓
  [542/5533] BASV   — 259 rows, max $30.84 ✓
  [543/5533] BATRA  — 2563 rows, max $56.16 ✓
  [544/5533] BATRK  — 2563 rows, max $51.66 ✓
  [545/5533] BAYA   — max $12.75 < $20.0 — skipped
  [546/5533] BAYAR  — max $0.09 < $20.0 — skipped
  [547/5533] BAYAU  — 632 rows, max $20.89 ✓
  [548/5533] BBB    — 380 rows, max $31.70 ✓
  [549/5533] BBCP   — max $11.52 < $20.0 — skipped
  [550/5533] BBCQ   — max $11.13 < $20.0 — skipped
  [551/5533] BBCQU  — max $13.00 < $20.0 — skipped
  [552/5533] BBCQW  — max $2.80 < $20.0 — skipped
  [553/5533] BBGI   — 4145 rows, max $290.56 ✓
  [554/5533] BBH    — 4145 rows, max $215.53 ✓
  [555/5533] BBIO   — 1759 rows, max $79.91 ✓
  [556/5533] BBLG   — 1180 rows, max $7891.20 ✓
  [557/5533] BBLGW  — 1179 rows, max $95.00 ✓
  [558/5533] BBNX   — 353 rows, max $31.99 ✓
  [559/5533] BBOT   — max $13.73 < $20.0 — skipped
  [560/5533] BBSI   — 4145 rows, max $48.78 ✓
  [561/5533] BBYY   — max $14.21 < $20.0 — skipped
  [562/5533] BCAB   — 1387 rows, max $3545.50 ✓
  [563/5533] BCAL   — 4145 rows, max $20.63 ✓
  [564/5533] BCAR   — max $10.99 < $20.0 — skipped
  [565/5533] BCARU  — max $12.38 < $20.0 — skipped
  [566/5533] BCARW  — max $0.71 < $20.0 — skipped
  [567/5533] BCAX   — 447 rows, max $27.07 ✓
  [568/5533] BCBP   — max $16.49 < $20.0 — skipped
  [569/5533] BCDA   — 4145 rows, max $1911.60 ✓
  [570/5533] BCFN   — 133 rows, max $25.53 ✓
  [571/5533] BCG    — max $12.95 < $20.0 — skipped
  [572/5533] BCGWW  — max $0.16 < $20.0 — skipped
  [573/5533] BCIC   — max $16.68 < $20.0 — skipped
  [574/5533] BCLO   — 353 rows, max $49.81 ✓
  [575/5533] BCML   — 4145 rows, max $32.62 ✓
  [576/5533] BCPC   — 4145 rows, max $183.26 ✓
  [577/5533] BCRX   — max $19.76 < $20.0 — skipped
  [578/5533] BCTK   — 133 rows, max $32.26 ✓
  [579/5533] BCTX   — 3592 rows, max $1563.52 ✓
  [580/5533] BCTXL  — max $0.80 < $20.0 — skipped
  [581/5533] BCTXZ  — max $0.14 < $20.0 — skipped
  [582/5533] BCYC   — 1783 rows, max $61.14 ✓
  [583/5533] BDCI   — max $10.20 < $20.0 — skipped
  [584/5533] BDCIU  — max $10.47 < $20.0 — skipped
  [585/5533] BDCIW  — max $0.50 < $20.0 — skipped
  [586/5533] BDGS   — 784 rows, max $36.95 ✓
  [587/5533] BDMD   — max $12.11 < $20.0 — skipped
  [588/5533] BDMDW  — max $0.19 < $20.0 — skipped
  [589/5533] BDRX   — 2653 rows, max $735000000.00 ✓
  [590/5533] BDSX   — 1421 rows, max $624.20 ✓
  [591/5533] BDTX   — 1609 rows, max $44.80 ✓
  [592/5533] BDVL   — 197 rows, max $26.13 ✓
  [593/5533] BDYN   — 197 rows, max $27.93 ✓
  [594/5533] BEAG   — max $10.88 < $20.0 — skipped
  [595/5533] BEAGR  — max $0.29 < $20.0 — skipped
  [596/5533] BEAGU  — max $11.40 < $20.0 — skipped
  [597/5533] BEAM   — 1605 rows, max $133.60 ✓
  [598/5533] BEAT   — max $5.94 < $20.0 — skipped
  [599/5533] BEATW  — max $0.16 < $20.0 — skipped
  [600/5533] BEDY   — 137 rows, max $29.28 ✓
  [601/5533] BEEM   — 4063 rows, max $73.78 ✓
  [602/5533] BEEP   — max $10.37 < $20.0 — skipped
  [603/5533] BEEX   — 382 rows, max $27.39 ✓
  [604/5533] BEEZ   — 659 rows, max $34.33 ✓
  [605/5533] BEG    — 132 rows, max $118.79 ✓
  [606/5533] BELFA  — 4145 rows, max $270.76 ✓
  [607/5533] BELFB  — 4145 rows, max $310.32 ✓
  [608/5533] BELT   — 507 rows, max $40.26 ✓
  [609/5533] BENF   — 1144 rows, max $6970.24 ✓
  [610/5533] BENFW  — max $0.01 < $20.0 — skipped
  [611/5533] BESO   — 46 rows, max $27.11 ✓
  [612/5533] BETR   — 1295 rows, max $2479.00 ✓
  [613/5533] BETRW  — max $0.31 < $20.0 — skipped
  [614/5533] BFC    — 4145 rows, max $150.70 ✓
  [615/5533] BFLX   — 26 rows, max $25.99 ✓
  [616/5533] BFRG   — max $8.74 < $20.0 — skipped
  [617/5533] BFRGW  — max $0.18 < $20.0 — skipped
  [618/5533] BFRI   — 1168 rows, max $263.40 ✓
  [619/5533] BFRIW  — max $0.07 < $20.0 — skipped
  [620/5533] BFST   — 2056 rows, max $30.15 ✓
  [621/5533] BGC    — max $12.65 < $20.0 — skipped
  [622/5533] BGCG   — 19 rows, max $26.44 ✓
  [623/5533] BGDE   — 3607 rows, max $434160.00 ✓
  [624/5533] BGEG   — 17 rows, max $25.28 ✓
  [625/5533] BGGG   — 19 rows, max $36.60 ✓
  [626/5533] BGIA   — 17 rows, max $25.38 ✓
  [627/5533] BGIN   — max $4.96 < $20.0 — skipped
  [628/5533] BGL    — 252 rows, max $133.00 ✓
  [629/5533] BGLC   — 1372 rows, max $285.60 ✓
  [630/5533] BGLWW  — max $0.28 < $20.0 — skipped
  [631/5533] BGM    — 1370 rows, max $58.32 ✓
  [632/5533] BGMS   — 4145 rows, max $8642383.00 ✓
  [633/5533] BGRN   — 1904 rows, max $47.69 ✓
  [634/5533] BGRO   — 516 rows, max $44.45 ✓
  [635/5533] BHAV   — max $9.99 < $20.0 — skipped
  [636/5533] BHAVR  — max $0.24 < $20.0 — skipped
  [637/5533] BHAVU  — max $10.40 < $20.0 — skipped
  [638/5533] BHDG   — 69 rows, max $26.67 ✓
  [639/5533] BHF    — 2249 rows, max $70.00 ✓
  [640/5533] BHFAL  — 1955 rows, max $21.99 ✓
  [641/5533] BHFAM  — max $17.98 < $20.0 — skipped
  [642/5533] BHFAN  — max $18.93 < $20.0 — skipped
  [643/5533] BHFAO  — 1534 rows, max $22.07 ✓
  [644/5533] BHFAP  — 1830 rows, max $21.64 ✓
  [645/5533] BHRB   — 4145 rows, max $75.97 ✓
  [646/5533] BHST   — max $19.25 < $20.0 — skipped
  [647/5533] BIAF   — 957 rows, max $249.00 ✓
  [648/5533] BIAFW  — max $0.29 < $20.0 — skipped
  [649/5533] BIB    — 4079 rows, max $108.50 ✓

$FBYDP: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-06-27)

1 Failed download:
['FBYDP']: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-06-27)

  [1726/5533] FBYDP  — no data
  [1727/5533] FBYDW  — max $0.98 < $20.0 — skipped
  [1728/5533] FBYY   — max $18.87 < $20.0 — skipped
  [1729/5533] FCA    — 3817 rows, max $34.11 ✓
  [1730/5533] FCAL   — 2262 rows, max $49.58 ✓
  [1731/5533] FCAP   — 4145 rows, max $68.91 ✓
  [1732/5533] FCBC   — 4145 rows, max $44.61 ✓
  [1733/5533] FCCO   — 4145 rows, max $32.74 ✓
  [1734/5533] FCEF   — 2448 rows, max $23.87 ✓
  [1735/5533] FCEL   — 4145 rows, max $17366.40 ✓
  [1736/5533] FCFS   — 4145 rows, max $232.57 ✓
  [1737/5533] FCHL   — 204 rows, max $3240.00 ✓
  [1738/5533] FCLO   — 93 rows, max $50.35 ✓
  [1739/5533] FCNCA  — 4145 rows, max $2336.57 ✓
  [1740/5533] FCNCN  — 102 rows, max $25.18 ✓
  [1741/5533] FCNCO  — 1120 rows, max $22.54 ✓
  [1742/5533] FCNCP  — 1585 rows, max $21.90 ✓
  [1743/5533] FCTE   — 498 rows, max $28.79 ✓
  [1744/5533] FCUV   — 2918 rows, max $1285.33 ✓
  [1745/5533] FCVT   — 2675 rows, max $54.63 ✓
  [1746/5533] FCXG   — max $18.07 < $20.0 — skipped
  [1747/5533] FDBC   — 4145 rows, max $59.72 ✓
  [1748/5533] FDCF   — 763 rows, max $51.76 ✓
  [1749/5533] FDFF   — 763 rows, max $38.94 ✓
  [1750/5533] FDIF   — 758 rows, max $39.75 ✓
  [1751/5533] FDIG   — 1049 rows, max $57.92 ✓
  [1752/5533] FDIQ   — 3683 rows, max $73.44 ✓
  [1753/5533] FDIV   — 694 rows, max $28.58 ✓
  [1754/5533] FDMT   — 1390 rows, max $52.67 ✓
  [1755/5533] FDNI   — 1915 rows, max $54.83 ✓
  [1756/5533] FDRS   — 123 rows, max $25.65 ✓
  [1757/5533] FDRX   — 112 rows, max $26.04 ✓
  [1758/5533] FDSB   — max $16.07 < $20.0 — skipped
  [1759/5533] FDT    — 3819 rows, max $100.11 ✓
  [1760/5533] FDTS   — 3610 rows, max $71.80 ✓
  [1761/5533] FDTX   — 763 rows, max $58.33 ✓
  [1762/5533] FDUS   — max $19.74 < $20.0 — skipped
  [1763/5533] FEAM   — 1075 rows, max $759.23 ✓
  [1764/5533] FEBO   — max $16.38 < $20.0 — skipped
  [1765/5533] FEED   — 2787 rows, max $16104.00 ✓
  [1766/5533] FEIM   — 4145 rows, max $77.15 ✓
  [1767/5533] FELE   — 4145 rows, max $109.56 ✓
  [1768/5533] FEM    — 3819 rows, max $33.53 ✓
  [1769/5533] FEMB   — 2926 rows, max $30.23 ✓
  [1770/5533] FEMS   — 3609 rows, max $48.82 ✓
  [1771/5533] FEMY   — 1261 rows, max $240.00 ✓
  [1772/5533] FENC   — max $14.33 < $20.0 — skipped
  [1773/5533] FEP    — 3815 rows, max $59.08 ✓
  [1774/5533] FEPI   — 679 rows, max $45.76 ✓
  [1775/5533] FER    — already stored, skipping
  [1776/5533] FERA   — max $10.50 < $20.0 — skipped
  [1777/5533] FERAR  — max $0.33 < $20.0 — skipped
  [1778/5533] FERAU  — max $10.90 < $20.0 — skipped
  [1779/5533] FEUZ   — 2933 rows, max $68.15 ✓
  [1780/5533] FEX    — 4145 rows, max $139.33 ✓
  [1781/5533] FFAI   — 1460 rows, max $183936.00 ✓
  [1782/5533] FFAIW  — max $0.02 < $20.0 — skipped
  [1783/5533] FFBC   — 4145 rows, max $33.49 ✓
  [1784/5533] FFIN   — 4145 rows, max $49.34 ✓
  [1785/5533] FFIV   — already stored, skipping
  [1786/5533] FFUT   — 266 rows, max $60.78 ✓
  [1787/5533] FGBI   — 3487 rows, max $26.18 ✓
  [1788/5533] FGBIP  — 1300 rows, max $20.73 ✓
  [1789/5533] FGI    — 1109 rows, max $24.30 ✓
  [1790/5533] FGII   — max $9.94 < $20.0 — skipped
  [1791/5533] FGIIU  — max $10.09 < $20.0 — skipped
  [1792/5533] FGIIW  — max $0.22 < $20.0 — skipped
  [1793/5533] FGIWW  — max $0.04 < $20.0 — skipped
  [1794/5533] FGL    — 419 rows, max $430.00 ✓
  [1795/5533] FGM    — 3609 rows, max $69.22 ✓
  [1796/5533] FGMC   — max $14.89 < $20.0 — skipped
  [1797/5533] FGMCR  — max $0.99 < $20.0 — skipped
  [1798/5533] FGMCU  — max $18.65 < $20.0 — skipped
  [1799/5533] FGNX   — 3078 rows, max $1246.25 ✓
  [1800/5533] FGNXP  — 2076 rows, max $25.75 ✓
  [1801/5533] FGSI   — 252 rows, max $20.55 ✓
  [1802/5533] FHB    — 2486 rows, max $29.30 ✓
  [1803/5533] FHTX   — 1424 rows, max $25.88 ✓
  [1804/5533] FIBK   — 4090 rows, max $38.44 ✓
  [1805/5533] FICS   — 1386 rows, max $41.81 ✓
  [1806/5533] FID    — 3229 rows, max $22.11 ✓
  [1807/5533] FIEE   — 4145 rows, max $112.50 ✓
  [1808/5533] FIGG   — 176 rows, max $292.94 ✓
  [1809/5533] FIGR   — 199 rows, max $73.91 ✓
  [1810/5533] FIGX   — max $10.30 < $20.0 — skipped
  [1811/5533] FIGXU  — max $10.45 < $20.0 — skipped
  [1812/5533] FIGXW  — max $0.24 < $20.0 — skipped
  [1813/5533] FIMU   — 6 rows, max $20.08 ✓
  [1814/5533] FINW   — 1153 rows, max $22.49 ✓
  [1815/5533] FINX   — 2460 rows, max $49.21 ✓
  [1816/5533] FINY   — 37 rows, max $25.16 ✓
  [1817/5533] FIP    — max $9.87 < $20.0 — skipped
  [1818/5533] FISI   — 4145 rows, max $38.70 ✓
  [1819/5533] FISN   — max $14.56 < $20.0 — skipped
  [1820/5533] FISV   — already stored, skipping
  [1821/5533] FIVE   — 3504 rows, max $247.71 ✓
  [1822/5533] FIVN   — 3075 rows, max $209.70 ✓
  [1823/5533] FIXD   — 2352 rows, max $45.06 ✓
  [1824/5533] FIYY   — 37 rows, max $24.86 ✓
  [1825/5533] FIZZ   — 4145 rows, max $79.77 ✓
  [1826/5533] FJP    — 3815 rows, max $81.33 ✓
  [1827/5533] FKU    — 3604 rows, max $55.39 ✓
  [1828/5533] FKWL   — 4145 rows, max $25.25 ✓
  [1829/5533] FLD    — max $11.38 < $20.0 — skipped
  [1830/5533] FLDB   — 586 rows, max $50.40 ✓
  [1831/5533] FLDDW  — max $0.16 < $20.0 — skipped
  [1832/5533] FLEX   — already stored, skipping
  [1833/5533] FLGT   — 2448 rows, max $183.85 ✓
  [1834/5533] FLL    — max $12.35 < $20.0 — skipped
  [1835/5533] FLN    — 3818 rows, max $27.59 ✓
  [1836/5533] FLNA   — 4145 rows, max $135.30 ✓
  [1837/5533] FLNC   — 1169 rows, max $37.61 ✓
  [1838/5533] FLNT   — 4145 rows, max $222.00 ✓
  [1839/5533] FLUX   — 1473 rows, max $20.00 ✓
  [1840/5533] FLWS   — 4145 rows, max $37.97 ✓
  [1841/5533] FLX    — max $18.01 < $20.0 — skipped
  [1842/5533] FLXS   — 4145 rows, max $68.77 ✓
  [1843/5533] FLY    — 223 rows, max $60.35 ✓
  [1844/5533] FLYE   — 515 rows, max $680.00 ✓
  [1845/5533] FLYW   — 1277 rows, max $53.96 ✓
  [1846/5533] FLZH   — 1661 rows, max $1874.75 ✓
  [1847/5533] FMAC   — max $10.01 < $20.0 — skipped
  [1848/5533] FMACR  — max $0.20 < $20.0 — skipped
  [1849/5533] FMACU  — max $10.16 < $20.0 — skipped
  [1850/5533] FMAO   — 4145 rows, max $38.24 ✓
  [1851/5533] FMB    — 3047 rows, max $51.36 ✓
  [1852/5533] FMBH   — 4145 rows, max $47.62 ✓
  [1853/5533] FMED   — 763 rows, max $28.83 ✓
  [1854/5533] FMET   — 1049 rows, max $40.06 ✓
  [1855/5533] FMFC   — max $15.48 < $20.0 — skipped
  [1856/5533] FMHI   — 2171 rows, max $48.42 ✓
  [1857/5533] FMNB   — max $15.87 < $20.0 — skipped
  [1858/5533] FMST   — max $7.10 < $20.0 — skipped
  [1859/5533] FMSTW  — max $0.90 < $20.0 — skipped
  [1860/5533] FMTM   — 319 rows, max $43.44 ✓
  [1861/5533] FMUB   — 307 rows, max $51.46 ✓
  [1862/5533] FMUN   — 306 rows, max $50.74 ✓
  [1863/5533] FNGR   — max $16.00 < $20.0 — skipped
  [1864/5533] FNK    — 3818 rows, max $61.27 ✓
  [1865/5533] FNKO   — 2172 rows, max $31.05 ✓
  [1866/5533] FNLC   — 4145 rows, max $34.10 ✓
  [1867/5533] FNRN   — max $18.40 < $20.0 — skipped
  [1868/5533] FNUC   — 1153 rows, max $169.00 ✓
  [1869/5533] FNWB   — 2868 rows, max $21.81 ✓
  [1870/5533] FNWD   — 4145 rows, max $44.49 ✓
  [1871/5533] FNX    — 4145 rows, max $145.21 ✓
  [1872/5533] FNY    — 3818 rows, max $108.79 ✓
  [1873/5533] FOCL   — max $12.49 < $20.0 — skipped
  [1874/5533] FOFO   — 198 rows, max $45.00 ✓
  [1875/5533] FORM   — 4145 rows, max $156.66 ✓
  [1876/5533] FORR   — 4145 rows, max $60.73 ✓
  [1877/5533] FORTY  — 4144 rows, max $172.83 ✓
  [1878/5533] FOSL   — 4145 rows, max $138.30 ✓
  [1879/5533] FOX    — already stored, skipping
  [1880/5533] FOXA   — already stored, skipping
  [1881/5533] FOXF   — 3240 rows, max $187.93 ✓
  [1882/5533] FOXX   — max $13.48 < $20.0 — skipped
  [1883/5533] FOXXW  — max $0.13 < $20.0 — skipped
  [1884/5533] FPA    — 3818 rows, max $58.32 ✓
  [1885/5533] FPXE   — 1931 rows, max $36.03 ✓
  [1886/5533] FPXI   — 2922 rows, max $86.09 ✓
  [1887/5533] FRAF   — 4145 rows, max $63.11 ✓
  [1888/5533] FRBA   — max $17.86 < $20.0 — skipped
  [1889/5533] FRBT   — max $18.25 < $20.0 — skipped
  [1890/5533] FRD    — 4145 rows, max $37.42 ✓
  [1891/5533] FREI   — 6 rows, max $25.02 ✓
  [1892/5533] FRGT   — 2233 rows, max $167951536.00 ✓
  [1893/5533] FRHC   — 2107 rows, max $190.14 ✓
  [1894/5533] FRME   — 4145 rows, max $43.37 ✓
  [1895/5533] FRMEP  — 1470 rows, max $25.83 ✓
  [1896/5533] FRMI   — 185 rows, max $32.53 ✓
  [1897/5533] FRMM   — 2262 rows, max $45524.00 ✓
  [1898/5533] FROG   — 1451 rows, max $88.31 ✓
  [1899/5533] FRPH   — 4145 rows, max $33.67 ✓
  [1900/5533] FRPT   — 2924 rows, max $184.82 ✓
  [1901/5533] FRSH   — 1195 rows, max $50.25 ✓
  [1902/5533] FRST   — max $15.75 < $20.0 — skipped
  [1903/5533] FRSX   — 2270 rows, max $1431.99 ✓
  [1904/5533] FRTT   — max $3.40 < $20.0 — skipped
  [1905/5533] FRVO   — 31 rows, max $42.50 ✓
  [1906/5533] FRWD   — 114 rows, max $34.47 ✓
  [1907/5533] FSBC   — 1293 rows, max $47.69 ✓
  [1908/5533] FSBW   — 3511 rows, max $46.54 ✓
  [1909/5533] FSCS   — 2265 rows, max $37.78 ✓
  [1910/5533] FSEA   — max $16.94 < $20.0 — skipped
  [1911/5533] FSGS   — 2263 rows, max $32.34 ✓
  [1912/5533] FSHP   — max $11.19 < $20.0 — skipped
  [1913/5533] FSHPR  — max $0.08 < $20.0 — skipped
  [1914/5533] FSHPU  — max $12.89 < $20.0 — skipped
  [1915/5533] FSLR   — already stored, skipping
  [1916/5533] FSLY   — 1787 rows, max $128.83 ✓
  [1917/5533] FSTB   — 6 rows, max $20.03 ✓
  [1918/5533] FSTR   — 4145 rows, max $55.43 ✓
  [1919/5533] FSUN   — 978 rows, max $43.97 ✓
  [1920/5533] FSV    — 2784 rows, max $207.30 ✓
  [1921/5533] FSZ    — 3610 rows, max $84.69 ✓
  [1922/5533] FTA    — 4145 rows, max $97.08 ✓
  [1923/5533] FTAG   — 4085 rows, max $134.90 ✓
  [1924/5533] FTAI   — 2796 rows, max $308.99 ✓
  [1925/5533] FTAIM  — 828 rows, max $27.55 ✓
  [1926/5533] FTC    — 4145 rows, max $194.10 ✓
  [1927/5533] FTCI   — 1297 rows, max $142.60 ✓
  [1928/5533] FTCS   — 4145 rows, max $98.84 ✓
  [1929/5533] FTDR   — 1956 rows, max $74.30 ✓
  [1930/5533] FTDS   — 2882 rows, max $62.48 ✓
  [1931/5533] FTEK   — max $10.82 < $20.0 — skipped
  [1932/5533] FTFT   — 4145 rows, max $11600.00 ✓
  [1933/5533] FTGC   — 3187 rows, max $30.34 ✓
  [1934/5533] FTGS   — 919 rows, max $37.83 ✓
  [1935/5533] FTH    — 1354 rows, max $455.00 ✓
  [1936/5533] FTHA   — max $9.93 < $20.0 — skipped
  [1937/5533] FTHAU  — max $10.05 < $20.0 — skipped
  [1938/5533] FTHAW  — max $0.52 < $20.0 — skipped
  [1939/5533] FTHI   — 3136 rows, max $23.87 ✓
  [1940/5533] FTHM   — 1483 rows, max $54.25 ✓
  [1941/5533] FTLF   — 4145 rows, max $20.76 ✓
  [1942/5533] FTNT   — already stored, skipping
  [1943/5533] FTQI   — 3136 rows, max $21.95 ✓
  [1944/5533] FTRE   — 759 rows, max $40.28 ✓
  [1945/5533] FTRI   — 4085 rows, max $24.70 ✓
  [1946/5533] FTRK   — max $7.19 < $20.0 — skipped
  [1947/5533] FTSL   — 3308 rows, max $44.77 ✓
  [1948/5533] FTSM   — 2990 rows, max $59.90 ✓
  [1949/5533] FTXG   — 2441 rows, max $25.75 ✓
  [1950/5533] FTXH   — 2453 rows, max $37.12 ✓
  [1951/5533] FTXL   — 2454 rows, max $297.01 ✓
  [1952/5533] FTXN   — 2452 rows, max $39.72 ✓
  [1953/5533] FTXO   — 2442 rows, max $41.81 ✓
  [1954/5533] FTXR   — 2453 rows, max $45.39 ✓
  [1955/5533] FUFU   — max $13.13 < $20.0 — skipped
  [1956/5533] FUFUW  — max $0.22 < $20.0 — skipped
  [1957/5533] FULC   — 1745 rows, max $30.97 ✓
  [1958/5533] FULT   — 4145 rows, max $24.28 ✓
  [1959/5533] FULTP  — max $19.95 < $20.0 — skipped
  [1960/5533] FUNC   — 4145 rows, max $43.43 ✓
  [1961/5533] FUND   — max $10.32 < $20.0 — skipped
  [1962/5533] FUSB   — max $16.50 < $20.0 — skipped
  [1963/5533] FUSE   — max $19.24 < $20.0 — skipped
  [1964/5533] FUSEW  — max $0.23 < $20.0 — skipped
  [1965/5533] FUTG   — 176 rows, max $22.30 ✓
  [1966/5533] FUTU   — 1836 rows, max $195.90 ✓
  [1967/5533] FV     — 3096 rows, max $74.25 ✓
  [1968/5533] FVAV   — max $10.15 < $20.0 — skipped
  [1969/5533] FVC    — 2583 rows, max $42.70 ✓
  [1970/5533] FVCB   — max $17.41 < $20.0 — skipped
  [1971/5533] FVN    — max $10.94 < $20.0 — skipped
  [1972/5533] FVNNR  — max $0.19 < $20.0 — skipped
  [1973/5533] FVNNU  — max $14.95 < $20.0 — skipped
  [1974/5533] FWACU  — max $10.00 < $20.0 — skipped
  [1975/5533] FWDI   — 4145 rows, max $53.30 ✓
  [1976/5533] FWONA  — 3385 rows, max $99.33 ✓
  [1977/5533] FWONK  — 3011 rows, max $108.33 ✓
  [1978/5533] FWRD   — 4145 rows, max $121.98 ✓
  [1979/5533] FWRG   — 1188 rows, max $25.52 ✓
  [1980/5533] FXACU  — max $10.08 < $20.0 — skipped
  [1981/5533] FXNC   — 4145 rows, max $30.19 ✓
  [1982/5533] FYC    — 3818 rows, max $122.01 ✓
  [1983/5533] FYT    — 3818 rows, max $68.77 ✓
  [1984/5533] FYX    — 4145 rows, max $140.86 ✓
  [1985/5533] GABC   — 4145 rows, max $46.81 ✓
  [1986/5533] GAIA   — 4145 rows, max $22.35 ✓
  [1987/5533] GAIN   — max $16.82 < $20.0 — skipped
  [1988/5533] GAING  — 89 rows, max $25.55 ✓
  [1989/5533] GAINI  — 380 rows, max $25.65 ✓
  [1990/5533] GAINZ  — 1218 rows, max $24.29 ✓
  [1991/5533] GALT   — max $18.30 < $20.0 — skipped
  [1992/5533] GAMB   — max $16.75 < $20.0 — skipped
  [1993/5533] GAME   — 2115 rows, max $2893.50 ✓
  [1994/5533] GANX   — max $15.80 < $20.0 — skipped
  [1995/5533] GARY   — 128 rows, max $26.94 ✓
  [1996/5533] GASS   — max $12.88 < $20.0 — skipped
  [1997/5533] GAUZ   — max $16.45 < $20.0 — skipped
  [1998/5533] GAVA   — 74 rows, max $24.76 ✓
  [1999/5533] GBDC   — max $13.90 < $20.0 — skipped
  [2000/5533] GBFH   — 494 rows, max $44.00 ✓
  [2001/5533] GBLI   — 4145 rows, max $34.47 ✓
  [2002/5533] GBUG   — 339 rows, max $58.17 ✓
  [2003/5533] GCBC   — 4145 rows, max $36.37 ✓
  [2004/5533] GCGR   — max $10.22 < $20.0 — skipped
  [2005/5533] GCGRU  — max $10.30 < $20.0 — skipped
  [2006/5533] GCGRW  — max $0.88 < $20.0 — skipped
  [2007/5533] GCL    — max $11.47 < $20.0 — skipped
  [2008/5533] GCLWW  — max $0.05 < $20.0 — skipped
  [2009/5533] GCMG   — max $13.60 < $20.0 — skipped
  [2010/5533] GCT    — 967 rows, max $51.80 ✓
  [2011/5533] GCTK   — 3313 rows, max $780000.00 ✓
  [2012/5533] GDC    — 2638 rows, max $285.00 ✓
  [2013/5533] GDEV   — 1438 rows, max $90.21 ✓
  [2014/5533] GDEVW  — max $0.01 < $20.0 — skipped
  [2015/5533] GDHG   — 805 rows, max $455812.50 ✓
  [2016/5533] GDRX   — 1446 rows, max $57.16 ✓
  [2017/5533] GDS    — 2424 rows, max $115.71 ✓
  [2018/5533] GDTC   — max $5.64 < $20.0 — skipped
  [2019/5533] GDYN   — 1923 rows, max $42.08 ✓
  [2020/5533] GECC   — 2422 rows, max $20.16 ✓
  [2021/5533] GECCG  — 197 rows, max $25.04 ✓
  [2022/5533] GECCH  — 438 rows, max $25.40 ✓
  [2023/5533] GECCI  — 548 rows, max $25.58 ✓
  [2024/5533] GEG    — 4145 rows, max $37.20 ✓
  [2025/5533] GEGGL  — 1008 rows, max $25.03 ✓
  [2026/5533] GEHC   — already stored, skipping
  [2027/5533] GELS   — max $4.79 < $20.0 — skipped
  [2028/5533] GEME   — 358 rows, max $45.13 ✓
  [2029/5533] GEMG   — 160 rows, max $322.14 ✓
  [2030/5533] GEMI   — 198 rows, max $32.52 ✓
  [2031/5533] GEN    — already stored, skipping
  [2032/5533] GENB   — max $16.42 < $20.0 — skipped
  [2033/5533] GENK   — 752 rows, max $20.08 ✓
  [2034/5533] GENVR  — max $12.05 < $20.0 — skipped
  [2035/5533] GENZ   — 4145 rows, max $52.06 ✓
  [2036/5533] GEOS   — 4145 rows, max $110.88 ✓
  [2037/5533] GEQ    — 13 rows, max $51.11 ✓
  [2038/5533] GERN   — max $6.38 < $20.0 — skipped
  [2039/5533] GEVG   — 132 rows, max $37.77 ✓
  [2040/5533] GEVO   — 3867 rows, max $153300.00 ✓
  [2041/5533] GEW    — 190 rows, max $55.33 ✓
  [2042/5533] GFAI   — 1190 rows, max $158.40 ✓
  [2043/5533] GFAIW  — max $0.08 < $20.0 — skipped
  [2044/5533] GFGF   — 1135 rows, max $36.15 ✓
  [2045/5533] GFLW   — 389 rows, max $33.58 ✓
  [2046/5533] GFS    — 1169 rows, max $89.83 ✓
  [2047/5533] GGAL   — 4145 rows, max $68.52 ✓
  [2048/5533] GGLL   — 954 rows, max $148.15 ✓
  [2049/5533] GGLS   — 947 rows, max $27.24 ✓
  [2050/5533] GGR    — 1338 rows, max $295.00 ✓
  [2051/5533] GGROW  — max $0.01 < $20.0 — skipped
  [2052/5533] GGRP   — max $17.66 < $20.0 — skipped
  [2053/5533] GH     — 1941 rows, max $179.10 ✓
  [2054/5533] GHRS   — 1256 rows, max $27.90 ✓
  [2055/5533] GHXIU  — max $10.07 < $20.0 — skipped
  [2056/5533] GIBO   — 715 rows, max $3136.00 ✓
  [2057/5533] GIBOW  — max $0.03 < $20.0 — skipped
  [2058/5533] GIEQ   — 25 rows, max $41.64 ✓
  [2059/5533] GIFT   — max $4.60 < $20.0 — skipped
  [2060/5533] GIGM   — max $16.60 < $20.0 — skipped
  [2061/5533] GIII   — 4145 rows, max $72.19 ✓
  [2062/5533] GILD   — already stored, skipping
  [2063/5533] GILT   — 4145 rows, max $21.30 ✓
  [2064/5533] GIND   — 309 rows, max $27.85 ✓
  [2065/5533] GINX   — 583 rows, max $35.43 ✓
  [2066/5533] GIPR   — max $6.63 < $20.0 — skipped
  [2067/5533] GIPRW  — max $0.05 < $20.0 — skipped
  [2068/5533] GITS   — max $7.80 < $20.0 — skipped
  [2069/5533] GIW    — max $10.08 < $20.0 — skipped
  [2070/5533] GIWWR  — max $0.26 < $20.0 — skipped
  [2071/5533] GIWWU  — max $10.50 < $20.0 — skipped
  [2072/5533] GIX    — max $9.95 < $20.0 — skipped
  [2073/5533] GIXXR  — max $0.31 < $20.0 — skipped
  [2074/5533] GIXXU  — max $10.32 < $20.0 — skipped
  [2075/5533] GKAT   — 211 rows, max $45.24 ✓
  [2076/5533] GLAD   — 4145 rows, max $26.74 ✓
  [2077/5533] GLBE   — 1287 rows, max $81.69 ✓
  [2078/5533] GLBS   — 4145 rows, max $43652.50 ✓
  [2079/5533] GLCR   — 314 rows, max $28.68 ✓
  [2080/5533] GLDB   — 168 rows, max $30.42 ✓
  [2081/5533] GLDI   — 3373 rows, max $165.29 ✓
  [2082/5533] GLDY   — max $15.87 < $20.0 — skipped
  [2083/5533] GLE    — max $5.19 < $20.0 — skipped
  [2084/5533] GLGG   — 213 rows, max $40.78 ✓
  [2085/5533] GLIBA  — 242 rows, max $40.23 ✓
  [2086/5533] GLIBK  — 242 rows, max $40.04 ✓
  [2087/5533] GLMD   — 3091 rows, max $3232.80 ✓
  [2088/5533] GLND   — max $13.00 < $20.0 — skipped
  [2089/5533] GLNDW  — max $0.99 < $20.0 — skipped
  [2090/5533] GLNG   — 4145 rows, max $57.87 ✓
  [2091/5533] GLOO   — max $9.50 < $20.0 — skipped
  [2092/5533] GLOW   — 493 rows, max $34.58 ✓
  [2093/5533] GLPI   — 3194 rows, max $48.18 ✓
  [2094/5533] GLRE   — 4145 rows, max $35.00 ✓
  [2095/5533] GLSI   — 1444 rows, max $72.22 ✓
  [2096/5533] GLUE   — 1257 rows, max $42.21 ✓
  [2097/5533] GLWG   — 76 rows, max $37.06 ✓
  [2098/5533] GLXG   — 448 rows, max $161.20 ✓
  [2099/5533] GLXY   — 279 rows, max $42.86 ✓
  [2100/5533] GMAB   — 4145 rows, max $48.72 ✓
  [2101/5533] GMEX   — 724 rows, max $30489.76 ✓
  [2102/5533] GMHS   — max $15.99 < $20.0 — skipped
  [2103/5533] GMM    — 681 rows, max $735.00 ✓
  [2104/5533] GNLN   — 1807 rows, max $278520000.00 ✓
  [2105/5533] GNLX   — 857 rows, max $38.00 ✓
  [2106/5533] GNMA   — 3608 rows, max $44.65 ✓
  [2107/5533] GNOM   — 1813 rows, max $110.00 ✓
  [2108/5533] GNPX   — 2072 rows, max $31800.00 ✓
  [2109/5533] GNSS   — max $8.15 < $20.0 — skipped
  [2110/5533] GNTA   — max $11.87 < $20.0 — skipped
  [2111/5533] GNTX   — 4145 rows, max $35.59 ✓
  [2112/5533] GO     — 1764 rows, max $46.64 ✓
  [2113/5533] GOAI   — max $7.62 < $20.0 — skipped
  [2114/5533] GOGO   — 3273 rows, max $34.34 ✓
  [2115/5533] GOOD   — max $17.45 < $20.0 — skipped
  [2116/5533] GOODN  — 1696 rows, max $22.79 ✓
  [2117/5533] GOODO  — 1259 rows, max $20.23 ✓
  [2118/5533] GOOG   — already stored, skipping
  [2119/5533] GOOGL  — already stored, skipping
  [2120/5533] GOOGM  — 17 rows, max $52.00 ✓
  [2121/5533] GOOGN  — 17 rows, max $51.85 ✓
  [2122/5533] GOSS   — 1855 rows, max $26.79 ✓
  [2123/5533] GOU    — 142 rows, max $37.44 ✓
  [2124/5533] GOVI   — 4145 rows, max $34.64 ✓
  [2125/5533] GOVX   — 1444 rows, max $3165.00 ✓
  [2126/5533] GP     — 1463 rows, max $324.10 ✓
  [2127/5533] GPAC   — max $10.01 < $20.0 — skipped
  [2128/5533] GPACU  — max $10.15 < $20.0 — skipped
  [2129/5533] GPACW  — max $0.28 < $20.0 — skipped
  [2130/5533] GPAT   — max $10.98 < $20.0 — skipped
  [2131/5533] GPATU  — max $11.69 < $20.0 — skipped
  [2132/5533] GPATW  — max $0.31 < $20.0 — skipped
  [2133/5533] GPCR   — 851 rows, max $93.79 ✓
  [2134/5533] GPIQ   — 667 rows, max $59.52 ✓
  [2135/5533] GPIX   — 667 rows, max $55.88 ✓
  [2136/5533] GPRE   — 4145 rows, max $43.86 ✓
  [2137/5533] GPRF   — 477 rows, max $50.46 ✓
  [2138/5533] GPRO   — 3018 rows, max $93.85 ✓

$MFPVV: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-06-27)

1 Failed download:
['MFPVV']: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-06-27)

  [3116/5533] MFPVV  — no data
  [3117/5533] MFVL   — 137 rows, max $21.08 ✓
  [3118/5533] MGEE   — 4145 rows, max $104.17 ✓
  [3119/5533] MGIH   — max $3.21 < $20.0 — skipped
  [3120/5533] MGN    — max $4.85 < $20.0 — skipped
  [3121/5533] MGNI   — 3077 rows, max $61.80 ✓
  [3122/5533] MGNX   — 3196 rows, max $40.21 ✓
  [3123/5533] MGPI   — 4145 rows, max $120.45 ✓
  [3124/5533] MGRC   — 4145 rows, max $126.22 ✓
  [3125/5533] MGRT   — 239 rows, max $142.20 ✓
  [3126/5533] MGRX   — 820 rows, max $60.00 ✓
  [3127/5533] MGTX   — 2023 rows, max $30.01 ✓
  [3128/5533] MGX    — max $12.25 < $20.0 — skipped
  [3129/5533] MGYR   — max $18.37 < $20.0 — skipped
  [3130/5533] MIDD   — 4145 rows, max $199.65 ✓

$MIDDV: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-06-27)

1 Failed download:
['MIDDV']: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-06-27)

  [3131/5533] MIDDV  — no data
  [3132/5533] MILN   — 2549 rows, max $50.61 ✓
  [3133/5533] MIMI   — 366 rows, max $107.50 ✓
  [3134/5533] MIND   — 4145 rows, max $260.90 ✓
  [3135/5533] MIRA   — max $7.42 < $20.0 — skipped
  [3136/5533] MIRM   — 1745 rows, max $117.28 ✓
  [3137/5533] MIST   — 1793 rows, max $27.15 ✓
  [3138/5533] MITK   — 4145 rows, max $23.03 ✓
  [3139/5533] MKAM   — 805 rows, max $32.19 ✓
  [3140/5533] MKDW   — 815 rows, max $345.90 ✓
  [3141/5533] MKDWW  — max $0.01 < $20.0 — skipped
  [3142/5533] MKLY   — max $10.19 < $20.0 — skipped
  [3143/5533] MKLYR  — max $0.23 < $20.0 — skipped
  [3144/5533] MKLYU  — max $10.33 < $20.0 — skipped
  [3145/5533] MKSI   — 4145 rows, max $420.56 ✓
  [3146/5533] MKTW   — 1453 rows, max $221.28 ✓
  [3147/5533] MKTX   — 4145 rows, max $553.43 ✓
  [3148/5533] MKZR   — 494 rows, max $46.92 ✓
  [3149/5533] MLAA   — max $10.14 < $20.0 — skipped
  [3150/5533] MLAAU  — max $10.40 < $20.0 — skipped
  [3151/5533] MLAAW  — max $0.27 < $20.0 — skipped
  [3152/5533] MLAB   — 4145 rows, max $324.50 ✓
  [3153/5533] MLCI   — max $18.09 < $20.0 — skipped
  [3154/5533] MLCIL  — 101 rows, max $24.30 ✓
  [3155/5533] MLCO   — 4145 rows, max $36.00 ✓
  [3156/5533] MLEC   — 1337 rows, max $2887.50 ✓
  [3157/5533] MLECW  — max $0.04 < $20.0 — skipped
  [3158/5533] MLGO   — 1308 rows, max $71520.00 ✓
  [3159/5533] MLKN   — 4145 rows, max $43.04 ✓
  [3160/5533] MLTX   — 1427 rows, max $63.86 ✓
  [3161/5533] MLYS   — 846 rows, max $47.33 ✓
  [3162/5533] MMED   — max $18.49 < $20.0 — skipped
  [3163/5533] MMLP   — 4145 rows, max $20.57 ✓
  [3164/5533] MMSI   — 4145 rows, max $110.29 ✓
  [3165/5533] MMTX   — max $10.12 < $20.0 — skipped
  [3166/5533] MMTXU  — max $10.32 < $20.0 — skipped
  [3167/5533] MMTXW  — max $0.13 < $20.0 — skipped
  [3168/5533] MMYT   — 3992 rows, max $120.46 ✓
  [3169/5533] MNDO   — max $2.45 < $20.0 — skipped
  [3170/5533] MNDR   — 555 rows, max $1090.80 ✓
  [3171/5533] MNDY   — 1267 rows, max $444.70 ✓
  [3172/5533] MNKD   — 4145 rows, max $54.80 ✓
  [3173/5533] MNOV   — max $13.91 < $20.0 — skipped
  [3174/5533] MNPR   — 1637 rows, max $135.00 ✓
  [3175/5533] MNRO   — 4145 rows, max $71.09 ✓
  [3176/5533] MNSB   — 4145 rows, max $27.74 ✓
  [3177/5533] MNSBP  — 1451 rows, max $25.20 ✓
  [3178/5533] MNST   — already stored, skipping
  [3179/5533] MNTK   — 1363 rows, max $20.32 ✓
  [3180/5533] MNTS   — 1629 rows, max $342750.00 ✓
  [3181/5533] MNTSW  — max $0.02 < $20.0 — skipped
  [3182/5533] MNVT   — 70 rows, max $34.88 ✓
  [3183/5533] MNY    — max $17.37 < $20.0 — skipped
  [3184/5533] MNYWW  — max $5.90 < $20.0 — skipped
  [3185/5533] MNZL   — 150 rows, max $61.61 ✓
  [3186/5533] MOB    — max $10.20 < $20.0 — skipped
  [3187/5533] MOBBW  — max $2.16 < $20.0 — skipped
  [3188/5533] MOBI   — max $14.53 < $20.0 — skipped
  [3189/5533] MOBX   — 1222 rows, max $118.76 ✓
  [3190/5533] MOBXW  — max $0.30 < $20.0 — skipped
  [3191/5533] MODD   — 1097 rows, max $159.60 ✓
  [3192/5533] MODL   — 929 rows, max $51.14 ✓
  [3193/5533] MOLN   — 1263 rows, max $31.89 ✓
  [3194/5533] MOMO   — 2901 rows, max $32.65 ✓
  [3195/5533] MOOD   — 1029 rows, max $44.45 ✓
  [3196/5533] MORN   — 4145 rows, max $354.60 ✓
  [3197/5533] MOVE   — 1322 rows, max $733.43 ✓
  [3198/5533] MPAA   — 4145 rows, max $40.25 ✓
  [3199/5533] MPB    — 4145 rows, max $34.38 ✓
  [3200/5533] MPG    — max $12.80 < $20.0 — skipped
  [3201/5533] MPLT   — 167 rows, max $32.13 ✓
  [3202/5533] MPWR   — already stored, skipping
  [3203/5533] MQ     — 1268 rows, max $33.25 ✓
  [3204/5533] MQQQ   — 455 rows, max $252.82 ✓
  [3205/5533] MRA    — 22 rows, max $24.79 ✓
  [3206/5533] MRAL   — 328 rows, max $348.50 ✓
  [3207/5533] MRAM   — 2442 rows, max $44.01 ✓
  [3208/5533] MRBK   — 2169 rows, max $20.45 ✓
  [3209/5533] MRCY   — 4145 rows, max $120.30 ✓
  [3210/5533] MRDN   — 4145 rows, max $1636199956480.00 ✓
  [3211/5533] MREO   — max $6.50 < $20.0 — skipped
  [3212/5533] MRKR   — 4145 rows, max $7200.00 ✓
  [3213/5533] MRLN   — max $16.09 < $20.0 — skipped
  [3214/5533] MRM    — max $17.34 < $20.0 — skipped
  [3215/5533] MRNA   — already stored, skipping
  [3216/5533] MRNO   — 1074 rows, max $21.25 ✓
  [3217/5533] MRNOW  — max $0.08 < $20.0 — skipped
  [3218/5533] MRTN   — 4145 rows, max $22.04 ✓
  [3219/5533] MRVI   — 1404 rows, max $60.62 ✓
  [3220/5533] MRVL   — already stored, skipping
  [3221/5533] MRVU   — 93 rows, max $294.98 ✓
  [3222/5533] MRX    — 544 rows, max $66.51 ✓
  [3223/5533] MSAI   — 1156 rows, max $538.00 ✓
  [3224/5533] MSAIW  — max $0.05 < $20.0 — skipped
  [3225/5533] MSBI   — 2537 rows, max $30.51 ✓
  [3226/5533] MSBIP  — 960 rows, max $25.45 ✓
  [3227/5533] MSEX   — 4145 rows, max $109.78 ✓
  [3228/5533] MSFD   — 953 rows, max $25.08 ✓
  [3229/5533] MSFL   — 571 rows, max $34.89 ✓
  [3230/5533] MSFT   — already stored, skipping
  [3231/5533] MSFU   — 954 rows, max $52.92 ✓
  [3232/5533] MSGM   — 1369 rows, max $350.00 ✓
  [3233/5533] MSGY   — 245 rows, max $20.52 ✓
  [3234/5533] MSLE   — 3493 rows, max $208.08 ✓
  [3235/5533] MSR    — 31 rows, max $24.13 ✓
  [3236/5533] MSS    — 683 rows, max $152.10 ✓
  [3237/5533] MST    — 289 rows, max $283.37 ✓
  [3238/5533] MSTP   — 263 rows, max $643.18 ✓
  [3239/5533] MSTR   — already stored, skipping
  [3240/5533] MSTX   — 467 rows, max $1250.49 ✓
  [3241/5533] MSW    — max $8.50 < $20.0 — skipped
  [3242/5533] MTC    — 1876 rows, max $1524.00 ✓
  [3243/5533] MTCH   — 4145 rows, max $169.43 ✓
  [3244/5533] MTEK   — max $5.83 < $20.0 — skipped
  [3245/5533] MTEKW  — max $0.30 < $20.0 — skipped
  [3246/5533] MTEN   — 548 rows, max $4260.00 ✓
  [3247/5533] MTEX   — 4145 rows, max $39.10 ✓
  [3248/5533] MTLS   — 3019 rows, max $80.62 ✓
  [3249/5533] MTRX   — 4145 rows, max $37.21 ✓
  [3250/5533] MTSI   — 3591 rows, max $409.68 ✓
  [3251/5533] MTVA   — 2486 rows, max $1390620.00 ✓
  [3252/5533] MTYY   — 191 rows, max $64.44 ✓
  [3253/5533] MU     — already stored, skipping
  [3254/5533] MUD    — 422 rows, max $3132.73 ✓
  [3255/5533] MULL   — 405 rows, max $42.93 ✓
  [3256/5533] MULT   — 208 rows, max $25.19 ✓
  [3257/5533] MUU    — 428 rows, max $1229.60 ✓
  [3258/5533] MUYY   — 52 rows, max $23.91 ✓
  [3259/5533] MUZE   — max $9.94 < $20.0 — skipped
  [3260/5533] MUZEU  — max $10.34 < $20.0 — skipped
  [3261/5533] MUZEW  — max $0.30 < $20.0 — skipped
  [3262/5533] MVBF   — 3493 rows, max $39.14 ✓
  [3263/5533] MVIS   — 4145 rows, max $28.80 ✓
  [3264/5533] MVLL   — 328 rows, max $74.07 ✓
  [3265/5533] MVST   — 1823 rows, max $24.50 ✓
  [3266/5533] MVSTW  — max $0.04 < $20.0 — skipped
  [3267/5533] MWC    — max $8.20 < $20.0 — skipped
  [3268/5533] MWH    — 93 rows, max $46.77 ✓
  [3269/5533] MWYN   — max $10.22 < $20.0 — skipped
  [3270/5533] MXCT   — max $17.20 < $20.0 — skipped
  [3271/5533] MXL    — 4090 rows, max $102.27 ✓
  [3272/5533] MYCF   — 440 rows, max $25.06 ✓
  [3273/5533] MYCG   — 440 rows, max $24.99 ✓
  [3274/5533] MYCH   — 440 rows, max $24.90 ✓
  [3275/5533] MYCI   — 440 rows, max $24.84 ✓
  [3276/5533] MYCJ   — 440 rows, max $24.84 ✓
  [3277/5533] MYCK   — 440 rows, max $25.00 ✓
  [3278/5533] MYCL   — 440 rows, max $24.94 ✓
  [3279/5533] MYCM   — 440 rows, max $24.87 ✓
  [3280/5533] MYCN   — 440 rows, max $24.72 ✓
  [3281/5533] MYCO   — 195 rows, max $24.76 ✓
  [3282/5533] MYFW   — 1995 rows, max $33.45 ✓
  [3283/5533] MYGN   — 4145 rows, max $50.34 ✓
  [3284/5533] MYHA   — 84 rows, max $25.00 ✓
  [3285/5533] MYHB   — 84 rows, max $25.02 ✓
  [3286/5533] MYHC   — 84 rows, max $25.21 ✓
  [3287/5533] MYHD   — 84 rows, max $25.07 ✓
  [3288/5533] MYHE   — 84 rows, max $25.02 ✓
  [3289/5533] MYMF   — 440 rows, max $24.89 ✓
  [3290/5533] MYMG   — 440 rows, max $24.75 ✓
  [3291/5533] MYMH   — 440 rows, max $24.64 ✓
  [3292/5533] MYMI   — 440 rows, max $24.74 ✓
  [3293/5533] MYMJ   — 440 rows, max $24.92 ✓
  [3294/5533] MYMK   — 195 rows, max $25.25 ✓
  [3295/5533] MYPS   — max $11.78 < $20.0 — skipped
  [3296/5533] MYRG   — 4145 rows, max $487.33 ✓
  [3297/5533] MYSE   — 1222 rows, max $150.10 ✓
  [3298/5533] MYSEW  — max $10.28 < $20.0 — skipped
  [3299/5533] MYSZ   — 2484 rows, max $32910.00 ✓
  [3300/5533] MYX    — max $9.96 < $20.0 — skipped
  [3301/5533] MYXXR  — max $0.24 < $20.0 — skipped
  [3302/5533] MYXXU  — max $10.22 < $20.0 — skipped
  [3303/5533] MYXXW  — max $0.06 < $20.0 — skipped
  [3304/5533] MZTI   — 4145 rows, max $203.69 ✓
  [3305/5533] NA     — 994 rows, max $120.50 ✓
  [3306/5533] NAAS   — 2181 rows, max $28400.00 ✓
  [3307/5533] NAGE   — max $18.74 < $20.0 — skipped
  [3308/5533] NAII   — max $19.15 < $20.0 — skipped
  [3309/5533] NAKA   — 519 rows, max $1001.20 ✓
  [3310/5533] NAMI   — max $5.31 < $20.0 — skipped
  [3311/5533] NAMM   — 265 rows, max $31.22 ✓
  [3312/5533] NAMMW  — max $13.90 < $20.0 — skipped
  [3313/5533] NAMS   — 1351 rows, max $41.45 ✓
  [3314/5533] NAMSW  — 1350 rows, max $29.99 ✓
  [3315/5533] NATH   — 4145 rows, max $110.57 ✓
  [3316/5533] NATO   — 427 rows, max $44.22 ✓
  [3317/5533] NATR   — 4145 rows, max $27.80 ✓
  [3318/5533] NAUT   — 1478 rows, max $22.43 ✓
  [3319/5533] NAVI   — max $18.94 < $20.0 — skipped
  [3320/5533] NAVN   — 164 rows, max $22.87 ✓
  [3321/5533] NB     — max $11.67 < $20.0 — skipped
  [3322/5533] NBBK   — 625 rows, max $22.56 ✓
  [3323/5533] NBIG   — 167 rows, max $43.67 ✓
  [3324/5533] NBIL   — 181 rows, max $63.09 ✓
  [3325/5533] NBIS   — 421 rows, max $286.69 ✓
  [3326/5533] NBIX   — 4145 rows, max $167.35 ✓
  [3327/5533] NBN    — 4145 rows, max $130.25 ✓
  [3328/5533] NBP    — 1618 rows, max $84.43 ✓
  [3329/5533] NBRG   — max $9.98 < $20.0 — skipped
  [3330/5533] NBRGR  — max $0.25 < $20.0 — skipped
  [3331/5533] NBRGU  — max $10.22 < $20.0 — skipped
  [3332/5533] NBTB   — 4145 rows, max $49.81 ✓
  [3333/5533] NBTX   — 1390 rows, max $55.07 ✓
  [3334/5533] NCEL   — 1358 rows, max $2340.00 ✓
  [3335/5533] NCEW   — 380 rows, max $20.80 ✓
  [3336/5533] NCI    — 546 rows, max $380.00 ✓
  [3337/5533] NCIQ   — 342 rows, max $33.99 ✓
  [3338/5533] NCMI   — 4145 rows, max $92.77 ✓
  [3339/5533] NCNA   — 2197 rows, max $149200.00 ✓
  [3340/5533] NCNO   — 1496 rows, max $98.04 ✓
  [3341/5533] NCPB   — 579 rows, max $25.20 ✓
  [3342/5533] NCPL   — 4145 rows, max $7000.00 ✓
  [3343/5533] NCPLW  — max $0.03 < $20.0 — skipped
  [3344/5533] NCRA   — max $7.50 < $20.0 — skipped
  [3345/5533] NCSM   — 2303 rows, max $540.80 ✓
  [3346/5533] NCT    — 313 rows, max $200.25 ✓
  [3347/5533] NCTY   — 4145 rows, max $2559.00 ✓
  [3348/5533] NDAA   — 422 rows, max $24.28 ✓
  [3349/5533] NDAQ   — already stored, skipping
  [3350/5533] NDLS   — 3268 rows, max $386.40 ✓
  [3351/5533] NDRA   — 2259 rows, max $189000.00 ✓
  [3352/5533] NDSN   — already stored, skipping
  [3353/5533] NECB   — 4145 rows, max $29.30 ✓
  [3354/5533] NEGG   — 4070 rows, max $2012.80 ✓
  [3355/5533] NEMG   — 152 rows, max $32.19 ✓
  [3356/5533] NEO    — 4145 rows, max $59.88 ✓
  [3357/5533] NEOG   — 4145 rows, max $48.33 ✓
  [3358/5533] NEON   — 4145 rows, max $82.80 ✓
  [3359/5533] NEOV   — max $7.17 < $20.0 — skipped
  [3360/5533] NEOVW  — max $1.41 < $20.0 — skipped
  [3361/5533] NEPH   — 4145 rows, max $216.00 ✓
  [3362/5533] NERV   — 3015 rows, max $117.60 ✓
  [3363/5533] NESR   — 494 rows, max $26.98 ✓
  [3364/5533] NETG   — max $17.52 < $20.0 — skipped
  [3365/5533] NEUP   — 1135 rows, max $176.76 ✓
  [3366/5533] NEWT   — 4145 rows, max $25.34 ✓
  [3367/5533] NEWTG  — 519 rows, max $25.25 ✓
  [3368/5533] NEWTH  — 445 rows, max $25.91 ✓
  [3369/5533] NEWTI  — 705 rows, max $25.39 ✓
  [3370/5533] NEWTO  — 97 rows, max $26.25 ✓
  [3371/5533] NEWTP  — 217 rows, max $24.69 ✓
  [3372/5533] NEWZ   — 553 rows, max $30.22 ✓
  [3373/5533] NEXM   — 4145 rows, max $1010.00 ✓
  [3374/5533] NEXN   — 1261 rows, max $23.45 ✓
  [3375/5533] NEXR   — 961 rows, max $4464.88 ✓
  [3376/5533] NEXRW  — max $0.04 < $20.0 — skipped
  [3377/5533] NEXT   — max $12.00 < $20.0 — skipped
  [3378/5533] NFBK   — max $15.05 < $20.0 — skipped
  [3379/5533] NFE    — 1861 rows, max $55.45 ✓
  [3380/5533] NFLX   — already stored, skipping
  [3381/5533] NFRX   — 102 rows, max $27.48 ✓
  [3382/5533] NFTY   — 3603 rows, max $63.42 ✓
  [3383/5533] NFXL   — 433 rows, max $69.06 ✓
  [3384/5533] NFXS   — 433 rows, max $24.33 ✓
  [3385/5533] NGEN   — max $5.97 < $20.0 — skipped
  [3386/5533] NGHT   — 56 rows, max $27.64 ✓
  [3387/5533] NGNE   — 3095 rows, max $442.60 ✓
  [3388/5533] NHIC   — max $11.44 < $20.0 — skipped
  [3389/5533] NHICU  — max $14.25 < $20.0 — skipped
  [3390/5533] NHICW  — max $0.37 < $20.0 — skipped
  [3391/5533] NHIV   — max $10.05 < $20.0 — skipped
  [3392/5533] NHIVU  — max $10.25 < $20.0 — skipped
  [3393/5533] NHIVW  — max $0.45 < $20.0 — skipped
  [3394/5533] NHP    — max $15.04 < $20.0 — skipped
  [3395/5533] NHPAP  — 1645 rows, max $23.15 ✓
  [3396/5533] NHPBP  — 1187 rows, max $22.85 ✓
  [3397/5533] NHTC   — max $16.92 < $20.0 — skipped
  [3398/5533] NICE   — 4145 rows, max $315.02 ✓
  [3399/5533] NICM   — max $8.23 < $20.0 — skipped
  [3400/5533] NIKL   — 819 rows, max $20.59 ✓
  [3401/5533] NIOBW  — max $1.89 < $20.0 — skipped
  [3402/5533] NIOG   — 130 rows, max $25.87 ✓
  [3403/5533] NIPG   — max $16.50 < $20.0 — skipped
  [3404/5533] NIU    — 1930 rows, max $49.43 ✓
  [3405/5533] NIVF   — 1072 rows, max $37020.00 ✓
  [3406/5533] NIVFW  — max $0.02 < $20.0 — skipped
  [3407/5533] NIXT   — 450 rows, max $31.95 ✓
  [3408/5533] NIXX   — 3457 rows, max $2975.00 ✓
  [3409/5533] NIXXW  — max $0.01 < $20.0 — skipped
  [3410/5533] NKLR   — max $18.26 < $20.0 — skipped
  [3411/5533] NKSH   — 4145 rows, max $38.12 ✓
  [3412/5533] NKTR   — 4145 rows, max $1626.60 ✓
  [3413/5533] NKTX   — 1498 rows, max $75.62 ✓
  [3414/5533] NMFC   — max $9.83 < $20.0 — skipped
  [3415/5533] NMFCZ  — 647 rows, max $25.50 ✓
  [3416/5533] NMIH   — 3175 rows, max $43.15 ✓
  [3417/5533] NMP    — max $10.28 < $20.0 — skipped
  [3418/5533] NMPAR  — max $0.16 < $20.0 — skipped
  [3419/5533] NMPAU  — max $10.45 < $20.0 — skipped
  [3420/5533] NMRA   — max $19.76 < $20.0 — skipped
  [3421/5533] NMRK   — max $19.43 < $20.0 — skipped
  [3422/5533] NMTC   — 2082 rows, max $161.82 ✓
  [3423/5533] NN     — 1418 rows, max $23.59 ✓
  [3424/5533] NNAVW  — max $7.22 < $20.0 — skipped
  [3425/5533] NNBR   — 4145 rows, max $30.91 ✓
  [3426/5533] NNDM   — 2592 rows, max $88.90 ✓
  [3427/5533] NNE    — 535 rows, max $56.63 ✓
  [3428/5533] NNNN   — 340 rows, max $52.10 ✓
  [3429/5533] NNOX   — 1468 rows, max $89.39 ✓
  [3430/5533] NODK   — 2333 rows, max $20.32 ✓
  [3431/5533] NOEM   — max $10.45 < $20.0 — skipped
  [3432/5533] NOEMR  — max $0.18 < $20.0 — skipped
  [3433/5533] NOEMU  — max $11.84 < $20.0 — skipped
  [3434/5533] NOEMW  — max $0.13 < $20.0 — skipped
  [3435/5533] NOMA   — max $11.50 < $20.0 — skipped
  [3436/5533] NOVT   — 4145 rows, max $186.20 ✓
  [3437/5533] NOVTU  — 158 rows, max $70.65 ✓
  [3438/5533] NOWL   — 240 rows, max $26.87 ✓
  [3439/5533] NPAC   — max $10.50 < $20.0 — skipped
  [3440/5533] NPACU  — max $10.77 < $20.0 — skipped
  [3441/5533] NPACW  — max $0.55 < $20.0 — skipped
  [3442/5533] NPCE   — 1301 rows, max $26.50 ✓
  [3443/5533] NPFI   — 578 rows, max $26.08 ✓
  [3444/5533] NPT    — 170 rows, max $20.50 ✓
  [3445/5533] NRC    — 3293 rows, max $61.11 ✓
  [3446/5533] NRDS   — 1164 rows, max $28.30 ✓
  [3447/5533] NRES   — 585 rows, max $35.22 ✓
  [3448/5533] NRIM   — 4145 rows, max $29.38 ✓
  [3449/5533] NRIX   — 1488 rows, max $50.17 ✓
  [3450/5533] NRSN   — max $6.23 < $20.0 — skipped
  [3451/5533] NRSNW  — max $0.21 < $20.0 — skipped
  [3452/5533] NRXP   — 2151 rows, max $627.10 ✓
  [3453/5533] NSI    — 639 rows, max $39.85 ✓
  [3454/5533] NSIT   — 4145 rows, max $225.24 ✓
  [3455/5533] NSPR   — 3824 rows, max $74550000.00 ✓
  [3456/5533] NSSC   — 4145 rows, max $56.24 ✓
  [3457/5533] NSTS   — max $13.84 < $20.0 — skipped
  [3458/5533] NSYS   — max $18.38 < $20.0 — skipped
  [3459/5533] NTAP   — already stored, skipping
  [3460/5533] NTCL   — 383 rows, max $33.00 ✓
  [3461/5533] NTCT   — 4145 rows, max $47.33 ✓
  [3462/5533] NTES   — 4145 rows, max $156.20 ✓
  [3463/5533] NTGR   — 4145 rows, max $48.23 ✓
  [3464/5533] NTHI   — max $16.55 < $20.0 — skipped
  [3465/5533] NTIC   — max $19.08 < $20.0 — skipped
  [3466/5533] NTLA   — 2549 rows, max $176.78 ✓
  [3467/5533] NTNX   — 2447 rows, max $83.07 ✓
  [3468/5533] NTRA   — 2763 rows, max $260.74 ✓
  [3469/5533] NTRB   — max $10.72 < $20.0 — skipped
  [3470/5533] NTRBW  — max $9.00 < $20.0 — skipped
  [3471/5533] NTRP   — 3948 rows, max $10320.00 ✓
  [3472/5533] NTRS   — already stored, skipping
  [3473/5533] NTRSO  — 1672 rows, max $21.60 ✓
  [3474/5533] NTSK   — 194 rows, max $25.79 ✓
  [3475/5533] NTWK   — 4145 rows, max $23.20 ✓
  [3476/5533] NTWO   — max $10.67 < $20.0 — skipped
  [3477/5533] NTWOU  — max $10.99 < $20.0 — skipped
  [3478/5533] NTWOW  — max $0.39 < $20.0 — skipped
  [3479/5533] NUAI   — max $11.88 < $20.0 — skipped
  [3480/5533] NUAIW  — max $1.89 < $20.0 — skipped
  [3481/5533] NUCL   — max $13.21 < $20.0 — skipped
  [3482/5533] NUCLW  — max $1.50 < $20.0 — skipped
  [3483/5533] NUG    — 152 rows, max $20.13 ✓
  [3484/5533] NUGY   — max $16.86 < $20.0 — skipped
  [3485/5533] NUIF   — 6 rows, max $26.08 ✓
  [3486/5533] NUSB   — 578 rows, max $25.25 ✓
  [3487/5533] NUTR   — max $9.30 < $20.0 — skipped
  [3488/5533] NUTX   — 1061 rows, max $6000.00 ✓
  [3489/5533] NUVL   — 1233 rows, max $123.58 ✓
  [3490/5533] NUWE   — 3610 rows, max $721617092608.00 ✓
  [3491/5533] NVAX   — 4145 rows, max $319.93 ✓
  [3492/5533] NVCR   — 2699 rows, max $225.58 ✓
  [3493/5533] NVCT   — 1101 rows, max $27.87 ✓
  [3494/5533] NVD    — 714 rows, max $530.78 ✓
  [3495/5533] NVDA   — already stored, skipping
  [3496/5533] NVDD   — 699 rows, max $250.62 ✓
  [3497/5533] NVDG   — 383 rows, max $24.54 ✓
  [3498/5533] NVDL   — 886 rows, max $43.02 ✓
  [3499/5533] NVDS   — 992 rows, max $15312.59 ✓
  [3500/5533] NVDU   — 699 rows, max $171.02 ✓
  [3501/5533] NVEC   — 4145 rows, max $116.92 ✓
  [3502/5533] NVMI   — 4145 rows, max $605.65 ✓
  [3503/5533] NVNI   — 1127 rows, max $117.30 ✓
  [3504/5533] NVNIW  — max $0.03 < $20.0 — skipped
  [3505/5533] NVNO   — 2029 rows, max $4585.00 ✓
  [3506/5533] NVPS   — 6 rows, max $28.25 ✓
  [3507/5533] NVTS   — 1175 rows, max $31.79 ✓
  [3508/5533] NVVE   — 1546 rows, max $356320.00 ✓
  [3509/5533] NVX    — 1103 rows, max $22.25 ✓
  [3510/5533] NVYY   — max $13.78 < $20.0 — skipped
  [3511/5533] NWBI   — max $15.09 < $20.0 — skipped
  [3512/5533] NWE    — 4145 rows, max $72.67 ✓
  [3513/5533] NWFL   — 4145 rows, max $32.14 ✓
  [3514/5533] NWGL   — max $19.27 < $20.0 — skipped
  [3515/5533] NWL    — 4145 rows, max $36.18 ✓
  [3516/5533] NWPX   — 4145 rows, max $146.63 ✓
  [3517/5533] NWS    — already stored, skipping
  [3518/5533] NWSA   — already stored, skipping
  [3519/5533] NWTG   — 719 rows, max $8691.00 ✓
  [3520/5533] NXGL   — max $4.93 < $20.0 — skipped
  [3521/5533] NXGLW  — max $0.17 < $20.0 — skipped
  [3522/5533] NXL    — max $4.36 < $20.0 — skipped
  [3523/5533] NXPI   — already stored, skipping
  [3524/5533] NXPL   — 4145 rows, max $7425000.00 ✓
  [3525/5533] NXST   — 4145 rows, max $251.25 ✓
  [3526/5533] NXT    — 847 rows, max $156.40 ✓
  [3527/5533] NXTC   — 1793 rows, max $1106.64 ✓
  [3528/5533] NXTG   — 3860 rows, max $166.95 ✓
  [3529/5533] NXTS   — 3927 rows, max $9003750.00 ✓
  [3530/5533] NXTT   — 989 rows, max $762940.00 ✓
  [3531/5533] NXXT   — 1200 rows, max $104.00 ✓
  [3532/5533] NYAX   — 944 rows, max $75.81 ✓
  [3533/5533] NYXH   — 1297 rows, max $37.00 ✓
  [3534/5533] NZAC   — 2911 rows, max $46.76 ✓
  [3535/5533] OABI   — max $10.31 < $20.0 — skipped
  [3536/5533] OABIW  — max $0.09 < $20.0 — skipped
  [3537/5533] OACC   — max $10.73 < $20.0 — skipped
  [3538/5533] OACCU  — max $11.06 < $20.0 — skipped
  [3539/5533] OACCW  — max $0.78 < $20.0 — skipped
  [3540/5533] OBA    — max $10.25 < $20.0 — skipped
  [3541/5533] OBAI   — 99 rows, max $33.00 ✓
  [3542/5533] OBAWU  — max $11.24 < $20.0 — skipped

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ZAZZT"}}}
$ZAZZT: possibly delisted; no timezone found

1 Failed download:
['ZAZZT']: possibly delisted; no timezone found

  [5487/5533] ZAZZT  — no data
  [5488/5533] ZBAO   — max $4.61 < $20.0 — skipped
  [5489/5533] ZBIO   — 447 rows, max $43.17 ✓
  [5490/5533] ZBRA   — already stored, skipping
  [5491/5533] ZBZZT  — 1 rows, max $199999.98 ✓
  [5492/5533] ZCMD   — 1593 rows, max $10242.40 ✓

$ZCZZT: possibly delisted; no timezone found

1 Failed download:
['ZCZZT']: possibly delisted; no timezone found

  [5493/5533] ZCZZT  — no data
  [5494/5533] ZD     — 4145 rows, max $132.98 ✓
  [5495/5533] ZDAI   — 484 rows, max $1717.76 ✓
  [5496/5533] ZENA   — max $10.30 < $20.0 — skipped
  [5497/5533] ZEO    — max $11.52 < $20.0 — skipped
  [5498/5533] ZEOWW  — max $0.04 < $20.0 — skipped
  [5499/5533] ZG     — 3756 rows, max $203.79 ✓
  [5500/5533] ZHOG   — 704 rows, max $51.47 ✓
  [5501/5533] ZION   — 4145 rows, max $69.33 ✓
  [5502/5533] ZIONP  — 4145 rows, max $22.66 ✓
  [5503/5533] ZJK    — max $17.26 < $20.0 — skipped
  [5504/5533] ZJYL   — 815 rows, max $276.11 ✓
  [5505/5533] ZJZZT  — max $10.02 < $20.0 — skipped
  [5506/5533] ZKIN   — max $12.35 < $20.0 — skipped
  [5507/5533] ZKP    — max $10.01 < $20.0 — skipped
  [5508/5533] ZKPU   — max $10.15 < $20.0 — skipped
  [5509/5533] ZKPW   — max $0.33 < $20.0 — skipped
  [5510/5533] ZLAB   — 2203 rows, max $191.71 ✓
  [5511/5533] ZM     — 1807 rows, max $568.34 ✓
  [5512/5533] ZMUN   — 186 rows, max $50.21 ✓
  [5513/5533] ZNB    — 4145 rows, max $897600000.00 ✓
  [5514/5533] ZNTL   — 1565 rows, max $84.79 ✓
  [5515/5533] ZOOZ   — 558 rows, max $82.00 ✓
  [5516/5533] ZOOZW  — max $0.03 < $20.0 — skipped
  [5517/5533] ZS     — already stored, skipping
  [5518/5533] ZSQR   — 1386 rows, max $239.00 ✓
  [5519/5533] ZSTK   — 1288 rows, max $13416.00 ✓
  [5520/5533] ZTEK   — max $5.70 < $20.0 — skipped
  [5521/5533] ZTEN   — 616 rows, max $51.08 ✓
  [5522/5533] ZTG    — max $4.17 < $20.0 — skipped
  [5523/5533] ZTOP   — 301 rows, max $51.72 ✓
  [5524/5533] ZTRE   — 616 rows, max $50.77 ✓
  [5525/5533] ZTWO   — 616 rows, max $50.52 ✓
  [5526/5533] ZUMZ   — 4145 rows, max $54.63 ✓
  [5527/5533] ZURA   — 820 rows, max $33.21 ✓
  [5528/5533] ZVRA   — 2816 rows, max $378.08 ✓
  [5529/5533] ZVZZT  — max $12.19 < $20.0 — skipped
  [5530/5533] ZWZZT  — max $10.00 < $20.0 — skipped
  [5531/5533] ZXZZT  — 1 rows, max $22.53 ✓
  [5532/5533] ZYBT   — max $14.15 < $20.0 — skipped
  [5533/5533] ZYME   — 2303 rows, max $56.81 ✓

 Done!
   Stored  : 3851 tickers
   Skipped : 1676 tickers below $20.0
   Failed  : 6 tickers — ['DALI', 'FBYDP', 'MFPVV', 'MIDDV', 'ZAZZT', 'ZCZZT']

---
## 5. Load a single ticker

In [6]:
TICKER = "NVDA"   # ← change this

df_ticker = load_csv_from_github(
    GITHUB_REPO,
    f"{STOCKS_PREFIX}/prices_{TICKER}.csv",
    GITHUB_TOKEN,
)
df_ticker["Date"] = pd.to_datetime(df_ticker["Date"])
print(f"{TICKER}: {len(df_ticker)} rows, {df_ticker['Date'].min().date()} → {df_ticker['Date'].max().date()}")
df_ticker.tail()

NVDA: 4145 rows, 2010-01-04 → 2026-06-26

,Date,Close,High,Low,Open,Volume,ticker
4140,2026-06-22,208.649994,213.990005,207.720001,211.440002,122041400,NVDA
4141,2026-06-23,200.039993,203.770004,200.000000,202.169998,153496200,NVDA
4142,2026-06-24,199.000000,201.669998,196.580002,200.119995,151810700,NVDA
4143,2026-06-25,195.740005,200.800003,192.130005,200.080002,149550000,NVDA
4144,2026-06-26,NaN,NaN,NaN,NaN,177757849,NVDA

---
## 6. Load the master index

In [7]:
df_index = load_csv_from_github(
    GITHUB_REPO,
    f"{STOCKS_PREFIX}/index.csv",
    GITHUB_TOKEN,
)
print(f"{len(df_index)} tickers in index")
print(f"Sectors: {df_index['sector'].value_counts().to_dict()}")
df_index.sort_values("max_price", ascending=False).head(20)

3851 tickers in index
Sectors: {'NASDAQ': 3851}

,ticker,name,sector,max_price,row_count,start_date,last_updated
3795,XTIA,"XTI Aerospace, Inc. Common Stock - Common Stock",NASDAQ,1.974375e+13,3493,2012-08-03,2026-06-28
2668,PPCB,"Propanc Biopharma, Inc. - Common Stock",NASDAQ,6.250000e+12,3388,2013-01-07,2026-06-27
2194,MRDN,Meridian Holdings Inc. - Common Stock,NASDAQ,1.636200e+12,4145,2010-01-04,2026-06-27
2389,NUWE,"Nuwellis, Inc. - Common Stock",NASDAQ,7.216171e+11,3610,2012-02-16,2026-06-27
1821,JAGX,"Jaguar Health, Inc. - Common Stock",NASDAQ,8.694591e+10,2798,2015-05-12,2026-06-27
3693,WHLR,"Wheeler Real Estate Investment Trust, Inc. - C...",NASDAQ,6.522079e+10,3420,2012-11-19,2026-06-28
3363,TNXP,Tonix Pharmaceuticals Holding Corp. - Common S...,NASDAQ,1.920000e+10,3552,2012-05-10,2026-06-27
1057,EJH,E-Home Household Service Holdings Limited - Or...,NASDAQ,6.750000e+09,1285,2021-05-14,2026-06-27
3133,SMX,SMX (Security Matters) Public Limited Company ...,NASDAQ,2.444036e+09,1140,2021-12-09,2026-06-27
673,CENN,Cenntro Inc. - Common Stock,NASDAQ,2.430000e+09,3457,2012-09-25,2026-06-27
3798,XXII,"22nd Century Group, Inc - Common Stock",NASDAQ,1.386072e+09,3877,2011-01-26,2026-06-28
3077,SINT,"SiNtx Technologies, Inc. - Common Stock",NASDAQ,9.514800e+08,3110,2014-02-13,2026-06-27
3836,ZNB,Zeta Network Group - Class A Ordinary Shares,NASDAQ,8.976000e+08,4145,2010-01-04,2026-06-28
398,BDRX,Biodexa Pharmaceuticals plc - American Deposit...,NASDAQ,7.350000e+08,2653,2015-12-07,2026-06-27
679,CETX,Cemtrex Inc. - Common Stock,NASDAQ,7.057069e+08,2767,2015-06-25,2026-06-27
1452,GNLN,"Greenlane Holdings, Inc. - Class A Common Stock",NASDAQ,2.785200e+08,1807,2019-04-18,2026-06-27
745,CLRB,"Cellectar Biosciences, Inc. - Common Stock",NASDAQ,2.698920e+08,4145,2010-01-04,2026-06-27
1306,FRGT,"Freight Technologies, Inc. - Ordinary Shares",NASDAQ,1.679515e+08,2233,2017-08-08,2026-06-27
1561,HIND,"Vyome Holdings, Inc. - Common Stock",NASDAQ,1.305000e+08,2443,2016-10-06,2026-06-27
1094,ENVB,"Enveric Biosciences, Inc. - Common Stock",NASDAQ,1.215000e+08,2804,2015-05-04,2026-06-27

---
## 7. Incremental update — refresh all stored tickers

In [4]:
import yfinance as yf

if GITHUB_TOKEN is None:
    print("  GITHUB_TOKEN not set.")
else:
    # Load the index to know which tickers we have
    df_index = load_csv_from_github(GITHUB_REPO, f"{STOCKS_PREFIX}/index.csv", GITHUB_TOKEN)
    tickers  = df_index["ticker"].tolist()
    today    = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    print(f"Updating {len(tickers)} tickers through {today} …\n")
    updated = 0

    for i, ticker in enumerate(tickers, 1):
        if not isinstance(ticker, str) or ticker.lower() == "nan":
            continue
        path = f"{STOCKS_PREFIX}/prices_{ticker}.csv"
        try:
            df_existing = load_csv_from_github(GITHUB_REPO, path, GITHUB_TOKEN)
            df_existing["Date"] = pd.to_datetime(df_existing["Date"])
            last_date = df_existing["Date"].max()
            fetch_from = (last_date + pd.Timedelta(days=1)).strftime("%Y-%m-%d")

            if fetch_from >= today:
                print(f"  [{i}/{len(tickers)}] {ticker:6s} — already current")
                continue

            df_new = yf.download(ticker, start=fetch_from, end=today, progress=False, auto_adjust=True)
            if df_new.empty:
                print(f"  [{i}/{len(tickers)}] {ticker:6s} — no new data")
                continue

            if isinstance(df_new.columns, pd.MultiIndex):
                df_new.columns = df_new.columns.get_level_values(0)
            df_new = df_new.reset_index()
            df_new["ticker"] = ticker

            df_combined = (
                pd.concat([df_existing, df_new], ignore_index=True)
                .drop_duplicates(subset="Date")
                .sort_values("Date")
                .reset_index(drop=True)
            )

            push_csv_to_github(
                df             = df_combined,
                repo           = GITHUB_REPO,
                path           = path,
                token          = GITHUB_TOKEN,
                commit_message = f"Update {ticker} +{len(df_new)} rows through {today}",
            )
            print(f"  [{i}/{len(tickers)}] {ticker:6s} — +{len(df_new)} new rows ✓")
            updated += 1
            time.sleep(0.3)

        except Exception as e:
            print(f"  [{i}/{len(tickers)}] {str(ticker):6s} — ERROR: {e}")

    print(f"\n✓ Updated {updated} tickers")

Updating 3851 tickers through 2026-06-28 …

  [1/3851] AAAP   — +1 new rows ✓
  [2/3851] AADR   — +1 new rows ✓
  [3/3851] AAEQ   — +1 new rows ✓
  [4/3851] AAL    — +1 new rows ✓
  [5/3851] AALG   — +1 new rows ✓
  [6/3851] AAOI   — +1 new rows ✓
  [7/3851] AAON   — +1 new rows ✓
  [8/3851] AAPB   — +1 new rows ✓
  [9/3851] AAPD   — +1 new rows ✓
  [10/3851] AAPG   — +1 new rows ✓
  [11/3851] AAPL   — +1 new rows ✓
  [12/3851] AAPU   — +1 new rows ✓
  [13/3851] AAUS   — +1 new rows ✓
  [14/3851] AAVM   — +1 new rows ✓
  [15/3851] AAXJ   — +1 new rows ✓
  [16/3851] ABAT   — +1 new rows ✓
  [17/3851] ABCL   — +1 new rows ✓
  [18/3851] ABCS   — +1 new rows ✓
  [19/3851] ABEO   — +1 new rows ✓
  [20/3851] ABI    — +1 new rows ✓
  [21/3851] ABIG   — +1 new rows ✓
  [22/3851] ABNB   — +1 new rows ✓
  [23/3851] ABOS   — +1 new rows ✓
  [24/3851] ABSI   — +1 new rows ✓
  [25/3851] ABTC   — +1 new rows ✓
  [26/3851] ABTS   — +1 new rows ✓
  [27/3851] ABUS   — +1 new rows ✓
  [28/3851] ABVC   — +1 new rows ✓
  [29/3851] ABVX   — +1 new rows ✓
  [30/3851] ACAD   — +1 new rows ✓
  [31/3851] ACB    — +1 new rows ✓
  [32/3851] ACDC   — +1 new rows ✓
  [33/3851] ACEP   — +1 new rows ✓
  [34/3851] ACET   — +1 new rows ✓
  [35/3851] ACFN   — +1 new rows ✓
  [36/3851] ACGL   — +1 new rows ✓
  [37/3851] ACGLN  — +1 new rows ✓
  [38/3851] ACGLO  — +1 new rows ✓
  [39/3851] ACHC   — +1 new rows ✓
  [40/3851] ACHV   — +1 new rows ✓
  [41/3851] ACIC   — +1 new rows ✓
  [42/3851] ACIW   — +1 new rows ✓
  [43/3851] ACLS   — +1 new rows ✓
  [44/3851] ACMR   — +1 new rows ✓
  [45/3851] ACNB   — +1 new rows ✓
  [46/3851] ACNT   — +1 new rows ✓
  [47/3851] ACON   — +1 new rows ✓
  [48/3851] ACRS   — +1 new rows ✓
  [49/3851] ACRV   — +1 new rows ✓
  [50/3851] ACT    — +1 new rows ✓
  [51/3851] ACTG   — +1 new rows ✓
  [52/3851] ACWI   — +1 new rows ✓
  [53/3851] ACWX   — +1 new rows ✓
  [54/3851] ACXP   — +1 new rows ✓
  [55/3851] ADAG   — +1 new rows ✓
  [56/3851] ADAMG  — +1 new rows ✓
  [57/3851] ADAMH  — +1 new rows ✓
  [58/3851] ADAMI  — +1 new rows ✓
  [59/3851] ADAML  — +1 new rows ✓
  [60/3851] ADAMM  — +1 new rows ✓
  [61/3851] ADAMN  — +1 new rows ✓
  [62/3851] ADAMO  — +1 new rows ✓
  [63/3851] ADBE   — +1 new rows ✓
  [64/3851] ADEA   — +1 new rows ✓
  [65/3851] ADI    — +1 new rows ✓
  [66/3851] ADIL   — +1 new rows ✓
  [67/3851] ADMA   — +1 new rows ✓
  [68/3851] ADP    — +1 new rows ✓
  [69/3851] ADPT   — +1 new rows ✓
  [70/3851] ADSK   — +1 new rows ✓
  [71/3851] ADTN   — +1 new rows ✓
  [72/3851] ADUS   — +1 new rows ✓
  [73/3851] ADV    — +1 new rows ✓
  [74/3851] ADVB   — +1 new rows ✓
  [75/3851] ADXN   — +1 new rows ✓
  [76/3851] AEC    — +1 new rows ✓
  [77/3851] AEHL   — +1 new rows ✓
  [78/3851] AEHR   — +1 new rows ✓
  [79/3851] AEI    — +1 new rows ✓
  [80/3851] AEIS   — +1 new rows ✓
  [81/3851] AEMD   — +1 new rows ✓
  [82/3851] AEP    — +1 new rows ✓
  [83/3851] AERT   — +1 new rows ✓
  [84/3851] AEVA   — +1 new rows ✓
  [85/3851] AEYE   — +1 new rows ✓
  [86/3851] AFBI   — +1 new rows ✓
  [87/3851] AFJK   — +1 new rows ✓

$AFJKU: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['AFJKU']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [88/3851] AFJKU  — no new data
  [89/3851] AFOS   — +1 new rows ✓
  [90/3851] AFRM   — +1 new rows ✓
  [91/3851] AFSC   — +1 new rows ✓
  [92/3851] AFYA   — +1 new rows ✓
  [93/3851] AGCC   — +1 new rows ✓
  [94/3851] AGEM   — +1 new rows ✓
  [95/3851] AGEN   — +1 new rows ✓
  [96/3851] AGGA   — +1 new rows ✓
  [97/3851] AGIO   — +1 new rows ✓
  [98/3851] AGIX   — +1 new rows ✓
  [99/3851] AGMH   — +1 new rows ✓
  [100/3851] AGMI   — +1 new rows ✓
  [101/3851] AGNCL  — +1 new rows ✓
  [102/3851] AGNCM  — +1 new rows ✓
  [103/3851] AGNCN  — +1 new rows ✓
  [104/3851] AGNCO  — +1 new rows ✓
  [105/3851] AGNCP  — +1 new rows ✓
  [106/3851] AGNCZ  — +1 new rows ✓
  [107/3851] AGNG   — +1 new rows ✓
  [108/3851] AGNT   — +1 new rows ✓
  [109/3851] AGPU   — +1 new rows ✓
  [110/3851] AGYS   — +1 new rows ✓
  [111/3851] AGZD   — +1 new rows ✓
  [112/3851] AHCO   — +1 new rows ✓
  [113/3851] AHD    — +1 new rows ✓
  [114/3851] AHG    — +1 new rows ✓
  [115/3851] AHMA   — +1 new rows ✓
  [116/3851] AIA    — +1 new rows ✓
  [117/3851] AIDX   — +1 new rows ✓
  [118/3851] AIFA   — +1 new rows ✓
  [119/3851] AIFC   — +1 new rows ✓
  [120/3851] AIFD   — +1 new rows ✓
  [121/3851] AIFF   — +1 new rows ✓
  [122/3851] AIFU   — +1 new rows ✓
  [123/3851] AIHS   — +1 new rows ✓
  [124/3851] AIIO   — +1 new rows ✓
  [125/3851] AIMD   — +1 new rows ✓
  [126/3851] AIMS   — +1 new rows ✓
  [127/3851] AIOS   — +1 new rows ✓
  [128/3851] AIP    — +1 new rows ✓
  [129/3851] AIPI   — +1 new rows ✓
  [130/3851] AIPO   — +1 new rows ✓
  [131/3851] AIQ    — +1 new rows ✓
  [132/3851] AIRE   — +1 new rows ✓
  [133/3851] AIRG   — +1 new rows ✓
  [134/3851] AIRJ   — +1 new rows ✓
  [135/3851] AIRO   — +1 new rows ✓
  [136/3851] AIRR   — +1 new rows ✓
  [137/3851] AIRT   — +1 new rows ✓
  [138/3851] AIX    — +1 new rows ✓
  [139/3851] AIXC   — +1 new rows ✓
  [140/3851] AIXI   — +1 new rows ✓
  [141/3851] AKAM   — +1 new rows ✓
  [142/3851] AKAN   — +1 new rows ✓
  [143/3851] AKBA   — +1 new rows ✓
  [144/3851] AKTS   — +1 new rows ✓
  [145/3851] AKTX   — +1 new rows ✓
  [146/3851] ALAB   — +1 new rows ✓
  [147/3851] ALAR   — +1 new rows ✓
  [148/3851] ALBG   — +1 new rows ✓
  [149/3851] ALBT   — +1 new rows ✓
  [150/3851] ALCO   — +1 new rows ✓
  [151/3851] ALEC   — +1 new rows ✓
  [152/3851] ALGM   — +1 new rows ✓
  [153/3851] ALGN   — +1 new rows ✓
  [154/3851] ALGS   — +1 new rows ✓
  [155/3851] ALGT   — +1 new rows ✓
  [156/3851] ALHC   — +1 new rows ✓
  [157/3851] ALIL   — +1 new rows ✓
  [158/3851] ALKS   — +1 new rows ✓
  [159/3851] ALKT   — +1 new rows ✓
  [160/3851] ALLO   — +1 new rows ✓
  [161/3851] ALLR   — +1 new rows ✓
  [162/3851] ALLT   — +1 new rows ✓
  [163/3851] ALLW   — +1 new rows ✓
  [164/3851] ALM    — +1 new rows ✓
  [165/3851] ALMR   — +1 new rows ✓
  [166/3851] ALMS   — +1 new rows ✓
  [167/3851] ALMU   — +1 new rows ✓
  [168/3851] ALNT   — +1 new rows ✓
  [169/3851] ALNY   — +1 new rows ✓
  [170/3851] ALOT   — +1 new rows ✓
  [171/3851] ALOY   — +1 new rows ✓
  [172/3851] ALP    — +1 new rows ✓
  [173/3851] ALRM   — +1 new rows ✓
  [174/3851] ALRS   — +1 new rows ✓
  [175/3851] ALT    — +1 new rows ✓
  [176/3851] ALTO   — +1 new rows ✓
  [177/3851] ALXO   — +1 new rows ✓
  [178/3851] ALZN   — +1 new rows ✓
  [179/3851] AMA    — +1 new rows ✓
  [180/3851] AMAL   — +1 new rows ✓
  [181/3851] AMAT   — +1 new rows ✓
  [182/3851] AMBA   — +1 new rows ✓
  [183/3851] AMBR   — +1 new rows ✓
  [184/3851] AMCI   — +1 new rows ✓
  [185/3851] AMCX   — +1 new rows ✓
  [186/3851] AMD    — +1 new rows ✓
  [187/3851] AMDD   — +1 new rows ✓
  [188/3851] AMDG   — +1 new rows ✓
  [189/3851] AMDL   — +1 new rows ✓
  [190/3851] AMEI   — +1 new rows ✓
  [191/3851] AMEM   — +1 new rows ✓
  [192/3851] AMGN   — +1 new rows ✓
  [193/3851] AMGR   — +1 new rows ✓
  [194/3851] AMID   — +1 new rows ✓
  [195/3851] AMIX   — +1 new rows ✓
  [196/3851] AMKR   — +1 new rows ✓
  [197/3851] AMLX   — +1 new rows ✓
  [198/3851] AMOD   — +1 new rows ✓
  [199/3851] AMPH   — +1 new rows ✓
  [200/3851] AMPL   — +1 new rows ✓
  [201/3851] AMRN   — +1 new rows ✓
  [202/3851] AMRX   — +1 new rows ✓
  [203/3851] AMSC   — +1 new rows ✓
  [204/3851] AMSF   — +1 new rows ✓
  [205/3851] AMST   — +1 new rows ✓
  [206/3851] AMTX   — +1 new rows ✓
  [207/3851] AMUN   — +1 new rows ✓
  [208/3851] AMUU   — +1 new rows ✓
  [209/3851] AMZD   — +1 new rows ✓
  [210/3851] AMZN   — +1 new rows ✓
  [211/3851] AMZU   — +1 new rows ✓
  [212/3851] AMZZ   — +1 new rows ✓
  [213/3851] ANAB   — +1 new rows ✓
  [214/3851] ANDE   — +1 new rows ✓
  [215/3851] ANEL   — +1 new rows ✓
  [216/3851] ANGH   — +1 new rows ✓
  [217/3851] ANGI   — +1 new rows ✓
  [218/3851] ANGL   — +1 new rows ✓
  [219/3851] ANGO   — +1 new rows ✓
  [220/3851] ANIK   — +1 new rows ✓
  [221/3851] ANIP   — +1 new rows ✓
  [222/3851] ANNX   — +1 new rows ✓
  [223/3851] ANPA   — +1 new rows ✓
  [224/3851] ANTX   — +1 new rows ✓
  [225/3851] ANV    — +1 new rows ✓
  [226/3851] ANY    — +1 new rows ✓
  [227/3851] AOSL   — +1 new rows ✓
  [228/3851] AOTG   — +1 new rows ✓
  [229/3851] AOUT   — +1 new rows ✓
  [230/3851] APA    — +1 new rows ✓
  [231/3851] APC    — +1 new rows ✓
  [232/3851] APEI   — +1 new rows ✓
  [233/3851] APGE   — +1 new rows ✓
  [234/3851] API    — +1 new rows ✓
  [235/3851] APLD   — +1 new rows ✓
  [236/3851] APLM   — +1 new rows ✓
  [237/3851] APM    — +1 new rows ✓
  [238/3851] APOG   — +1 new rows ✓
  [239/3851] APP    — +1 new rows ✓
  [240/3851] APPF   — +1 new rows ✓
  [241/3851] APPN   — +1 new rows ✓
  [242/3851] APPS   — +1 new rows ✓
  [243/3851] APPX   — +1 new rows ✓
  [244/3851] APRE   — +1 new rows ✓
  [245/3851] APVO   — +1 new rows ✓
  [246/3851] AQB    — +1 new rows ✓
  [247/3851] AQLG   — +1 new rows ✓
  [248/3851] AQMS   — +1 new rows ✓
  [249/3851] AQWA   — +1 new rows ✓
  [250/3851] ARBB   — +1 new rows ✓
  [251/3851] ARBK   — +1 new rows ✓
  [252/3851] ARCB   — +1 new rows ✓
  [253/3851] ARCC   — +1 new rows ✓
  [254/3851] ARCT   — +1 new rows ✓
  [255/3851] ARDX   — +1 new rows ✓
  [256/3851] ARGX   — +1 new rows ✓
  [257/3851] ARKR   — +1 new rows ✓
  [258/3851] ARLP   — +1 new rows ✓
  [259/3851] ARM    — +1 new rows ✓
  [260/3851] ARMG   — +1 new rows ✓
  [261/3851] ARMY   — +1 new rows ✓
  [262/3851] AROW   — +1 new rows ✓
  [263/3851] ARQ    — +1 new rows ✓
  [264/3851] ARQQ   — +1 new rows ✓
  [265/3851] ARQT   — +1 new rows ✓
  [266/3851] ARRY   — +1 new rows ✓
  [267/3851] ARTL   — +1 new rows ✓
  [268/3851] ARTNA  — +1 new rows ✓
  [269/3851] ARVN   — +1 new rows ✓
  [270/3851] ARVR   — +1 new rows ✓
  [271/3851] ARWR   — +1 new rows ✓
  [272/3851] ARXS   — +1 new rows ✓
  [273/3851] ASBP   — +1 new rows ✓
  [274/3851] ASCI   — +1 new rows ✓
  [275/3851] ASD    — +1 new rows ✓
  [276/3851] ASEC   — +1 new rows ✓
  [277/3851] ASLE   — +1 new rows ✓
  [278/3851] ASMB   — +1 new rows ✓
  [279/3851] ASMG   — +1 new rows ✓
  [280/3851] ASML   — +1 new rows ✓
  [281/3851] ASMU   — +1 new rows ✓
  [282/3851] ASND   — +1 new rows ✓
  [283/3851] ASO    — +1 new rows ✓

$ASPC: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['ASPC']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [284/3851] ASPC   — no new data

$ASPCU: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['ASPCU']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [285/3851] ASPCU  — no new data
  [286/3851] ASPS   — +1 new rows ✓
  [287/3851] ASST   — +1 new rows ✓
  [288/3851] ASTC   — +1 new rows ✓
  [289/3851] ASTE   — +1 new rows ✓
  [290/3851] ASTH   — +1 new rows ✓
  [291/3851] ASTI   — +1 new rows ✓
  [292/3851] ASTS   — +1 new rows ✓
  [293/3851] ASYS   — +1 new rows ✓
  [294/3851] ATAT   — +1 new rows ✓
  [295/3851] ATC    — +1 new rows ✓
  [296/3851] ATEC   — +1 new rows ✓
  [297/3851] ATER   — +1 new rows ✓
  [298/3851] ATEX   — +1 new rows ✓

$ATGL: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['ATGL']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [299/3851] ATGL   — no new data
  [300/3851] ATHE   — +1 new rows ✓
  [301/3851] ATLC   — +1 new rows ✓
  [302/3851] ATLCL  — +1 new rows ✓
  [303/3851] ATLCP  — +1 new rows ✓
  [304/3851] ATLCZ  — +1 new rows ✓
  [305/3851] ATLN   — +1 new rows ✓
  [306/3851] ATLO   — +1 new rows ✓
  [307/3851] ATLX   — +1 new rows ✓
  [308/3851] ATNI   — +1 new rows ✓
  [309/3851] ATOM   — +1 new rows ✓
  [310/3851] ATOS   — +1 new rows ✓
  [311/3851] ATPC   — +1 new rows ✓
  [312/3851] ATRA   — +1 new rows ✓
  [313/3851] ATRC   — +1 new rows ✓
  [314/3851] ATRO   — +1 new rows ✓
  [315/3851] ATXG   — +1 new rows ✓
  [316/3851] ATYR   — +1 new rows ✓
  [317/3851] AUBN   — +1 new rows ✓
  [318/3851] AUC    — +1 new rows ✓
  [319/3851] AUDC   — +1 new rows ✓
  [320/3851] AUGO   — +1 new rows ✓
  [321/3851] AUID   — +1 new rows ✓
  [322/3851] AUMI   — +1 new rows ✓
  [323/3851] AUPH   — +1 new rows ✓
  [324/3851] AURA   — +1 new rows ✓
  [325/3851] AURE   — +1 new rows ✓
  [326/3851] AUTL   — +1 new rows ✓
  [327/3851] AUUD   — +1 new rows ✓
  [328/3851] AVAV   — +1 new rows ✓
  [329/3851] AVBH   — +1 new rows ✓
  [330/3851] AVBP   — +1 new rows ✓
  [331/3851] AVGB   — +1 new rows ✓
  [332/3851] AVGG   — +1 new rows ✓
  [333/3851] AVGO   — +1 new rows ✓
  [334/3851] AVGU   — +1 new rows ✓
  [335/3851] AVGX   — +1 new rows ✓
  [336/3851] AVIR   — +1 new rows ✓
  [337/3851] AVL    — +1 new rows ✓
  [338/3851] AVLN   — +1 new rows ✓
  [339/3851] AVNW   — +1 new rows ✓
  [340/3851] AVO    — +1 new rows ✓
  [341/3851] AVOS   — +1 new rows ✓
  [342/3851] AVS    — +1 new rows ✓
  [343/3851] AVT    — +1 new rows ✓
  [344/3851] AVTX   — +1 new rows ✓
  [345/3851] AVUQ   — +1 new rows ✓
  [346/3851] AVX    — +1 new rows ✓
  [347/3851] AVXC   — +1 new rows ✓
  [348/3851] AVXL   — +1 new rows ✓
  [349/3851] AVXX   — +1 new rows ✓
  [350/3851] AXG    — +1 new rows ✓
  [351/3851] AXGN   — +1 new rows ✓
  [352/3851] AXON   — +1 new rows ✓
  [353/3851] AXSM   — +1 new rows ✓
  [354/3851] AXTI   — +1 new rows ✓
  [355/3851] AYA    — +1 new rows ✓
  [356/3851] AYTU   — +1 new rows ✓
  [357/3851] AZ     — +1 new rows ✓
  [358/3851] AZI    — +1 new rows ✓
  [359/3851] AZTA   — +1 new rows ✓
  [360/3851] BABU   — +1 new rows ✓
  [361/3851] BABX   — +1 new rows ✓
  [362/3851] BAER   — +1 new rows ✓
  [363/3851] BAFE   — +1 new rows ✓
  [364/3851] BAFN   — +1 new rows ✓
  [365/3851] BAIG   — +1 new rows ✓
  [366/3851] BAIV   — +1 new rows ✓
  [367/3851] BALQ   — +1 new rows ✓
  [368/3851] BAND   — +1 new rows ✓
  [369/3851] BANF   — +1 new rows ✓
  [370/3851] BANFP  — +1 new rows ✓
  [371/3851] BANR   — +1 new rows ✓
  [372/3851] BANX   — +1 new rows ✓
  [373/3851] BAOS   — +1 new rows ✓
  [374/3851] BASG   — +1 new rows ✓
  [375/3851] BASV   — +1 new rows ✓
  [376/3851] BATRA  — +1 new rows ✓
  [377/3851] BATRK  — +1 new rows ✓

$BAYAU: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['BAYAU']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [378/3851] BAYAU  — no new data
  [379/3851] BBB    — +1 new rows ✓
  [380/3851] BBGI   — +1 new rows ✓
  [381/3851] BBH    — +1 new rows ✓
  [382/3851] BBIO   — +1 new rows ✓
  [383/3851] BBLG   — +1 new rows ✓

$BBLGW: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['BBLGW']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [384/3851] BBLGW  — no new data
  [385/3851] BBNX   — +1 new rows ✓
  [386/3851] BBSI   — +1 new rows ✓
  [387/3851] BCAB   — +1 new rows ✓
  [388/3851] BCAL   — +1 new rows ✓
  [389/3851] BCAX   — +1 new rows ✓
  [390/3851] BCDA   — +1 new rows ✓
  [391/3851] BCFN   — +1 new rows ✓
  [392/3851] BCLO   — +1 new rows ✓
  [393/3851] BCML   — +1 new rows ✓
  [394/3851] BCPC   — +1 new rows ✓
  [395/3851] BCTK   — +1 new rows ✓
  [396/3851] BCTX   — +1 new rows ✓
  [397/3851] BCYC   — +1 new rows ✓
  [398/3851] BDGS   — +1 new rows ✓
  [399/3851] BDRX   — +1 new rows ✓
  [400/3851] BDSX   — +1 new rows ✓
  [401/3851] BDTX   — +1 new rows ✓
  [402/3851] BDVL   — +1 new rows ✓
  [403/3851] BDYN   — +1 new rows ✓
  [404/3851] BEAM   — +1 new rows ✓
  [405/3851] BEDY   — +1 new rows ✓
  [406/3851] BEEM   — +1 new rows ✓
  [407/3851] BEEX   — +1 new rows ✓
  [408/3851] BEEZ   — +1 new rows ✓
  [409/3851] BEG    — +1 new rows ✓
  [410/3851] BELFA  — +1 new rows ✓
  [411/3851] BELFB  — +1 new rows ✓
  [412/3851] BELT   — +1 new rows ✓
  [413/3851] BENF   — +1 new rows ✓
  [414/3851] BESO   — +1 new rows ✓
  [415/3851] BETR   — +1 new rows ✓
  [416/3851] BFC    — +1 new rows ✓
  [417/3851] BFLX   — +1 new rows ✓
  [418/3851] BFRI   — +1 new rows ✓
  [419/3851] BFST   — +1 new rows ✓
  [420/3851] BGCG   — +1 new rows ✓
  [421/3851] BGDE   — +1 new rows ✓
  [422/3851] BGEG   — +1 new rows ✓
  [423/3851] BGGG   — +1 new rows ✓
  [424/3851] BGIA   — +1 new rows ✓
  [425/3851] BGL    — +1 new rows ✓
  [426/3851] BGLC   — +1 new rows ✓
  [427/3851] BGM    — +1 new rows ✓
  [428/3851] BGMS   — +1 new rows ✓
  [429/3851] BGRN   — +1 new rows ✓
  [430/3851] BGRO   — +1 new rows ✓
  [431/3851] BHDG   — +1 new rows ✓
  [432/3851] BHF    — +1 new rows ✓
  [433/3851] BHFAL  — +1 new rows ✓
  [434/3851] BHFAO  — +1 new rows ✓
  [435/3851] BHFAP  — +1 new rows ✓
  [436/3851] BHRB   — +1 new rows ✓
  [437/3851] BIAF   — +1 new rows ✓
  [438/3851] BIB    — +1 new rows ✓
  [439/3851] BIDG   — +1 new rows ✓
  [440/3851] BIDU   — +1 new rows ✓
  [441/3851] BIIB   — +1 new rows ✓
  [442/3851] BILI   — +1 new rows ✓
  [443/3851] BIOA   — +1 new rows ✓
  [444/3851] BIOY   — +1 new rows ✓
  [445/3851] BIRD   — +1 new rows ✓
  [446/3851] BIS    — +1 new rows ✓
  [447/3851] BITA   — +1 new rows ✓
  [448/3851] BITS   — +1 new rows ✓
  [449/3851] BIVI   — +1 new rows ✓
  [450/3851] BIYA   — +1 new rows ✓
  [451/3851] BJDX   — +1 new rows ✓
  [452/3851] BJRI   — +1 new rows ✓
  [453/3851] BKCH   — +1 new rows ✓
  [454/3851] BKMI   — +1 new rows ✓
  [455/3851] BKMS   — +1 new rows ✓
  [456/3851] BKNG   — +1 new rows ✓
  [457/3851] BKR    — +1 new rows ✓
  [458/3851] BL     — +1 new rows ✓
  [459/3851] BLBD   — +1 new rows ✓
  [460/3851] BLCN   — +1 new rows ✓
  [461/3851] BLCR   — +1 new rows ✓
  [462/3851] BLDP   — +1 new rows ✓
  [463/3851] BLFS   — +1 new rows ✓
  [464/3851] BLIN   — +1 new rows ✓
  [465/3851] BLKB   — +1 new rows ✓
  [466/3851] BLLN   — +1 new rows ✓
  [467/3851] BLMN   — +1 new rows ✓
  [468/3851] BLNE   — +1 new rows ✓
  [469/3851] BLNK   — +1 new rows ✓
  [470/3851] BLRX   — +1 new rows ✓
  [471/3851] BLTE   — +1 new rows ✓
  [472/3851] BLZE   — +1 new rows ✓
  [473/3851] BMBL   — +1 new rows ✓
  [474/3851] BMEA   — +1 new rows ✓
  [475/3851] BMNG   — +1 new rows ✓
  [476/3851] BMOP   — +1 new rows ✓
  [477/3851] BMRA   — +1 new rows ✓
  [478/3851] BMRC   — +1 new rows ✓
  [479/3851] BMRN   — +1 new rows ✓
  [480/3851] BNAI   — +1 new rows ✓
  [481/3851] BNBX   — +1 new rows ✓
  [482/3851] BNC    — +1 new rows ✓
  [483/3851] BND    — +1 new rows ✓
  [484/3851] BNDP   — +1 new rows ✓
  [485/3851] BNDW   — +1 new rows ✓
  [486/3851] BNDX   — +1 new rows ✓
  [487/3851] BNGO   — +1 new rows ✓
  [488/3851] BNKK   — +1 new rows ✓
  [489/3851] BNR    — +1 new rows ✓
  [490/3851] BNRG   — +1 new rows ✓
  [491/3851] BNTC   — +1 new rows ✓
  [492/3851] BNTX   — +1 new rows ✓
  [493/3851] BNZI   — +1 new rows ✓
  [494/3851] BODI   — +1 new rows ✓
  [495/3851] BOEG   — +1 new rows ✓
  [496/3851] BOEU   — +1 new rows ✓
  [497/3851] BOKF   — +1 new rows ✓
  [498/3851] BOLT   — +1 new rows ✓
  [499/3851] BON    — +1 new rows ✓
  [500/3851] BOOM   — +1 new rows ✓
  [501/3851] BOT    — +1 new rows ✓
  [502/3851] BOTJ   — +1 new rows ✓
  [503/3851] BOTT   — +1 new rows ✓
  [504/3851] BOTZ   — +1 new rows ✓
  [505/3851] BOXL   — +1 new rows ✓
  [506/3851] BPOP   — +1 new rows ✓
  [507/3851] BPOPM  — +1 new rows ✓
  [508/3851] BPRN   — +1 new rows ✓
  [509/3851] BRAG   — +1 new rows ✓
  [510/3851] BRBI   — +1 new rows ✓
  [511/3851] BRCB   — +1 new rows ✓
  [512/3851] BREM   — +1 new rows ✓
  [513/3851] BRES   — +1 new rows ✓
  [514/3851] BRHY   — +1 new rows ✓
  [515/3851] BRID   — +1 new rows ✓
  [516/3851] BRKR   — +1 new rows ✓
  [517/3851] BRKRP  — +1 new rows ✓
  [518/3851] BRKU   — +1 new rows ✓
  [519/3851] BRNY   — +1 new rows ✓
  [520/3851] BRRR   — +1 new rows ✓
  [521/3851] BRTR   — +1 new rows ✓
  [522/3851] BRTX   — +1 new rows ✓
  [523/3851] BRUN   — +1 new rows ✓
  [524/3851] BRUNW  — +1 new rows ✓
  [525/3851] BRZE   — +1 new rows ✓
  [526/3851] BSCA   — +1 new rows ✓
  [527/3851] BSCS   — +1 new rows ✓
  [528/3851] BSCW   — +1 new rows ✓
  [529/3851] BSCX   — +1 new rows ✓
  [530/3851] BSCY   — +1 new rows ✓
  [531/3851] BSCZ   — +1 new rows ✓
  [532/3851] BSET   — +1 new rows ✓
  [533/3851] BSGR   — +1 new rows ✓
  [534/3851] BSGT   — +1 new rows ✓
  [535/3851] BSIN   — +1 new rows ✓
  [536/3851] BSJQ   — +1 new rows ✓
  [537/3851] BSJR   — +1 new rows ✓
  [538/3851] BSJS   — +1 new rows ✓
  [539/3851] BSJT   — +1 new rows ✓
  [540/3851] BSJU   — +1 new rows ✓
  [541/3851] BSJV   — +1 new rows ✓
  [542/3851] BSJW   — +1 new rows ✓
  [543/3851] BSJX   — +1 new rows ✓
  [544/3851] BSJY   — +1 new rows ✓
  [545/3851] BSMQ   — +1 new rows ✓
  [546/3851] BSMR   — +1 new rows ✓
  [547/3851] BSMS   — +1 new rows ✓
  [548/3851] BSMT   — +1 new rows ✓
  [549/3851] BSMU   — +1 new rows ✓
  [550/3851] BSMV   — +1 new rows ✓
  [551/3851] BSMW   — +1 new rows ✓
  [552/3851] BSMY   — +1 new rows ✓
  [553/3851] BSMZ   — +1 new rows ✓
  [554/3851] BSRR   — +1 new rows ✓
  [555/3851] BSSX   — +1 new rows ✓
  [556/3851] BSTS   — +1 new rows ✓
  [557/3851] BSTU   — +1 new rows ✓
  [558/3851] BSTV   — +1 new rows ✓
  [559/3851] BSVN   — +1 new rows ✓
  [560/3851] BSVO   — +1 new rows ✓
  [561/3851] BSY    — +1 new rows ✓
  [562/3851] BTAI   — +1 new rows ✓
  [563/3851] BTBT   — +1 new rows ✓
  [564/3851] BTCS   — +1 new rows ✓
  [565/3851] BTCT   — +1 new rows ✓
  [566/3851] BTDR   — +1 new rows ✓
  [567/3851] BTF    — +1 new rows ✓
  [568/3851] BTGD   — +1 new rows ✓
  [569/3851] BTOG   — +1 new rows ✓
  [570/3851] BTSG   — +1 new rows ✓
  [571/3851] BTSGU  — +1 new rows ✓
  [572/3851] BTTC   — +1 new rows ✓
  [573/3851] BUFC   — +1 new rows ✓
  [574/3851] BUFI   — +1 new rows ✓
  [575/3851] BUFM   — +1 new rows ✓
  [576/3851] BUG    — +1 new rows ✓
  [577/3851] BULD   — +1 new rows ✓
  [578/3851] BULG   — +1 new rows ✓
  [579/3851] BULL   — +1 new rows ✓
  [580/3851] BUSE   — +1 new rows ✓
  [581/3851] BUSEP  — +1 new rows ✓
  [582/3851] BUUU   — +1 new rows ✓
  [583/3851] BVFL   — +1 new rows ✓
  [584/3851] BWB    — +1 new rows ✓
  [585/3851] BWBBP  — +1 new rows ✓
  [586/3851] BWEN   — +1 new rows ✓
  [587/3851] BWFG   — +1 new rows ✓
  [588/3851] BWIN   — +1 new rows ✓
  [589/3851] BWMN   — +1 new rows ✓
  [590/3851] BYAH   — +1 new rows ✓
  [591/3851] BYFC   — +1 new rows ✓
  [592/3851] BYND   — +1 new rows ✓
  [593/3851] BYRN   — +1 new rows ✓
  [594/3851] BYSI   — +1 new rows ✓
  [595/3851] BZ     — +1 new rows ✓
  [596/3851] BZFD   — +1 new rows ✓
  [597/3851] BZUN   — +1 new rows ✓
  [598/3851] CAAS   — +1 new rows ✓
  [599/3851] CABA   — +1 new rows ✓
  [600/3851] CAC    — +1 new rows ✓
  [601/3851] CACC   — +1 new rows ✓
  [602/3851] CAFG   — +1 new rows ✓
  [603/3851] CAI    — +1 new rows ✓
  [604/3851] CAIQ   — +1 new rows ✓
  [605/3851] CAKE   — +1 new rows ✓
  [606/3851] CALI   — +1 new rows ✓
  [607/3851] CALM   — +1 new rows ✓
  [608/3851] CAMT   — +1 new rows ✓
  [609/3851] CAN    — +1 new rows ✓
  [610/3851] CANC   — +1 new rows ✓
  [611/3851] CANQ   — +1 new rows ✓
  [612/3851] CAPNR  — +1 new rows ✓
  [613/3851] CAPR   — +1 new rows ✓
  [614/3851] CAPS   — +1 new rows ✓
  [615/3851] CAR    — +1 new rows ✓
  [616/3851] CARE   — +1 new rows ✓
  [617/3851] CARG   — +1 new rows ✓
  [618/3851] CART   — +1 new rows ✓
  [619/3851] CARY   — +1 new rows ✓
  [620/3851] CARZ   — +1 new rows ✓
  [621/3851] CASH   — +1 new rows ✓
  [622/3851] CASS   — +1 new rows ✓
  [623/3851] CASY   — +1 new rows ✓
  [624/3851] CATH   — +1 new rows ✓
  [625/3851] CATY   — +1 new rows ✓
  [626/3851] CBC    — +1 new rows ✓
  [627/3851] CBFV   — +1 new rows ✓
  [628/3851] CBIO   — +1 new rows ✓
  [629/3851] CBK    — +1 new rows ✓
  [630/3851] CBLL   — +1 new rows ✓
  [631/3851] CBNK   — +1 new rows ✓
  [632/3851] CBRL   — +1 new rows ✓
  [633/3851] CBRS   — +1 new rows ✓
  [634/3851] CBSH   — +1 new rows ✓
  [635/3851] CBUS   — +1 new rows ✓
  [636/3851] CCB    — +1 new rows ✓
  [637/3851] CCBG   — +1 new rows ✓
  [638/3851] CCCC   — +1 new rows ✓
  [639/3851] CCD    — +1 new rows ✓
  [640/3851] CCEC   — +1 new rows ✓
  [641/3851] CCEP   — +1 new rows ✓
  [642/3851] CCFE   — +1 new rows ✓
  [643/3851] CCG    — +1 new rows ✓
  [644/3851] CCNE   — +1 new rows ✓

$CCNEP: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['CCNEP']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [645/3851] CCNEP  — no new data
  [646/3851] CCNR   — +1 new rows ✓
  [647/3851] CCOI   — +1 new rows ✓
  [648/3851] CCRN   — +1 new rows ✓
  [649/3851] CCSB   — +1 new rows ✓
  [650/3851] CCSI   — +1 new rows ✓
  [651/3851] CCSO   — +1 new rows ✓
  [652/3851] CCTG   — +1 new rows ✓
  [653/3851] CD     — +1 new rows ✓
  [654/3851] CDC    — +1 new rows ✓
  [655/3851] CDIG   — +1 new rows ✓
  [656/3851] CDIO   — +1 new rows ✓
  [657/3851] CDL    — +1 new rows ✓
  [658/3851] CDLX   — +1 new rows ✓
  [659/3851] CDNA   — +1 new rows ✓
  [660/3851] CDNL   — +1 new rows ✓
  [661/3851] CDNS   — +1 new rows ✓
  [662/3851] CDT    — +1 new rows ✓
  [663/3851] CDTG   — +1 new rows ✓
  [664/3851] CDW    — +1 new rows ✓
  [665/3851] CDXS   — +1 new rows ✓
  [666/3851] CDZIP  — +1 new rows ✓
  [667/3851] CECO   — +1 new rows ✓
  [668/3851] CEFA   — +1 new rows ✓
  [669/3851] CEG    — +1 new rows ✓
  [670/3851] CELC   — +1 new rows ✓
  [671/3851] CELH   — +1 new rows ✓
  [672/3851] CELU   — +1 new rows ✓
  [673/3851] CELZ   — +1 new rows ✓
  [674/3851] CENN   — +1 new rows ✓
  [675/3851] CENT   — +1 new rows ✓
  [676/3851] CENTA  — +1 new rows ✓
  [677/3851] CENX   — +1 new rows ✓
  [678/3851] CEPI   — +1 new rows ✓
  [679/3851] CERT   — +1 new rows ✓
  [680/3851] CETX   — +1 new rows ✓
  [681/3851] CETY   — +1 new rows ✓
  [682/3851] CEVA   — +1 new rows ✓
  [683/3851] CFA    — +1 new rows ✓
  [684/3851] CFBK   — +1 new rows ✓
  [685/3851] CFFI   — +1 new rows ✓
  [686/3851] CFO    — +1 new rows ✓
  [687/3851] CG     — +1 new rows ✓
  [688/3851] CGC    — +1 new rows ✓
  [689/3851] CGEM   — +1 new rows ✓
  [690/3851] CGNT   — +1 new rows ✓
  [691/3851] CGNX   — +1 new rows ✓
  [692/3851] CGON   — +1 new rows ✓
  [693/3851] CHA    — +1 new rows ✓
  [694/3851] CHAI   — +1 new rows ✓
  [695/3851] CHCI   — +1 new rows ✓
  [696/3851] CHCO   — +1 new rows ✓
  [697/3851] CHDN   — +1 new rows ✓
  [698/3851] CHEF   — +1 new rows ✓
  [699/3851] CHGX   — +1 new rows ✓
  [700/3851] CHKP   — +1 new rows ✓
  [701/3851] CHMG   — +1 new rows ✓
  [702/3851] CHNR   — +1 new rows ✓
  [703/3851] CHPS   — +1 new rows ✓
  [704/3851] CHPX   — +1 new rows ✓
  [705/3851] CHR    — +1 new rows ✓
  [706/3851] CHRD   — +1 new rows ✓
  [707/3851] CHRI   — +1 new rows ✓
  [708/3851] CHRN   — +1 new rows ✓
  [709/3851] CHRS   — +1 new rows ✓
  [710/3851] CHRW   — +1 new rows ✓
  [711/3851] CHSCL  — +1 new rows ✓
  [712/3851] CHSCM  — +1 new rows ✓
  [713/3851] CHSCN  — +1 new rows ✓
  [714/3851] CHSCO  — +1 new rows ✓
  [715/3851] CHSCP  — +1 new rows ✓
  [716/3851] CHSN   — +1 new rows ✓
  [717/3851] CHTR   — +1 new rows ✓
  [718/3851] CHYM   — +1 new rows ✓
  [719/3851] CIBR   — +1 new rows ✓
  [720/3851] CIFR   — +1 new rows ✓
  [721/3851] CIGI   — +1 new rows ✓
  [722/3851] CIIT   — +1 new rows ✓
  [723/3851] CINF   — +1 new rows ✓
  [724/3851] CING   — +1 new rows ✓
  [725/3851] CISO   — +1 new rows ✓
  [726/3851] CISS   — +1 new rows ✓
  [727/3851] CIVB   — +1 new rows ✓
  [728/3851] CLAR   — +1 new rows ✓
  [729/3851] CLBK   — +1 new rows ✓
  [730/3851] CLBT   — +1 new rows ✓
  [731/3851] CLDX   — +1 new rows ✓
  [732/3851] CLFD   — +1 new rows ✓
  [733/3851] CLGN   — +1 new rows ✓
  [734/3851] CLIK   — +1 new rows ✓
  [735/3851] CLIR   — +1 new rows ✓
  [736/3851] CLLS   — +1 new rows ✓
  [737/3851] CLMB   — +1 new rows ✓
  [738/3851] CLMT   — +1 new rows ✓
  [739/3851] CLNE   — +1 new rows ✓
  [740/3851] CLNN   — +1 new rows ✓
  [741/3851] CLOA   — +1 new rows ✓
  [742/3851] CLOD   — +1 new rows ✓
  [743/3851] CLOU   — +1 new rows ✓
  [744/3851] CLOV   — +1 new rows ✓
  [745/3851] CLPT   — +1 new rows ✓
  [746/3851] CLRB   — +1 new rows ✓
  [747/3851] CLRO   — +1 new rows ✓
  [748/3851] CLSK   — +1 new rows ✓
  [749/3851] CLSM   — +1 new rows ✓
  [750/3851] CLYM   — +1 new rows ✓
  [751/3851] CMBO   — +1 new rows ✓
  [752/3851] CMCO   — +1 new rows ✓
  [753/3851] CMCSA  — +1 new rows ✓
  [754/3851] CMCT   — +1 new rows ✓
  [755/3851] CME    — +1 new rows ✓
  [756/3851] CMGG   — +1 new rows ✓
  [757/3851] CMMB   — +1 new rows ✓
  [758/3851] CMND   — +1 new rows ✓
  [759/3851] CMPR   — +1 new rows ✓
  [760/3851] CMPS   — +1 new rows ✓
  [761/3851] CMRC   — +1 new rows ✓
  [762/3851] CMTL   — +1 new rows ✓
  [763/3851] CMTV   — +1 new rows ✓
  [764/3851] CNCG   — +1 new rows ✓
  [765/3851] CNDT   — +1 new rows ✓
  [766/3851] CNET   — +1 new rows ✓
  [767/3851] CNEY   — +1 new rows ✓
  [768/3851] CNOB   — +1 new rows ✓
  [769/3851] CNOBP  — +1 new rows ✓
  [770/3851] CNQQ   — +1 new rows ✓
  [771/3851] CNSP   — +1 new rows ✓
  [772/3851] CNTB   — +1 new rows ✓
  [773/3851] CNTN   — +1 new rows ✓
  [774/3851] CNVS   — +1 new rows ✓
  [775/3851] CNXC   — +1 new rows ✓
  [776/3851] CNXN   — +1 new rows ✓
  [777/3851] COAG   — +1 new rows ✓
  [778/3851] COCO   — +1 new rows ✓
  [779/3851] COCP   — +1 new rows ✓
  [780/3851] CODX   — +1 new rows ✓
  [781/3851] COFS   — +1 new rows ✓
  [782/3851] COGT   — +1 new rows ✓
  [783/3851] COHU   — +1 new rows ✓
  [784/3851] COIG   — +1 new rows ✓
  [785/3851] COIN   — +1 new rows ✓
  [786/3851] COKE   — +1 new rows ✓
  [787/3851] COLB   — +1 new rows ✓
  [788/3851] COLL   — +1 new rows ✓
  [789/3851] COLM   — +1 new rows ✓
  [790/3851] COMT   — +1 new rows ✓
  [791/3851] CONI   — +1 new rows ✓
  [792/3851] CONL   — +1 new rows ✓
  [793/3851] CONX   — +1 new rows ✓
  [794/3851] COO    — +1 new rows ✓
  [795/3851] COPJ   — +1 new rows ✓
  [796/3851] COPP   — +1 new rows ✓
  [797/3851] CORO   — +1 new rows ✓
  [798/3851] CORT   — +1 new rows ✓
  [799/3851] CORZ   — +1 new rows ✓
  [800/3851] COSM   — +1 new rows ✓
  [801/3851] COST   — +1 new rows ✓
  [802/3851] COWG   — +1 new rows ✓
  [803/3851] COWS   — +1 new rows ✓
  [804/3851] COYY   — +1 new rows ✓
  [805/3851] CPAG   — +1 new rows ✓
  [806/3851] CPB    — +1 new rows ✓
  [807/3851] CPHC   — +1 new rows ✓
  [808/3851] CPHY   — +1 new rows ✓
  [809/3851] CPLS   — +1 new rows ✓
  [810/3851] CPOP   — +1 new rows ✓
  [811/3851] CPRT   — +1 new rows ✓
  [812/3851] CPRX   — +1 new rows ✓
  [813/3851] CPSH   — +1 new rows ✓
  [814/3851] CRAI   — +1 new rows ✓
  [815/3851] CRBP   — +1 new rows ✓
  [816/3851] CRBU   — +1 new rows ✓
  [817/3851] CRCG   — +1 new rows ✓
  [818/3851] CRCT   — +1 new rows ✓
  [819/3851] CRDF   — +1 new rows ✓
  [820/3851] CRDO   — +1 new rows ✓
  [821/3851] CRE    — +1 new rows ✓
  [822/3851] CREG   — +1 new rows ✓
  [823/3851] CREX   — +1 new rows ✓
  [824/3851] CRIS   — +1 new rows ✓
  [825/3851] CRMD   — +1 new rows ✓
  [826/3851] CRML   — +1 new rows ✓
  [827/3851] CRMT   — +1 new rows ✓
  [828/3851] CRNC   — +1 new rows ✓
  [829/3851] CRNX   — +1 new rows ✓
  [830/3851] CRON   — +1 new rows ✓
  [831/3851] CROX   — +1 new rows ✓
  [832/3851] CRSP   — +1 new rows ✓
  [833/3851] CRSR   — +1 new rows ✓
  [834/3851] CRTO   — +1 new rows ✓
  [835/3851] CRUS   — +1 new rows ✓
  [836/3851] CRVL   — +1 new rows ✓
  [837/3851] CRVO   — +1 new rows ✓
  [838/3851] CRVS   — +1 new rows ✓
  [839/3851] CRWD   — +1 new rows ✓
  [840/3851] CRWG   — +1 new rows ✓
  [841/3851] CRWL   — +1 new rows ✓
  [842/3851] CRWV   — +1 new rows ✓
  [843/3851] CRY    — +1 new rows ✓
  [844/3851] CSAI   — +1 new rows ✓
  [845/3851] CSB    — +1 new rows ✓
  [846/3851] CSBR   — +1 new rows ✓
  [847/3851] CSCL   — +1 new rows ✓
  [848/3851] CSCO   — +1 new rows ✓
  [849/3851] CSCS   — +1 new rows ✓
  [850/3851] CSEN   — +1 new rows ✓
  [851/3851] CSGP   — +1 new rows ✓
  [852/3851] CSIQ   — +1 new rows ✓
  [853/3851] CSPI   — +1 new rows ✓
  [854/3851] CSQ    — +1 new rows ✓
  [855/3851] CSTE   — +1 new rows ✓
  [856/3851] CSTL   — +1 new rows ✓
  [857/3851] CSWC   — +1 new rows ✓
  [858/3851] CSX    — +1 new rows ✓
  [859/3851] CTAS   — +1 new rows ✓
  [860/3851] CTBI   — +1 new rows ✓
  [861/3851] CTEC   — +1 new rows ✓
  [862/3851] CTKB   — +1 new rows ✓
  [863/3851] CTMX   — +1 new rows ✓
  [864/3851] CTNM   — +1 new rows ✓
  [865/3851] CTNT   — +1 new rows ✓
  [866/3851] CTOR   — +1 new rows ✓
  [867/3851] CTRM   — +1 new rows ✓
  [868/3851] CTRN   — +1 new rows ✓
  [869/3851] CTSH   — +1 new rows ✓
  [870/3851] CTXR   — +1 new rows ✓
  [871/3851] CUE    — +1 new rows ✓
  [872/3851] CULP   — +1 new rows ✓
  [873/3851] CUPR   — +1 new rows ✓
  [874/3851] CVBF   — +1 new rows ✓
  [875/3851] CVCO   — +1 new rows ✓
  [876/3851] CVKD   — +1 new rows ✓
  [877/3851] CVLT   — +1 new rows ✓
  [878/3851] CVRX   — +1 new rows ✓
  [879/3851] CWBC   — +1 new rows ✓
  [880/3851] CWCO   — +1 new rows ✓
  [881/3851] CWD    — +1 new rows ✓
  [882/3851] CWST   — +1 new rows ✓
  [883/3851] CWY    — +1 new rows ✓
  [884/3851] CXSE   — +1 new rows ✓
  [885/3851] CYCN   — +1 new rows ✓
  [886/3851] CYCU   — +1 new rows ✓
  [887/3851] CYN    — +1 new rows ✓
  [888/3851] CYPH   — +1 new rows ✓
  [889/3851] CYRX   — +1 new rows ✓
  [890/3851] CYTK   — +1 new rows ✓
  [891/3851] CZAR   — +1 new rows ✓
  [892/3851] CZFS   — +1 new rows ✓
  [893/3851] CZNC   — +1 new rows ✓
  [894/3851] CZR    — +1 new rows ✓
  [895/3851] CZWI   — +1 new rows ✓
  [896/3851] DADS   — +1 new rows ✓
  [897/3851] DAIC   — +1 new rows ✓
  [898/3851] DAK    — +1 new rows ✓
  [899/3851] DAKT   — +1 new rows ✓
  [900/3851] DAPP   — +1 new rows ✓
  [901/3851] DARE   — +1 new rows ✓
  [902/3851] DASH   — +1 new rows ✓
  [903/3851] DAVE   — +1 new rows ✓
  [904/3851] DAX    — +1 new rows ✓
  [905/3851] DBGI   — +1 new rows ✓
  [906/3851] DBVT   — +1 new rows ✓
  [907/3851] DBX    — +1 new rows ✓
  [908/3851] DCBO   — +1 new rows ✓
  [909/3851] DCOY   — +1 new rows ✓
  [910/3851] DCTH   — +1 new rows ✓
  [911/3851] DCX    — +1 new rows ✓
  [912/3851] DDIV   — +1 new rows ✓
  [913/3851] DDOG   — +1 new rows ✓
  [914/3851] DECO   — +1 new rows ✓
  [915/3851] DEMZ   — +1 new rows ✓
  [916/3851] DFDV   — +1 new rows ✓
  [917/3851] DFGP   — +1 new rows ✓
  [918/3851] DFGX   — +1 new rows ✓
  [919/3851] DFLI   — +1 new rows ✓
  [920/3851] DFNS   — +1 new rows ✓
  [921/3851] DFSC   — +1 new rows ✓
  [922/3851] DFTX   — +1 new rows ✓
  [923/3851] DGCB   — +1 new rows ✓
  [924/3851] DGICA  — +1 new rows ✓
  [925/3851] DGICB  — +1 new rows ✓
  [926/3851] DGII   — +1 new rows ✓
  [927/3851] DGLO   — +1 new rows ✓
  [928/3851] DGNX   — +1 new rows ✓
  [929/3851] DGRE   — +1 new rows ✓
  [930/3851] DGRS   — +1 new rows ✓
  [931/3851] DGRW   — +1 new rows ✓
  [932/3851] DH     — +1 new rows ✓
  [933/3851] DIBS   — +1 new rows ✓
  [934/3851] DIME   — +1 new rows ✓
  [935/3851] DINE   — +1 new rows ✓
  [936/3851] DIOD   — +1 new rows ✓
  [937/3851] DIVD   — +1 new rows ✓
  [938/3851] DJCO   — +1 new rows ✓
  [939/3851] DJT    — +1 new rows ✓
  [940/3851] DJTWW  — +1 new rows ✓
  [941/3851] DKNG   — +1 new rows ✓
  [942/3851] DKNX   — +1 new rows ✓
  [943/3851] DLHC   — +1 new rows ✓
  [944/3851] DLLL   — +1 new rows ✓
  [945/3851] DLO    — +1 new rows ✓
  [946/3851] DLPN   — +1 new rows ✓
  [947/3851] DLTH   — +1 new rows ✓
  [948/3851] DLTR   — +1 new rows ✓
  [949/3851] DMAC   — +1 new rows ✓
  [950/3851] DMLP   — +1 new rows ✓
  [951/3851] DMRA   — +1 new rows ✓
  [952/3851] DMRC   — +1 new rows ✓
  [953/3851] DMXF   — +1 new rows ✓
  [954/3851] DNLI   — +1 new rows ✓
  [955/3851] DNTH   — +1 new rows ✓
  [956/3851] DNUT   — +1 new rows ✓
  [957/3851] DOCU   — +1 new rows ✓
  [958/3851] DOGZ   — +1 new rows ✓
  [959/3851] DOMH   — +1 new rows ✓
  [960/3851] DOMO   — +1 new rows ✓
  [961/3851] DOO    — +1 new rows ✓
  [962/3851] DORM   — +1 new rows ✓
  [963/3851] DOX    — +1 new rows ✓
  [964/3851] DOYU   — +1 new rows ✓
  [965/3851] DPRO   — +1 new rows ✓
  [966/3851] DPZ    — +1 new rows ✓
  [967/3851] DRCT   — +1 new rows ✓
  [968/3851] DRIO   — +1 new rows ✓
  [969/3851] DRIV   — +1 new rows ✓
  [970/3851] DRMA   — +1 new rows ✓
  [971/3851] DRNZ   — +1 new rows ✓
  [972/3851] DRS    — +1 new rows ✓
  [973/3851] DRUG   — +1 new rows ✓
  [974/3851] DRVN   — +1 new rows ✓
  [975/3851] DSGN   — +1 new rows ✓
  [976/3851] DSGR   — +1 new rows ✓
  [977/3851] DSGX   — +1 new rows ✓
  [978/3851] DSP    — +1 new rows ✓
  [979/3851] DSY    — +1 new rows ✓
  [980/3851] DTCR   — +1 new rows ✓
  [981/3851] DTIL   — +1 new rows ✓
  [982/3851] DTSS   — +1 new rows ✓
  [983/3851] DUKH   — +1 new rows ✓
  [984/3851] DUKX   — +1 new rows ✓
  [985/3851] DUO    — +1 new rows ✓
  [986/3851] DUOG   — +1 new rows ✓
  [987/3851] DUOL   — +1 new rows ✓
  [988/3851] DUOT   — +1 new rows ✓
  [989/3851] DUSG   — +1 new rows ✓
  [990/3851] DVGR   — +1 new rows ✓
  [991/3851] DVIN   — +1 new rows ✓
  [992/3851] DVLT   — +1 new rows ✓
  [993/3851] DVLU   — +1 new rows ✓
  [994/3851] DVOL   — +1 new rows ✓
  [995/3851] DVQQ   — +1 new rows ✓
  [996/3851] DVRE   — +1 new rows ✓
  [997/3851] DVSP   — +1 new rows ✓
  [998/3851] DVUT   — +1 new rows ✓
  [999/3851] DVXB   — +1 new rows ✓
  [1000/3851] DVXC   — +1 new rows ✓
  [1001/3851] DVXE   — +1 new rows ✓
  [1002/3851] DVXF   — +1 new rows ✓
  [1003/3851] DVXK   — +1 new rows ✓
  [1004/3851] DVXP   — +1 new rows ✓
  [1005/3851] DVXV   — +1 new rows ✓
  [1006/3851] DVXY   — +1 new rows ✓
  [1007/3851] DVY    — +1 new rows ✓
  [1008/3851] DWAS   — +1 new rows ✓
  [1009/3851] DWAW   — +1 new rows ✓
  [1010/3851] DWSH   — +1 new rows ✓
  [1011/3851] DWSN   — +1 new rows ✓
  [1012/3851] DWTX   — +1 new rows ✓
  [1013/3851] DWUS   — +1 new rows ✓
  [1014/3851] DXCM   — +1 new rows ✓
  [1015/3851] DXPE   — +1 new rows ✓
  [1016/3851] DXR    — +1 new rows ✓
  [1017/3851] DXST   — +1 new rows ✓
  [1018/3851] DYFI   — +1 new rows ✓
  [1019/3851] DYN    — +1 new rows ✓
  [1020/3851] DYNB   — +1 new rows ✓
  [1021/3851] DYTA   — +1 new rows ✓
  [1022/3851] EA     — +1 new rows ✓
  [1023/3851] EART   — +1 new rows ✓
  [1024/3851] EASY   — +1 new rows ✓
  [1025/3851] EBAY   — +1 new rows ✓
  [1026/3851] EBC    — +1 new rows ✓
  [1027/3851] EBI    — +1 new rows ✓
  [1028/3851] EBIZ   — +1 new rows ✓
  [1029/3851] EBMT   — +1 new rows ✓
  [1030/3851] EBON   — +1 new rows ✓
  [1031/3851] ECBK   — +1 new rows ✓
  [1032/3851] ECHO   — +1 new rows ✓
  [1033/3851] ECOR   — +1 new rows ✓
  [1034/3851] ECOW   — +1 new rows ✓
  [1035/3851] ECPG   — +1 new rows ✓
  [1036/3851] EDBL   — +1 new rows ✓
  [1037/3851] EDHL   — +1 new rows ✓
  [1038/3851] EDIT   — +1 new rows ✓
  [1039/3851] EDRY   — +1 new rows ✓
  [1040/3851] EDSA   — +1 new rows ✓
  [1041/3851] EEE    — +1 new rows ✓
  [1042/3851] EEFT   — +1 new rows ✓
  [1043/3851] EEIQ   — +1 new rows ✓
  [1044/3851] EEMA   — +1 new rows ✓
  [1045/3851] EFAS   — +1 new rows ✓
  [1046/3851] EFOI   — +1 new rows ✓
  [1047/3851] EFRA   — +1 new rows ✓
  [1048/3851] EFSC   — +1 new rows ✓

$EFSCP: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['EFSCP']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1049/3851] EFSCP  — no new data
  [1050/3851] EFSI   — +1 new rows ✓
  [1051/3851] EGBN   — +1 new rows ✓
  [1052/3851] EGGQ   — +1 new rows ✓
  [1053/3851] EGHT   — +1 new rows ✓
  [1054/3851] EH     — +1 new rows ✓
  [1055/3851] EHGO   — +1 new rows ✓
  [1056/3851] EHLS   — +1 new rows ✓
  [1057/3851] EHTH   — +1 new rows ✓
  [1058/3851] EJH    — +1 new rows ✓
  [1059/3851] EKG    — +1 new rows ✓
  [1060/3851] ELAB   — +1 new rows ✓
  [1061/3851] ELBM   — +1 new rows ✓
  [1062/3851] ELDN   — +1 new rows ✓
  [1063/3851] ELE    — +1 new rows ✓
  [1064/3851] ELFY   — +1 new rows ✓
  [1065/3851] ELIL   — +1 new rows ✓
  [1066/3851] ELMT   — +1 new rows ✓
  [1067/3851] ELPW   — +1 new rows ✓
  [1068/3851] ELTK   — +1 new rows ✓
  [1069/3851] ELTX   — +1 new rows ✓
  [1070/3851] ELVA   — +1 new rows ✓
  [1071/3851] ELVN   — +1 new rows ✓
  [1072/3851] ELVR   — +1 new rows ✓
  [1073/3851] EMB    — +1 new rows ✓
  [1074/3851] EMBC   — +1 new rows ✓
  [1075/3851] EMCB   — +1 new rows ✓
  [1076/3851] EMEM   — +1 new rows ✓
  [1077/3851] EMEQ   — +1 new rows ✓
  [1078/3851] EMIF   — +1 new rows ✓
  [1079/3851] EML    — +1 new rows ✓
  [1080/3851] EMPD   — +1 new rows ✓
  [1081/3851] EMSC   — +1 new rows ✓
  [1082/3851] EMXC   — +1 new rows ✓
  [1083/3851] EMXF   — +1 new rows ✓
  [1084/3851] ENDW   — +1 new rows ✓
  [1085/3851] ENGN   — +1 new rows ✓
  [1086/3851] ENHI   — +1 new rows ✓
  [1087/3851] ENHU   — +1 new rows ✓
  [1088/3851] ENLT   — +1 new rows ✓
  [1089/3851] ENLV   — +1 new rows ✓
  [1090/3851] ENPH   — +1 new rows ✓
  [1091/3851] ENSC   — +1 new rows ✓
  [1092/3851] ENSG   — +1 new rows ✓
  [1093/3851] ENTA   — +1 new rows ✓
  [1094/3851] ENTG   — +1 new rows ✓
  [1095/3851] ENVB   — +1 new rows ✓
  [1096/3851] ENVX   — +1 new rows ✓
  [1097/3851] ENZL   — +1 new rows ✓
  [1098/3851] EOLS   — +1 new rows ✓
  [1099/3851] EOSE   — +1 new rows ✓
  [1100/3851] EPSM   — +1 new rows ✓
  [1101/3851] EQ     — +1 new rows ✓
  [1102/3851] EQIX   — +1 new rows ✓
  [1103/3851] EQPT   — +1 new rows ✓
  [1104/3851] EQRR   — +1 new rows ✓
  [1105/3851] ERAS   — +1 new rows ✓
  [1106/3851] ERET   — +1 new rows ✓
  [1107/3851] ERIE   — +1 new rows ✓
  [1108/3851] ERII   — +1 new rows ✓
  [1109/3851] ERNA   — +1 new rows ✓
  [1110/3851] ESCA   — +1 new rows ✓
  [1111/3851] ESEA   — +1 new rows ✓
  [1112/3851] ESGD   — +1 new rows ✓
  [1113/3851] ESGE   — +1 new rows ✓
  [1114/3851] ESGU   — +1 new rows ✓
  [1115/3851] ESLA   — +1 new rows ✓
  [1116/3851] ESLT   — +1 new rows ✓
  [1117/3851] ESMV   — +1 new rows ✓
  [1118/3851] ESPO   — +1 new rows ✓
  [1119/3851] ESPR   — +1 new rows ✓
  [1120/3851] ESQ    — +1 new rows ✓
  [1121/3851] ESTA   — +1 new rows ✓
  [1122/3851] ETEC   — +1 new rows ✓
  [1123/3851] ETHA   — +1 new rows ✓
  [1124/3851] ETHB   — +1 new rows ✓
  [1125/3851] ETON   — +1 new rows ✓
  [1126/3851] ETOR   — +1 new rows ✓
  [1127/3851] EUDA   — +1 new rows ✓
  [1128/3851] EUFN   — +1 new rows ✓
  [1129/3851] EVAX   — +1 new rows ✓
  [1130/3851] EVCM   — +1 new rows ✓
  [1131/3851] EVER   — +1 new rows ✓
  [1132/3851] EVGN   — +1 new rows ✓
  [1133/3851] EVGO   — +1 new rows ✓
  [1134/3851] EVMT   — +1 new rows ✓
  [1135/3851] EVO    — +1 new rows ✓
  [1136/3851] EVPF   — +1 new rows ✓
  [1137/3851] EVRG   — +1 new rows ✓
  [1138/3851] EVSD   — +1 new rows ✓
  [1139/3851] EVTV   — +1 new rows ✓
  [1140/3851] EVYM   — +1 new rows ✓
  [1141/3851] EWBC   — +1 new rows ✓
  [1142/3851] EWJV   — +1 new rows ✓
  [1143/3851] EWTX   — +1 new rows ✓
  [1144/3851] EXC    — +1 new rows ✓
  [1145/3851] EXE    — +1 new rows ✓
  [1146/3851] EXEL   — +1 new rows ✓
  [1147/3851] EXFY   — +1 new rows ✓
  [1148/3851] EXLS   — +1 new rows ✓
  [1149/3851] EXOZ   — +1 new rows ✓
  [1150/3851] EXPE   — +1 new rows ✓
  [1151/3851] EXPO   — +1 new rows ✓
  [1152/3851] EXTR   — +1 new rows ✓
  [1153/3851] EXUS   — +1 new rows ✓
  [1154/3851] EYE    — +1 new rows ✓
  [1155/3851] EYEG   — +1 new rows ✓
  [1156/3851] EYPT   — +1 new rows ✓
  [1157/3851] EZGO   — +1 new rows ✓
  [1158/3851] EZMO   — +1 new rows ✓
  [1159/3851] EZPW   — +1 new rows ✓
  [1160/3851] EZRA   — +1 new rows ✓
  [1161/3851] EZRO   — +1 new rows ✓
  [1162/3851] FA     — +1 new rows ✓
  [1163/3851] FAAA   — +1 new rows ✓
  [1164/3851] FAAR   — +1 new rows ✓
  [1165/3851] FAB    — +1 new rows ✓
  [1166/3851] FABC   — +1 new rows ✓
  [1167/3851] FAC    — +1 new rows ✓
  [1168/3851] FAD    — +1 new rows ✓
  [1169/3851] FALN   — +1 new rows ✓
  [1170/3851] FAMI   — +1 new rows ✓
  [1171/3851] FANG   — +1 new rows ✓
  [1172/3851] FAST   — +1 new rows ✓
  [1173/3851] FATE   — +1 new rows ✓
  [1174/3851] FBIO   — +1 new rows ✓
  [1175/3851] FBIOP  — +1 new rows ✓
  [1176/3851] FBIZ   — +1 new rows ✓
  [1177/3851] FBL    — +1 new rows ✓
  [1178/3851] FBLG   — +1 new rows ✓
  [1179/3851] FBNC   — +1 new rows ✓
  [1180/3851] FBOT   — +1 new rows ✓
  [1181/3851] FBRX   — +1 new rows ✓
  [1182/3851] FBYD   — +1 new rows ✓
  [1183/3851] FCA    — +1 new rows ✓
  [1184/3851] FCAL   — +1 new rows ✓
  [1185/3851] FCAP   — +1 new rows ✓
  [1186/3851] FCBC   — +1 new rows ✓
  [1187/3851] FCCO   — +1 new rows ✓
  [1188/3851] FCEF   — +1 new rows ✓
  [1189/3851] FCEL   — +1 new rows ✓
  [1190/3851] FCFS   — +1 new rows ✓
  [1191/3851] FCHL   — +1 new rows ✓
  [1192/3851] FCLO   — +1 new rows ✓
  [1193/3851] FCNCA  — +1 new rows ✓
  [1194/3851] FCNCN  — +1 new rows ✓
  [1195/3851] FCNCO  — +1 new rows ✓
  [1196/3851] FCNCP  — +1 new rows ✓
  [1197/3851] FCTE   — +1 new rows ✓
  [1198/3851] FCUV   — +1 new rows ✓
  [1199/3851] FCVT   — +1 new rows ✓
  [1200/3851] FDBC   — +1 new rows ✓
  [1201/3851] FDCF   — +1 new rows ✓
  [1202/3851] FDFF   — +1 new rows ✓
  [1203/3851] FDIF   — +1 new rows ✓
  [1204/3851] FDIG   — +1 new rows ✓
  [1205/3851] FDIQ   — +1 new rows ✓
  [1206/3851] FDIV   — +1 new rows ✓
  [1207/3851] FDMT   — +1 new rows ✓
  [1208/3851] FDNI   — +1 new rows ✓
  [1209/3851] FDRS   — +1 new rows ✓
  [1210/3851] FDRX   — +1 new rows ✓
  [1211/3851] FDT    — +1 new rows ✓
  [1212/3851] FDTS   — +1 new rows ✓
  [1213/3851] FDTX   — +1 new rows ✓
  [1214/3851] FEAM   — +1 new rows ✓
  [1215/3851] FEED   — +1 new rows ✓
  [1216/3851] FEIM   — +1 new rows ✓
  [1217/3851] FELE   — +1 new rows ✓
  [1218/3851] FEM    — +1 new rows ✓
  [1219/3851] FEMB   — +1 new rows ✓
  [1220/3851] FEMS   — +1 new rows ✓
  [1221/3851] FEMY   — +1 new rows ✓
  [1222/3851] FEP    — +1 new rows ✓
  [1223/3851] FEPI   — +1 new rows ✓
  [1224/3851] FER    — +1 new rows ✓
  [1225/3851] FEUZ   — +1 new rows ✓
  [1226/3851] FEX    — +1 new rows ✓
  [1227/3851] FFAI   — +1 new rows ✓
  [1228/3851] FFBC   — +1 new rows ✓
  [1229/3851] FFIN   — +1 new rows ✓
  [1230/3851] FFIV   — +1 new rows ✓
  [1231/3851] FFUT   — +1 new rows ✓
  [1232/3851] FGBI   — +1 new rows ✓
  [1233/3851] FGBIP  — +1 new rows ✓
  [1234/3851] FGI    — +1 new rows ✓
  [1235/3851] FGL    — +1 new rows ✓
  [1236/3851] FGM    — +1 new rows ✓
  [1237/3851] FGNX   — +1 new rows ✓

$FGNXP: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['FGNXP']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1238/3851] FGNXP  — no new data
  [1239/3851] FGSI   — +1 new rows ✓
  [1240/3851] FHB    — +1 new rows ✓
  [1241/3851] FHTX   — +1 new rows ✓
  [1242/3851] FIBK   — +1 new rows ✓
  [1243/3851] FICS   — +1 new rows ✓
  [1244/3851] FID    — +1 new rows ✓
  [1245/3851] FIEE   — +1 new rows ✓
  [1246/3851] FIGG   — +1 new rows ✓
  [1247/3851] FIGR   — +1 new rows ✓
  [1248/3851] FIMU   — +1 new rows ✓
  [1249/3851] FINW   — +1 new rows ✓
  [1250/3851] FINX   — +1 new rows ✓
  [1251/3851] FINY   — +1 new rows ✓
  [1252/3851] FISI   — +1 new rows ✓
  [1253/3851] FISV   — +1 new rows ✓
  [1254/3851] FIVE   — +1 new rows ✓
  [1255/3851] FIVN   — +1 new rows ✓
  [1256/3851] FIXD   — +1 new rows ✓
  [1257/3851] FIYY   — +1 new rows ✓
  [1258/3851] FIZZ   — +1 new rows ✓
  [1259/3851] FJP    — +1 new rows ✓
  [1260/3851] FKU    — +1 new rows ✓
  [1261/3851] FKWL   — +1 new rows ✓
  [1262/3851] FLDB   — +1 new rows ✓
  [1263/3851] FLEX   — +1 new rows ✓
  [1264/3851] FLGT   — +1 new rows ✓
  [1265/3851] FLN    — +1 new rows ✓
  [1266/3851] FLNA   — +1 new rows ✓
  [1267/3851] FLNC   — +1 new rows ✓
  [1268/3851] FLNT   — +1 new rows ✓
  [1269/3851] FLUX   — +1 new rows ✓
  [1270/3851] FLWS   — +1 new rows ✓
  [1271/3851] FLXS   — +1 new rows ✓
  [1272/3851] FLY    — +1 new rows ✓
  [1273/3851] FLYE   — +1 new rows ✓
  [1274/3851] FLYW   — +1 new rows ✓
  [1275/3851] FLZH   — +1 new rows ✓
  [1276/3851] FMAO   — +1 new rows ✓
  [1277/3851] FMB    — +1 new rows ✓
  [1278/3851] FMBH   — +1 new rows ✓
  [1279/3851] FMED   — +1 new rows ✓
  [1280/3851] FMET   — +1 new rows ✓
  [1281/3851] FMHI   — +1 new rows ✓
  [1282/3851] FMTM   — +1 new rows ✓
  [1283/3851] FMUB   — +1 new rows ✓
  [1284/3851] FMUN   — +1 new rows ✓
  [1285/3851] FNK    — +1 new rows ✓
  [1286/3851] FNKO   — +1 new rows ✓
  [1287/3851] FNLC   — +1 new rows ✓
  [1288/3851] FNUC   — +1 new rows ✓
  [1289/3851] FNWB   — +1 new rows ✓
  [1290/3851] FNWD   — +1 new rows ✓
  [1291/3851] FNX    — +1 new rows ✓
  [1292/3851] FNY    — +1 new rows ✓
  [1293/3851] FOFO   — +1 new rows ✓
  [1294/3851] FORM   — +1 new rows ✓
  [1295/3851] FORR   — +1 new rows ✓

$FORTY: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['FORTY']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1296/3851] FORTY  — no new data
  [1297/3851] FOSL   — +1 new rows ✓
  [1298/3851] FOX    — +1 new rows ✓
  [1299/3851] FOXA   — +1 new rows ✓
  [1300/3851] FOXF   — +1 new rows ✓
  [1301/3851] FPA    — +1 new rows ✓
  [1302/3851] FPXE   — +1 new rows ✓
  [1303/3851] FPXI   — +1 new rows ✓
  [1304/3851] FRAF   — +1 new rows ✓
  [1305/3851] FRD    — +1 new rows ✓
  [1306/3851] FREI   — +1 new rows ✓
  [1307/3851] FRGT   — +1 new rows ✓
  [1308/3851] FRHC   — +1 new rows ✓
  [1309/3851] FRME   — +1 new rows ✓

$FRMEP: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['FRMEP']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1310/3851] FRMEP  — no new data
  [1311/3851] FRMI   — +1 new rows ✓
  [1312/3851] FRMM   — +1 new rows ✓
  [1313/3851] FROG   — +1 new rows ✓
  [1314/3851] FRPH   — +1 new rows ✓
  [1315/3851] FRPT   — +1 new rows ✓
  [1316/3851] FRSH   — +1 new rows ✓
  [1317/3851] FRSX   — +1 new rows ✓
  [1318/3851] FRVO   — +1 new rows ✓
  [1319/3851] FRWD   — +1 new rows ✓
  [1320/3851] FSBC   — +1 new rows ✓
  [1321/3851] FSBW   — +1 new rows ✓
  [1322/3851] FSCS   — +1 new rows ✓
  [1323/3851] FSGS   — +1 new rows ✓
  [1324/3851] FSLR   — +1 new rows ✓
  [1325/3851] FSLY   — +1 new rows ✓
  [1326/3851] FSTB   — +1 new rows ✓
  [1327/3851] FSTR   — +1 new rows ✓
  [1328/3851] FSUN   — +1 new rows ✓
  [1329/3851] FSV    — +1 new rows ✓
  [1330/3851] FSZ    — +1 new rows ✓
  [1331/3851] FTA    — +1 new rows ✓
  [1332/3851] FTAG   — +1 new rows ✓
  [1333/3851] FTAI   — +1 new rows ✓
  [1334/3851] FTAIM  — +1 new rows ✓
  [1335/3851] FTC    — +1 new rows ✓
  [1336/3851] FTCI   — +1 new rows ✓
  [1337/3851] FTCS   — +1 new rows ✓
  [1338/3851] FTDR   — +1 new rows ✓
  [1339/3851] FTDS   — +1 new rows ✓
  [1340/3851] FTFT   — +1 new rows ✓
  [1341/3851] FTGC   — +1 new rows ✓
  [1342/3851] FTGS   — +1 new rows ✓
  [1343/3851] FTH    — +1 new rows ✓
  [1344/3851] FTHI   — +1 new rows ✓
  [1345/3851] FTHM   — +1 new rows ✓
  [1346/3851] FTLF   — +1 new rows ✓
  [1347/3851] FTNT   — +1 new rows ✓
  [1348/3851] FTQI   — +1 new rows ✓
  [1349/3851] FTRE   — +1 new rows ✓
  [1350/3851] FTRI   — +1 new rows ✓
  [1351/3851] FTSL   — +1 new rows ✓
  [1352/3851] FTSM   — +1 new rows ✓
  [1353/3851] FTXG   — +1 new rows ✓
  [1354/3851] FTXH   — +1 new rows ✓
  [1355/3851] FTXL   — +1 new rows ✓
  [1356/3851] FTXN   — +1 new rows ✓
  [1357/3851] FTXO   — +1 new rows ✓
  [1358/3851] FTXR   — +1 new rows ✓
  [1359/3851] FULC   — +1 new rows ✓
  [1360/3851] FULT   — +1 new rows ✓
  [1361/3851] FUNC   — +1 new rows ✓
  [1362/3851] FUTG   — +1 new rows ✓
  [1363/3851] FUTU   — +1 new rows ✓
  [1364/3851] FV     — +1 new rows ✓
  [1365/3851] FVC    — +1 new rows ✓
  [1366/3851] FWDI   — +1 new rows ✓
  [1367/3851] FWONA  — +1 new rows ✓
  [1368/3851] FWONK  — +1 new rows ✓
  [1369/3851] FWRD   — +1 new rows ✓
  [1370/3851] FWRG   — +1 new rows ✓
  [1371/3851] FXNC   — +1 new rows ✓
  [1372/3851] FYC    — +1 new rows ✓
  [1373/3851] FYT    — +1 new rows ✓
  [1374/3851] FYX    — +1 new rows ✓
  [1375/3851] GABC   — +1 new rows ✓
  [1376/3851] GAIA   — +1 new rows ✓
  [1377/3851] GAING  — +1 new rows ✓
  [1378/3851] GAINI  — +1 new rows ✓
  [1379/3851] GAINZ  — +1 new rows ✓
  [1380/3851] GAME   — +1 new rows ✓
  [1381/3851] GARY   — +1 new rows ✓
  [1382/3851] GAVA   — +1 new rows ✓
  [1383/3851] GBFH   — +1 new rows ✓
  [1384/3851] GBLI   — +1 new rows ✓
  [1385/3851] GBUG   — +1 new rows ✓
  [1386/3851] GCBC   — +1 new rows ✓
  [1387/3851] GCT    — +1 new rows ✓
  [1388/3851] GCTK   — +1 new rows ✓
  [1389/3851] GDC    — +1 new rows ✓
  [1390/3851] GDEV   — +1 new rows ✓
  [1391/3851] GDHG   — +1 new rows ✓
  [1392/3851] GDRX   — +1 new rows ✓
  [1393/3851] GDS    — +1 new rows ✓
  [1394/3851] GDYN   — +1 new rows ✓
  [1395/3851] GECC   — +1 new rows ✓

$GECCG: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['GECCG']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1396/3851] GECCG  — no new data
  [1397/3851] GECCH  — +1 new rows ✓
  [1398/3851] GECCI  — +1 new rows ✓
  [1399/3851] GEG    — +1 new rows ✓
  [1400/3851] GEGGL  — +1 new rows ✓
  [1401/3851] GEHC   — +1 new rows ✓
  [1402/3851] GEME   — +1 new rows ✓
  [1403/3851] GEMG   — +1 new rows ✓
  [1404/3851] GEMI   — +1 new rows ✓
  [1405/3851] GEN    — +1 new rows ✓
  [1406/3851] GENK   — +1 new rows ✓
  [1407/3851] GENZ   — +1 new rows ✓
  [1408/3851] GEOS   — +1 new rows ✓
  [1409/3851] GEQ    — +1 new rows ✓
  [1410/3851] GEVG   — +1 new rows ✓
  [1411/3851] GEVO   — +1 new rows ✓
  [1412/3851] GEW    — +1 new rows ✓
  [1413/3851] GFAI   — +1 new rows ✓
  [1414/3851] GFGF   — +1 new rows ✓
  [1415/3851] GFLW   — +1 new rows ✓
  [1416/3851] GFS    — +1 new rows ✓
  [1417/3851] GGAL   — +1 new rows ✓
  [1418/3851] GGLL   — +1 new rows ✓
  [1419/3851] GGLS   — +1 new rows ✓
  [1420/3851] GGR    — +1 new rows ✓
  [1421/3851] GH     — +1 new rows ✓
  [1422/3851] GHRS   — +1 new rows ✓
  [1423/3851] GIBO   — +1 new rows ✓
  [1424/3851] GIEQ   — +1 new rows ✓
  [1425/3851] GIII   — +1 new rows ✓
  [1426/3851] GILD   — +1 new rows ✓
  [1427/3851] GILT   — +1 new rows ✓
  [1428/3851] GIND   — +1 new rows ✓
  [1429/3851] GINX   — +1 new rows ✓
  [1430/3851] GKAT   — +1 new rows ✓
  [1431/3851] GLAD   — +1 new rows ✓
  [1432/3851] GLBE   — +1 new rows ✓
  [1433/3851] GLBS   — +1 new rows ✓
  [1434/3851] GLCR   — +1 new rows ✓
  [1435/3851] GLDB   — +1 new rows ✓
  [1436/3851] GLDI   — +1 new rows ✓
  [1437/3851] GLGG   — +1 new rows ✓
  [1438/3851] GLIBA  — +1 new rows ✓
  [1439/3851] GLIBK  — +1 new rows ✓
  [1440/3851] GLMD   — +1 new rows ✓
  [1441/3851] GLNG   — +1 new rows ✓
  [1442/3851] GLOW   — +1 new rows ✓
  [1443/3851] GLPI   — +1 new rows ✓
  [1444/3851] GLRE   — +1 new rows ✓
  [1445/3851] GLSI   — +1 new rows ✓
  [1446/3851] GLUE   — +1 new rows ✓
  [1447/3851] GLWG   — +1 new rows ✓
  [1448/3851] GLXG   — +1 new rows ✓
  [1449/3851] GLXY   — +1 new rows ✓
  [1450/3851] GMAB   — +1 new rows ✓
  [1451/3851] GMEX   — +1 new rows ✓
  [1452/3851] GMM    — +1 new rows ✓
  [1453/3851] GNLN   — +1 new rows ✓
  [1454/3851] GNLX   — +1 new rows ✓
  [1455/3851] GNMA   — +1 new rows ✓
  [1456/3851] GNOM   — +1 new rows ✓
  [1457/3851] GNPX   — +1 new rows ✓
  [1458/3851] GNTX   — +1 new rows ✓
  [1459/3851] GO     — +1 new rows ✓
  [1460/3851] GOGO   — +1 new rows ✓
  [1461/3851] GOODN  — +1 new rows ✓
  [1462/3851] GOODO  — +1 new rows ✓
  [1463/3851] GOOG   — +1 new rows ✓
  [1464/3851] GOOGL  — +1 new rows ✓
  [1465/3851] GOOGM  — +1 new rows ✓
  [1466/3851] GOOGN  — +1 new rows ✓
  [1467/3851] GOSS   — +1 new rows ✓
  [1468/3851] GOU    — +1 new rows ✓
  [1469/3851] GOVI   — +1 new rows ✓
  [1470/3851] GOVX   — +1 new rows ✓
  [1471/3851] GP     — +1 new rows ✓
  [1472/3851] GPCR   — +1 new rows ✓
  [1473/3851] GPIQ   — +1 new rows ✓
  [1474/3851] GPIX   — +1 new rows ✓
  [1475/3851] GPRE   — +1 new rows ✓
  [1476/3851] GPRF   — +1 new rows ✓
  [1477/3851] GPRO   — +1 new rows ✓
  [1478/3851] GPT    — +1 new rows ✓
  [1479/3851] GQQQ   — +1 new rows ✓
  [1480/3851] GRAL   — +1 new rows ✓
  [1481/3851] GRCE   — +1 new rows ✓
  [1482/3851] GRDX   — +1 new rows ✓
  [1483/3851] GREE   — +1 new rows ✓
  [1484/3851] GREEL  — +1 new rows ✓
  [1485/3851] GRFS   — +1 new rows ✓
  [1486/3851] GRI    — +1 new rows ✓
  [1487/3851] GRID   — +1 new rows ✓
  [1488/3851] GRIN   — +1 new rows ✓
  [1489/3851] GRNQ   — +1 new rows ✓
  [1490/3851] GRPN   — +1 new rows ✓
  [1491/3851] GRRR   — +1 new rows ✓
  [1492/3851] GRVY   — +1 new rows ✓
  [1493/3851] GRW    — +1 new rows ✓
  [1494/3851] GRWG   — +1 new rows ✓
  [1495/3851] GSAT   — +1 new rows ✓
  [1496/3851] GSBC   — +1 new rows ✓
  [1497/3851] GSGO   — +1 new rows ✓
  [1498/3851] GSHD   — +1 new rows ✓
  [1499/3851] GSIB   — +1 new rows ✓
  [1500/3851] GSIW   — +1 new rows ✓
  [1501/3851] GSM    — +1 new rows ✓
  [1502/3851] GSUN   — +1 new rows ✓
  [1503/3851] GT     — +1 new rows ✓
  [1504/3851] GTBP   — +1 new rows ✓
  [1505/3851] GTLB   — +1 new rows ✓
  [1506/3851] GTM    — +1 new rows ✓
  [1507/3851] GTOP   — +1 new rows ✓
  [1508/3851] GTOQ   — +1 new rows ✓
  [1509/3851] GTPE   — +1 new rows ✓
  [1510/3851] GTR    — +1 new rows ✓
  [1511/3851] GTX    — +1 new rows ✓
  [1512/3851] GURE   — +1 new rows ✓
  [1513/3851] GUSE   — +1 new rows ✓
  [1514/3851] GV     — +1 new rows ✓
  [1515/3851] GVH    — +1 new rows ✓
  [1516/3851] GVLE   — +1 new rows ✓
  [1517/3851] GWAV   — +1 new rows ✓
  [1518/3851] GXAI   — +1 new rows ✓
  [1519/3851] GXDW   — +1 new rows ✓
  [1520/3851] GYRE   — +1 new rows ✓

$GYRO: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['GYRO']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1521/3851] GYRO   — no new data
  [1522/3851] HAFC   — +1 new rows ✓
  [1523/3851] HAIN   — +1 new rows ✓
  [1524/3851] HALO   — +1 new rows ✓
  [1525/3851] HAO    — +1 new rows ✓
  [1526/3851] HAPN   — +1 new rows ✓
  [1527/3851] HAS    — +1 new rows ✓
  [1528/3851] HBANL  — +1 new rows ✓
  [1529/3851] HBANM  — +1 new rows ✓
  [1530/3851] HBANZ  — +1 new rows ✓
  [1531/3851] HBCP   — +1 new rows ✓
  [1532/3851] HBDC   — +1 new rows ✓
  [1533/3851] HBIO   — +1 new rows ✓
  [1534/3851] HBR    — +1 new rows ✓
  [1535/3851] HBT    — +1 new rows ✓
  [1536/3851] HCAI   — +1 new rows ✓
  [1537/3851] HCAT   — +1 new rows ✓
  [1538/3851] HCKT   — +1 new rows ✓
  [1539/3851] HCM    — +1 new rows ✓
  [1540/3851] HCOW   — +1 new rows ✓
  [1541/3851] HCSG   — +1 new rows ✓
  [1542/3851] HCTI   — +1 new rows ✓
  [1543/3851] HCWB   — +1 new rows ✓
  [1544/3851] HDL    — +1 new rows ✓
  [1545/3851] HEAL   — +1 new rows ✓
  [1546/3851] HECO   — +1 new rows ✓
  [1547/3851] HELE   — +1 new rows ✓
  [1548/3851] HELP   — +1 new rows ✓
  [1549/3851] HEQQ   — +1 new rows ✓
  [1550/3851] HERD   — +1 new rows ✓
  [1551/3851] HERO   — +1 new rows ✓
  [1552/3851] HERZ   — +1 new rows ✓
  [1553/3851] HFBL   — +1 new rows ✓
  [1554/3851] HFFG   — +1 new rows ✓
  [1555/3851] HFSP   — +1 new rows ✓
  [1556/3851] HFWA   — +1 new rows ✓
  [1557/3851] HHS    — +1 new rows ✓
  [1558/3851] HIDE   — +1 new rows ✓
  [1559/3851] HIFS   — +1 new rows ✓
  [1560/3851] HIMX   — +1 new rows ✓
  [1561/3851] HIMZ   — +1 new rows ✓
  [1562/3851] HIND   — +1 new rows ✓
  [1563/3851] HIS    — +1 new rows ✓
  [1564/3851] HISF   — +1 new rows ✓
  [1565/3851] HIVE   — +1 new rows ✓
  [1566/3851] HKIT   — +1 new rows ✓
  [1567/3851] HLAL   — +1 new rows ✓
  [1568/3851] HLNE   — +1 new rows ✓
  [1569/3851] HMH    — +1 new rows ✓
  [1570/3851] HNDL   — +1 new rows ✓
  [1571/3851] HNNAZ  — +1 new rows ✓
  [1572/3851] HNRG   — +1 new rows ✓
  [1573/3851] HNST   — +1 new rows ✓
  [1574/3851] HNVR   — +1 new rows ✓
  [1575/3851] HODU   — +1 new rows ✓
  [1576/3851] HOFT   — +1 new rows ✓
  [1577/3851] HOLO   — +1 new rows ✓
  [1578/3851] HON    — +1 new rows ✓
  [1579/3851] HONAV  — +1 new rows ✓
  [1580/3851] HONIV  — +1 new rows ✓
  [1581/3851] HOOD   — +1 new rows ✓
  [1582/3851] HOOG   — +1 new rows ✓
  [1583/3851] HOOX   — +1 new rows ✓
  [1584/3851] HOVNP  — +1 new rows ✓
  [1585/3851] HOWL   — +1 new rows ✓
  [1586/3851] HPK    — +1 new rows ✓
  [1587/3851] HQ     — +1 new rows ✓
  [1588/3851] HQGO   — +1 new rows ✓
  [1589/3851] HQI    — +1 new rows ✓
  [1590/3851] HQWWW  — +1 new rows ✓
  [1591/3851] HQY    — +1 new rows ✓
  [1592/3851] HRMY   — +1 new rows ✓
  [1593/3851] HROW   — +1 new rows ✓
  [1594/3851] HRTS   — +1 new rows ✓
  [1595/3851] HRTX   — +1 new rows ✓
  [1596/3851] HSAI   — +1 new rows ✓
  [1597/3851] HSCS   — +1 new rows ✓
  [1598/3851] HSDT   — +1 new rows ✓
  [1599/3851] HSIC   — +1 new rows ✓
  [1600/3851] HST    — +1 new rows ✓
  [1601/3851] HSTM   — +1 new rows ✓
  [1602/3851] HTCO   — +1 new rows ✓
  [1603/3851] HTCR   — +1 new rows ✓
  [1604/3851] HTFL   — +1 new rows ✓
  [1605/3851] HTHT   — +1 new rows ✓
  [1606/3851] HTLD   — +1 new rows ✓
  [1607/3851] HTO    — +1 new rows ✓
  [1608/3851] HTOO   — +1 new rows ✓
  [1609/3851] HTZ    — +1 new rows ✓
  [1610/3851] HUBC   — +1 new rows ✓
  [1611/3851] HUBG   — +1 new rows ✓
  [1612/3851] HUDI   — +1 new rows ✓
  [1613/3851] HUIZ   — +1 new rows ✓
  [1614/3851] HURA   — +1 new rows ✓
  [1615/3851] HURC   — +1 new rows ✓
  [1616/3851] HURN   — +1 new rows ✓
  [1617/3851] HUT    — +1 new rows ✓
  [1618/3851] HUTG   — +1 new rows ✓
  [1619/3851] HWAY   — +1 new rows ✓
  [1620/3851] HWBK   — +1 new rows ✓
  [1621/3851] HWC    — +1 new rows ✓
  [1622/3851] HWCPZ  — +1 new rows ✓
  [1623/3851] HWH    — +1 new rows ✓
  [1624/3851] HWKN   — +1 new rows ✓
  [1625/3851] HWSM   — +1 new rows ✓
  [1626/3851] HYBI   — +1 new rows ✓
  [1627/3851] HYDR   — +1 new rows ✓
  [1628/3851] HYFM   — +1 new rows ✓
  [1629/3851] HYLS   — +1 new rows ✓
  [1630/3851] HYMC   — +1 new rows ✓
  [1631/3851] HYP    — +1 new rows ✓
  [1632/3851] HYPD   — +1 new rows ✓
  [1633/3851] HYPG   — +1 new rows ✓
  [1634/3851] HYXF   — +1 new rows ✓
  [1635/3851] HYZD   — +1 new rows ✓
  [1636/3851] IALT   — +1 new rows ✓
  [1637/3851] IART   — +1 new rows ✓
  [1638/3851] IBAT   — +1 new rows ✓
  [1639/3851] IBB    — +1 new rows ✓
  [1640/3851] IBBQ   — +1 new rows ✓
  [1641/3851] IBCP   — +1 new rows ✓
  [1642/3851] IBEX   — +1 new rows ✓
  [1643/3851] IBG    — +1 new rows ✓
  [1644/3851] IBGA   — +1 new rows ✓
  [1645/3851] IBGB   — +1 new rows ✓
  [1646/3851] IBGC   — +1 new rows ✓
  [1647/3851] IBGK   — +1 new rows ✓
  [1648/3851] IBGL   — +1 new rows ✓
  [1649/3851] IBGM   — +1 new rows ✓
  [1650/3851] IBIO   — +1 new rows ✓
  [1651/3851] IBIT   — +1 new rows ✓
  [1652/3851] IBKR   — +1 new rows ✓
  [1653/3851] IBOC   — +1 new rows ✓
  [1654/3851] IBOT   — +1 new rows ✓
  [1655/3851] IBRX   — +1 new rows ✓
  [1656/3851] IBTG   — +1 new rows ✓
  [1657/3851] IBTH   — +1 new rows ✓
  [1658/3851] IBTI   — +1 new rows ✓
  [1659/3851] IBTJ   — +1 new rows ✓
  [1660/3851] IBTK   — +1 new rows ✓
  [1661/3851] IBTL   — +1 new rows ✓
  [1662/3851] IBTM   — +1 new rows ✓
  [1663/3851] IBTO   — +1 new rows ✓
  [1664/3851] IBTP   — +1 new rows ✓
  [1665/3851] IBTQ   — +1 new rows ✓
  [1666/3851] IBTR   — +1 new rows ✓
  [1667/3851] ICCM   — +1 new rows ✓
  [1668/3851] ICFI   — +1 new rows ✓
  [1669/3851] ICHR   — +1 new rows ✓
  [1670/3851] ICLN   — +1 new rows ✓
  [1671/3851] ICLR   — +1 new rows ✓
  [1672/3851] ICON   — +1 new rows ✓
  [1673/3851] ICOP   — +1 new rows ✓
  [1674/3851] ICU    — +1 new rows ✓
  [1675/3851] ICUI   — +1 new rows ✓
  [1676/3851] IDAI   — +1 new rows ✓
  [1677/3851] IDCC   — +1 new rows ✓
  [1678/3851] IDEF   — +1 new rows ✓
  [1679/3851] IDN    — +1 new rows ✓
  [1680/3851] IDVY   — +1 new rows ✓
  [1681/3851] IDXX   — +1 new rows ✓
  [1682/3851] IDYA   — +1 new rows ✓
  [1683/3851] IEF    — +1 new rows ✓
  [1684/3851] IEI    — +1 new rows ✓
  [1685/3851] IEP    — +1 new rows ✓
  [1686/3851] IESC   — +1 new rows ✓
  [1687/3851] IEUS   — +1 new rows ✓
  [1688/3851] IFBD   — +1 new rows ✓
  [1689/3851] IFGL   — +1 new rows ✓
  [1690/3851] IFLO   — +1 new rows ✓
  [1691/3851] IFRX   — +1 new rows ✓
  [1692/3851] IFV    — +1 new rows ✓
  [1693/3851] IGF    — +1 new rows ✓
  [1694/3851] IGIB   — +1 new rows ✓
  [1695/3851] IGIC   — +1 new rows ✓
  [1696/3851] IGOV   — +1 new rows ✓
  [1697/3851] IGSB   — +1 new rows ✓
  [1698/3851] IHRT   — +1 new rows ✓
  [1699/3851] IIIV   — +1 new rows ✓
  [1700/3851] IJT    — +1 new rows ✓
  [1701/3851] IKT    — +1 new rows ✓
  [1702/3851] ILAG   — +1 new rows ✓
  [1703/3851] ILIT   — +1 new rows ✓
  [1704/3851] ILLR   — +1 new rows ✓
  [1705/3851] ILMN   — +1 new rows ✓
  [1706/3851] ILPT   — +1 new rows ✓
  [1707/3851] IMA    — +1 new rows ✓
  [1708/3851] IMCC   — +1 new rows ✓
  [1709/3851] IMCR   — +1 new rows ✓
  [1710/3851] IMCV   — +1 new rows ✓
  [1711/3851] IMDX   — +1 new rows ✓
  [1712/3851] IMKTA  — +1 new rows ✓
  [1713/3851] IMMP   — +1 new rows ✓
  [1714/3851] IMNM   — +1 new rows ✓
  [1715/3851] IMNN   — +1 new rows ✓
  [1716/3851] IMOM   — +1 new rows ✓
  [1717/3851] IMOS   — +1 new rows ✓
  [1718/3851] IMPP   — +1 new rows ✓
  [1719/3851] IMPPP  — +1 new rows ✓
  [1720/3851] IMRN   — +1 new rows ✓
  [1721/3851] IMRX   — +1 new rows ✓
  [1722/3851] IMSR   — +1 new rows ✓
  [1723/3851] IMTE   — +1 new rows ✓
  [1724/3851] IMUX   — +1 new rows ✓
  [1725/3851] IMVT   — +1 new rows ✓
  [1726/3851] IMXI   — +1 new rows ✓
  [1727/3851] INAB   — +1 new rows ✓
  [1728/3851] INBK   — +1 new rows ✓

$INBKZ: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['INBKZ']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1729/3851] INBKZ  — no new data
  [1730/3851] INBS   — +1 new rows ✓
  [1731/3851] INBX   — +1 new rows ✓
  [1732/3851] INCY   — +1 new rows ✓
  [1733/3851] IND    — +1 new rows ✓
  [1734/3851] INDB   — +1 new rows ✓
  [1735/3851] INDH   — +1 new rows ✓
  [1736/3851] INDP   — +1 new rows ✓
  [1737/3851] INDQ   — +1 new rows ✓
  [1738/3851] INDV   — +1 new rows ✓
  [1739/3851] INDY   — +1 new rows ✓
  [1740/3851] INGN   — +1 new rows ✓

$INHD: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['INHD']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1741/3851] INHD   — no new data
  [1742/3851] INIO   — +1 new rows ✓
  [1743/3851] INKT   — +1 new rows ✓
  [1744/3851] INLF   — +1 new rows ✓
  [1745/3851] INM    — +1 new rows ✓
  [1746/3851] INMB   — +1 new rows ✓
  [1747/3851] INMD   — +1 new rows ✓
  [1748/3851] INNV   — +1 new rows ✓
  [1749/3851] INO    — +1 new rows ✓
  [1750/3851] INOD   — +1 new rows ✓
  [1751/3851] INRO   — +1 new rows ✓
  [1752/3851] INSG   — +1 new rows ✓
  [1753/3851] INSM   — +1 new rows ✓
  [1754/3851] INTA   — +1 new rows ✓
  [1755/3851] INTC   — +1 new rows ✓
  [1756/3851] INTG   — +1 new rows ✓
  [1757/3851] INTJ   — +1 new rows ✓
  [1758/3851] INTS   — +1 new rows ✓
  [1759/3851] INTU   — +1 new rows ✓
  [1760/3851] INTW   — +1 new rows ✓
  [1761/3851] INTZ   — +1 new rows ✓
  [1762/3851] INVA   — +1 new rows ✓
  [1763/3851] INVE   — +1 new rows ✓
  [1764/3851] IONL   — +1 new rows ✓
  [1765/3851] IONR   — +1 new rows ✓
  [1766/3851] IONS   — +1 new rows ✓
  [1767/3851] IONX   — +1 new rows ✓
  [1768/3851] IONZ   — +1 new rows ✓
  [1769/3851] IOSP   — +1 new rows ✓
  [1770/3851] IOTR   — +1 new rows ✓
  [1771/3851] IOVA   — +1 new rows ✓
  [1772/3851] IPAR   — +1 new rows ✓
  [1773/3851] IPDN   — +1 new rows ✓
  [1774/3851] IPGP   — +1 new rows ✓
  [1775/3851] IPKW   — +1 new rows ✓
  [1776/3851] IPM    — +1 new rows ✓
  [1777/3851] IPSC   — +1 new rows ✓
  [1778/3851] IPST   — +1 new rows ✓
  [1779/3851] IPW    — +1 new rows ✓
  [1780/3851] IPWR   — +1 new rows ✓
  [1781/3851] IPX    — +1 new rows ✓
  [1782/3851] IQ     — +1 new rows ✓
  [1783/3851] IQQQ   — +1 new rows ✓
  [1784/3851] IQST   — +1 new rows ✓
  [1785/3851] IRD    — +1 new rows ✓
  [1786/3851] IRDM   — +1 new rows ✓
  [1787/3851] IREG   — +1 new rows ✓
  [1788/3851] IREN   — +1 new rows ✓
  [1789/3851] IRMD   — +1 new rows ✓
  [1790/3851] IRON   — +1 new rows ✓
  [1791/3851] IRTC   — +1 new rows ✓
  [1792/3851] ISBA   — +1 new rows ✓
  [1793/3851] ISHG   — +1 new rows ✓
  [1794/3851] ISHP   — +1 new rows ✓
  [1795/3851] ISPC   — +1 new rows ✓
  [1796/3851] ISRG   — +1 new rows ✓
  [1797/3851] ISSC   — +1 new rows ✓
  [1798/3851] ISTB   — +1 new rows ✓
  [1799/3851] ISTM   — +1 new rows ✓
  [1800/3851] ISTR   — +1 new rows ✓
  [1801/3851] ISUL   — +1 new rows ✓
  [1802/3851] ITIC   — +1 new rows ✓
  [1803/3851] ITOC   — +1 new rows ✓
  [1804/3851] ITRI   — +1 new rows ✓
  [1805/3851] ITRN   — +1 new rows ✓
  [1806/3851] IUS    — +1 new rows ✓
  [1807/3851] IUSB   — +1 new rows ✓
  [1808/3851] IUSG   — +1 new rows ✓
  [1809/3851] IUSV   — +1 new rows ✓
  [1810/3851] IVAL   — +1 new rows ✓
  [1811/3851] IVDA   — +1 new rows ✓
  [1812/3851] IVF    — +1 new rows ✓
  [1813/3851] IVSI   — +1 new rows ✓
  [1814/3851] IVSS   — +1 new rows ✓
  [1815/3851] IVSX   — +1 new rows ✓
  [1816/3851] IVVD   — ERROR: Not found: stocks/prices_IVVD.csv
  [1817/3851] IXHL   — +1 new rows ✓
  [1818/3851] IXUS   — +1 new rows ✓
  [1819/3851] IZEA   — +1 new rows ✓
  [1820/3851] IZM    — +1 new rows ✓
  [1821/3851] JACK   — +1 new rows ✓
  [1822/3851] JAGX   — +1 new rows ✓
  [1823/3851] JAKK   — +1 new rows ✓
  [1824/3851] JANX   — +1 new rows ✓
  [1825/3851] JAPN   — +1 new rows ✓
  [1826/3851] JAZZ   — +1 new rows ✓
  [1827/3851] JBDI   — +1 new rows ✓
  [1828/3851] JBHT   — +1 new rows ✓
  [1829/3851] JBIO   — +1 new rows ✓
  [1830/3851] JBLU   — +1 new rows ✓
  [1831/3851] JBSS   — +1 new rows ✓
  [1832/3851] JCAP   — +1 new rows ✓
  [1833/3851] JCSE   — +1 new rows ✓
  [1834/3851] JD     — +1 new rows ✓
  [1835/3851] JDOC   — +1 new rows ✓

$JDZG: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['JDZG']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1836/3851] JDZG   — no new data
  [1837/3851] JEM    — +1 new rows ✓
  [1838/3851] JEMA   — +1 new rows ✓
  [1839/3851] JEPQ   — +1 new rows ✓
  [1840/3851] JF     — +1 new rows ✓
  [1841/3851] JFU    — +1 new rows ✓
  [1842/3851] JG     — +1 new rows ✓
  [1843/3851] JGLO   — +1 new rows ✓
  [1844/3851] JHAI   — +1 new rows ✓
  [1845/3851] JIVE   — +1 new rows ✓
  [1846/3851] JJSF   — +1 new rows ✓
  [1847/3851] JKHY   — +1 new rows ✓
  [1848/3851] JLHL   — +1 new rows ✓
  [1849/3851] JMID   — +1 new rows ✓
  [1850/3851] JMSB   — +1 new rows ✓
  [1851/3851] JOUT   — +1 new rows ✓
  [1852/3851] JOYT   — +1 new rows ✓
  [1853/3851] JOYY   — +1 new rows ✓
  [1854/3851] JPEF   — +1 new rows ✓
  [1855/3851] JPFP   — +1 new rows ✓
  [1856/3851] JPY    — +1 new rows ✓
  [1857/3851] JRVR   — +1 new rows ✓
  [1858/3851] JSMD   — +1 new rows ✓
  [1859/3851] JSML   — +1 new rows ✓
  [1860/3851] JSPR   — +1 new rows ✓
  [1861/3851] JTAI   — +1 new rows ✓
  [1862/3851] JTEK   — +1 new rows ✓
  [1863/3851] JVA    — +1 new rows ✓
  [1864/3851] JWEL   — +1 new rows ✓
  [1865/3851] JXG    — +1 new rows ✓
  [1866/3851] JYD    — +1 new rows ✓
  [1867/3851] JYNT   — +1 new rows ✓
  [1868/3851] JZ     — +1 new rows ✓
  [1869/3851] JZXN   — +1 new rows ✓
  [1870/3851] KALA   — +1 new rows ✓
  [1871/3851] KALU   — +1 new rows ✓
  [1872/3851] KARD   — +1 new rows ✓
  [1873/3851] KARO   — +1 new rows ✓
  [1874/3851] KAT    — +1 new rows ✓
  [1875/3851] KBAB   — +1 new rows ✓
  [1876/3851] KBDU   — +1 new rows ✓
  [1877/3851] KBWB   — +1 new rows ✓
  [1878/3851] KBWP   — +1 new rows ✓
  [1879/3851] KC     — +1 new rows ✓
  [1880/3851] KDP    — +1 new rows ✓
  [1881/3851] KE     — +1 new rows ✓
  [1882/3851] KEAT   — +1 new rows ✓
  [1883/3851] KELYA  — +1 new rows ✓
  [1884/3851] KELYB  — +1 new rows ✓
  [1885/3851] KEQU   — +1 new rows ✓
  [1886/3851] KG     — +1 new rows ✓
  [1887/3851] KGEI   — +1 new rows ✓
  [1888/3851] KHC    — +1 new rows ✓
  [1889/3851] KIDS   — +1 new rows ✓
  [1890/3851] KIDZ   — +1 new rows ✓
  [1891/3851] KINS   — +1 new rows ✓
  [1892/3851] KIQQ   — +1 new rows ✓
  [1893/3851] KITT   — +1 new rows ✓
  [1894/3851] KJD    — +1 new rows ✓
  [1895/3851] KLAC   — +1 new rows ✓
  [1896/3851] KLAG   — +1 new rows ✓
  [1897/3851] KLIC   — +1 new rows ✓
  [1898/3851] KLRA   — +1 new rows ✓
  [1899/3851] KLRS   — +1 new rows ✓
  [1900/3851] KLXE   — +1 new rows ✓
  [1901/3851] KMB    — +1 new rows ✓
  [1902/3851] KMLI   — +1 new rows ✓
  [1903/3851] KMTS   — +1 new rows ✓
  [1904/3851] KNDI   — +1 new rows ✓
  [1905/3851] KNGZ   — +1 new rows ✓
  [1906/3851] KNSA   — +1 new rows ✓
  [1907/3851] KOD    — +1 new rows ✓
  [1908/3851] KOID   — +1 new rows ✓
  [1909/3851] KOSS   — +1 new rows ✓
  [1910/3851] KPLT   — +1 new rows ✓
  [1911/3851] KPRX   — +1 new rows ✓
  [1912/3851] KPTI   — +1 new rows ✓
  [1913/3851] KQQQ   — +1 new rows ✓
  [1914/3851] KRKR   — +1 new rows ✓
  [1915/3851] KRMA   — +1 new rows ✓
  [1916/3851] KRNT   — +1 new rows ✓
  [1917/3851] KROP   — +1 new rows ✓
  [1918/3851] KROS   — +1 new rows ✓
  [1919/3851] KRRO   — +1 new rows ✓
  [1920/3851] KRT    — +1 new rows ✓
  [1921/3851] KRUS   — +1 new rows ✓
  [1922/3851] KRYS   — +1 new rows ✓
  [1923/3851] KSCP   — +1 new rows ✓
  [1924/3851] KSPI   — +1 new rows ✓
  [1925/3851] KTOS   — +1 new rows ✓
  [1926/3851] KTTA   — +1 new rows ✓
  [1927/3851] KURA   — +1 new rows ✓
  [1928/3851] KUST   — +1 new rows ✓
  [1929/3851] KXIN   — +1 new rows ✓
  [1930/3851] KYMR   — +1 new rows ✓
  [1931/3851] KYNB   — +1 new rows ✓
  [1932/3851] KYTX   — +1 new rows ✓
  [1933/3851] KZIA   — +1 new rows ✓
  [1934/3851] LAB    — +1 new rows ✓
  [1935/3851] LACG   — +1 new rows ✓
  [1936/3851] LAES   — +1 new rows ✓
  [1937/3851] LAKE   — +1 new rows ✓
  [1938/3851] LAMR   — +1 new rows ✓
  [1939/3851] LAND   — +1 new rows ✓
  [1940/3851] LANDO  — +1 new rows ✓
  [1941/3851] LANDP  — +1 new rows ✓
  [1942/3851] LARK   — +1 new rows ✓
  [1943/3851] LASR   — +1 new rows ✓
  [1944/3851] LAUR   — +1 new rows ✓
  [1945/3851] LBGJ   — +1 new rows ✓
  [1946/3851] LBRDA  — +1 new rows ✓
  [1947/3851] LBRDK  — +1 new rows ✓
  [1948/3851] LBRDP  — +1 new rows ✓
  [1949/3851] LBRX   — +1 new rows ✓
  [1950/3851] LBTYA  — +1 new rows ✓

$LBTYB: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['LBTYB']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [1951/3851] LBTYB  — no new data
  [1952/3851] LBTYK  — +1 new rows ✓
  [1953/3851] LCDL   — +1 new rows ✓
  [1954/3851] LCDS   — +1 new rows ✓
  [1955/3851] LCFY   — +1 new rows ✓
  [1956/3851] LCID   — +1 new rows ✓
  [1957/3851] LDEM   — +1 new rows ✓
  [1958/3851] LDRX   — +1 new rows ✓
  [1959/3851] LE     — +1 new rows ✓
  [1960/3851] LECO   — +1 new rows ✓
  [1961/3851] LEDS   — +1 new rows ✓
  [1962/3851] LEE    — +1 new rows ✓
  [1963/3851] LEGH   — +1 new rows ✓
  [1964/3851] LEGN   — +1 new rows ✓
  [1965/3851] LEGR   — +1 new rows ✓
  [1966/3851] LEND   — +1 new rows ✓
  [1967/3851] LENZ   — +1 new rows ✓
  [1968/3851] LESL   — +1 new rows ✓
  [1969/3851] LEXI   — +1 new rows ✓
  [1970/3851] LFMD   — +1 new rows ✓
  [1971/3851] LFMDP  — +1 new rows ✓
  [1972/3851] LFSC   — +1 new rows ✓
  [1973/3851] LFST   — +1 new rows ✓
  [1974/3851] LFTO   — +1 new rows ✓
  [1975/3851] LFUS   — +1 new rows ✓
  [1976/3851] LFVN   — +1 new rows ✓
  [1977/3851] LFWD   — +1 new rows ✓
  [1978/3851] LGCF   — +1 new rows ✓
  [1979/3851] LGCL   — +1 new rows ✓
  [1980/3851] LGHL   — +1 new rows ✓
  [1981/3851] LGIH   — +1 new rows ✓
  [1982/3851] LGN    — +1 new rows ✓
  [1983/3851] LGND   — +1 new rows ✓
  [1984/3851] LGO    — +1 new rows ✓
  [1985/3851] LGRO   — +1 new rows ✓
  [1986/3851] LGVN   — +1 new rows ✓
  [1987/3851] LI     — +1 new rows ✓
  [1988/3851] LIDR   — +1 new rows ✓
  [1989/3851] LIF    — +1 new rows ✓
  [1990/3851] LIFE   — +1 new rows ✓
  [1991/3851] LILA   — +1 new rows ✓
  [1992/3851] LILAK  — +1 new rows ✓
  [1993/3851] LILAP  — +1 new rows ✓
  [1994/3851] LIMN   — +1 new rows ✓
  [1995/3851] LIN    — +1 new rows ✓
  [1996/3851] LINC   — +1 new rows ✓
  [1997/3851] LIND   — +1 new rows ✓
  [1998/3851] LINE   — +1 new rows ✓
  [1999/3851] LINT   — +1 new rows ✓
  [2000/3851] LIQT   — +1 new rows ✓
  [2001/3851] LITE   — +1 new rows ✓
  [2002/3851] LITS   — +1 new rows ✓
  [2003/3851] LIVE   — +1 new rows ✓
  [2004/3851] LIVN   — +1 new rows ✓
  [2005/3851] LIXT   — +1 new rows ✓
  [2006/3851] LKFN   — +1 new rows ✓
  [2007/3851] LKFT   — +1 new rows ✓
  [2008/3851] LKQ    — +1 new rows ✓
  [2009/3851] LLYVA  — +1 new rows ✓
  [2010/3851] LLYVK  — +1 new rows ✓
  [2011/3851] LMAT   — +1 new rows ✓
  [2012/3851] LMB    — +1 new rows ✓
  [2013/3851] LMBS   — +1 new rows ✓
  [2014/3851] LMFA   — +1 new rows ✓
  [2015/3851] LMNR   — +1 new rows ✓
  [2016/3851] LMNX   — +1 new rows ✓
  [2017/3851] LMTL   — +1 new rows ✓
  [2018/3851] LNAI   — +1 new rows ✓
  [2019/3851] LNKS   — +1 new rows ✓
  [2020/3851] LNT    — +1 new rows ✓
  [2021/3851] LNTH   — +1 new rows ✓
  [2022/3851] LNZA   — +1 new rows ✓
  [2023/3851] LOCO   — +1 new rows ✓
  [2024/3851] LOGI   — +1 new rows ✓
  [2025/3851] LOGO   — +1 new rows ✓
  [2026/3851] LONA   — +1 new rows ✓
  [2027/3851] LOPE   — +1 new rows ✓
  [2028/3851] LOTI   — +1 new rows ✓
  [2029/3851] LOVE   — +1 new rows ✓
  [2030/3851] LPCN   — +1 new rows ✓
  [2031/3851] LPLA   — +1 new rows ✓
  [2032/3851] LPRO   — +1 new rows ✓
  [2033/3851] LPSN   — +1 new rows ✓
  [2034/3851] LQ     — +1 new rows ✓
  [2035/3851] LQDA   — +1 new rows ✓
  [2036/3851] LQDT   — +1 new rows ✓
  [2037/3851] LRCX   — +1 new rows ✓
  [2038/3851] LRGE   — +1 new rows ✓
  [2039/3851] LRHC   — +1 new rows ✓
  [2040/3851] LRMR   — +1 new rows ✓
  [2041/3851] LRND   — +1 new rows ✓
  [2042/3851] LSAK   — +1 new rows ✓
  [2043/3851] LSCC   — +1 new rows ✓
  [2044/3851] LSTA   — +1 new rows ✓
  [2045/3851] LSTR   — +1 new rows ✓
  [2046/3851] LTBR   — +1 new rows ✓
  [2047/3851] LTCC   — +1 new rows ✓
  [2048/3851] LTRN   — +1 new rows ✓
  [2049/3851] LUCY   — +1 new rows ✓
  [2050/3851] LULG   — +1 new rows ✓
  [2051/3851] LULU   — +1 new rows ✓
  [2052/3851] LUNG   — +1 new rows ✓
  [2053/3851] LUNR   — +1 new rows ✓
  [2054/3851] LVDS   — +1 new rows ✓
  [2055/3851] LVHD   — +1 new rows ✓
  [2056/3851] LVIG   — +1 new rows ✓
  [2057/3851] LVLU   — +1 new rows ✓
  [2058/3851] LVO    — +1 new rows ✓
  [2059/3851] LWAY   — +1 new rows ✓
  [2060/3851] LXEH   — +1 new rows ✓
  [2061/3851] LXRX   — +1 new rows ✓
  [2062/3851] LYEL   — +1 new rows ✓
  [2063/3851] LYFT   — +1 new rows ✓
  [2064/3851] LYTS   — +1 new rows ✓
  [2065/3851] LZ     — +1 new rows ✓
  [2066/3851] LZMH   — +1 new rows ✓
  [2067/3851] MAAS   — +1 new rows ✓
  [2068/3851] MANH   — +1 new rows ✓
  [2069/3851] MAR    — +1 new rows ✓
  [2070/3851] MARA   — +1 new rows ✓
  [2071/3851] MASK   — +1 new rows ✓
  [2072/3851] MASS   — +1 new rows ✓
  [2073/3851] MAT    — +1 new rows ✓
  [2074/3851] MATE   — +1 new rows ✓
  [2075/3851] MATW   — +1 new rows ✓
  [2076/3851] MAXI   — +1 new rows ✓
  [2077/3851] MAYS   — +1 new rows ✓
  [2078/3851] MAZE   — +1 new rows ✓
  [2079/3851] MBAI   — +1 new rows ✓
  [2080/3851] MBB    — +1 new rows ✓
  [2081/3851] MBIN   — +1 new rows ✓
  [2082/3851] MBINL  — +1 new rows ✓
  [2083/3851] MBINM  — +1 new rows ✓
  [2084/3851] MBINN  — +1 new rows ✓
  [2085/3851] MBIO   — +1 new rows ✓
  [2086/3851] MBLY   — +1 new rows ✓
  [2087/3851] MBNKO  — +1 new rows ✓
  [2088/3851] MBOT   — +1 new rows ✓
  [2089/3851] MBRX   — +1 new rows ✓
  [2090/3851] MBUU   — +1 new rows ✓
  [2091/3851] MBWM   — +1 new rows ✓
  [2092/3851] MBX    — +1 new rows ✓
  [2093/3851] MCBS   — +1 new rows ✓
  [2094/3851] MCDS   — +1 new rows ✓
  [2095/3851] MCFT   — +1 new rows ✓
  [2096/3851] MCHB   — +1 new rows ✓
  [2097/3851] MCHI   — +1 new rows ✓
  [2098/3851] MCHP   — +1 new rows ✓
  [2099/3851] MCHPP  — +1 new rows ✓
  [2100/3851] MCHS   — +1 new rows ✓
  [2101/3851] MCRB   — +1 new rows ✓
  [2102/3851] MCRI   — +1 new rows ✓

$MCTA: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['MCTA']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [2103/3851] MCTA   — no new data
  [2104/3851] MDB    — +1 new rows ✓
  [2105/3851] MDGL   — +1 new rows ✓
  [2106/3851] MDLN   — +1 new rows ✓
  [2107/3851] MDLZ   — +1 new rows ✓
  [2108/3851] MDRR   — +1 new rows ✓
  [2109/3851] MDWD   — +1 new rows ✓
  [2110/3851] MEDP   — +1 new rows ✓
  [2111/3851] MEDX   — +1 new rows ✓
  [2112/3851] MEGL   — +1 new rows ✓
  [2113/3851] MELI   — +1 new rows ✓
  [2114/3851] MEMA   — +1 new rows ✓
  [2115/3851] MEMS   — +1 new rows ✓
  [2116/3851] MENS   — +1 new rows ✓
  [2117/3851] MEOH   — +1 new rows ✓
  [2118/3851] MESO   — +1 new rows ✓
  [2119/3851] META   — +1 new rows ✓
  [2120/3851] METC   — +1 new rows ✓
  [2121/3851] METCB  — +1 new rows ✓
  [2122/3851] METCI  — +1 new rows ✓
  [2123/3851] METCZ  — +1 new rows ✓
  [2124/3851] METD   — +1 new rows ✓
  [2125/3851] METL   — +1 new rows ✓
  [2126/3851] METU   — +1 new rows ✓
  [2127/3851] MFI    — +1 new rows ✓
  [2128/3851] MFICL  — +1 new rows ✓
  [2129/3851] MFIG   — +1 new rows ✓
  [2130/3851] MFMO   — +1 new rows ✓
  [2131/3851] MFVL   — +1 new rows ✓
  [2132/3851] MGEE   — +1 new rows ✓
  [2133/3851] MGNI   — +1 new rows ✓
  [2134/3851] MGNX   — +1 new rows ✓
  [2135/3851] MGPI   — +1 new rows ✓
  [2136/3851] MGRC   — +1 new rows ✓
  [2137/3851] MGRT   — +1 new rows ✓
  [2138/3851] MGRX   — +1 new rows ✓
  [2139/3851] MGTX   — +1 new rows ✓
  [2140/3851] MIDD   — +1 new rows ✓
  [2141/3851] MILN   — +1 new rows ✓
  [2142/3851] MIMI   — +1 new rows ✓
  [2143/3851] MIND   — +1 new rows ✓
  [2144/3851] MIRM   — +1 new rows ✓
  [2145/3851] MIST   — +1 new rows ✓
  [2146/3851] MITK   — +1 new rows ✓
  [2147/3851] MKAM   — +1 new rows ✓
  [2148/3851] MKDW   — +1 new rows ✓
  [2149/3851] MKSI   — +1 new rows ✓
  [2150/3851] MKTW   — +1 new rows ✓
  [2151/3851] MKTX   — +1 new rows ✓
  [2152/3851] MKZR   — +1 new rows ✓
  [2153/3851] MLAB   — +1 new rows ✓
  [2154/3851] MLCIL  — +1 new rows ✓
  [2155/3851] MLCO   — +1 new rows ✓
  [2156/3851] MLEC   — +1 new rows ✓
  [2157/3851] MLGO   — +1 new rows ✓
  [2158/3851] MLKN   — +1 new rows ✓
  [2159/3851] MLTX   — +1 new rows ✓
  [2160/3851] MLYS   — +1 new rows ✓
  [2161/3851] MMLP   — +1 new rows ✓
  [2162/3851] MMSI   — +1 new rows ✓
  [2163/3851] MMYT   — +1 new rows ✓
  [2164/3851] MNDR   — +1 new rows ✓
  [2165/3851] MNDY   — +1 new rows ✓
  [2166/3851] MNKD   — +1 new rows ✓
  [2167/3851] MNPR   — +1 new rows ✓
  [2168/3851] MNRO   — +1 new rows ✓
  [2169/3851] MNSB   — +1 new rows ✓
  [2170/3851] MNSBP  — +1 new rows ✓
  [2171/3851] MNST   — +1 new rows ✓
  [2172/3851] MNTK   — +1 new rows ✓
  [2173/3851] MNTS   — +1 new rows ✓
  [2174/3851] MNVT   — +1 new rows ✓
  [2175/3851] MNZL   — +1 new rows ✓
  [2176/3851] MOBX   — +1 new rows ✓
  [2177/3851] MODD   — +1 new rows ✓
  [2178/3851] MODL   — +1 new rows ✓
  [2179/3851] MOLN   — +1 new rows ✓
  [2180/3851] MOMO   — +1 new rows ✓
  [2181/3851] MOOD   — +1 new rows ✓
  [2182/3851] MORN   — +1 new rows ✓
  [2183/3851] MOVE   — +1 new rows ✓
  [2184/3851] MPAA   — +1 new rows ✓
  [2185/3851] MPB    — +1 new rows ✓
  [2186/3851] MPLT   — +1 new rows ✓
  [2187/3851] MPWR   — +1 new rows ✓
  [2188/3851] MQ     — +1 new rows ✓
  [2189/3851] MQQQ   — +1 new rows ✓
  [2190/3851] MRA    — +1 new rows ✓
  [2191/3851] MRAL   — +1 new rows ✓
  [2192/3851] MRAM   — +1 new rows ✓
  [2193/3851] MRBK   — +1 new rows ✓
  [2194/3851] MRCY   — +1 new rows ✓
  [2195/3851] MRDN   — +1 new rows ✓
  [2196/3851] MRKR   — +1 new rows ✓
  [2197/3851] MRNA   — +1 new rows ✓
  [2198/3851] MRNO   — +1 new rows ✓
  [2199/3851] MRTN   — +1 new rows ✓
  [2200/3851] MRVI   — +1 new rows ✓
  [2201/3851] MRVL   — +1 new rows ✓
  [2202/3851] MRVU   — +1 new rows ✓
  [2203/3851] MRX    — +1 new rows ✓
  [2204/3851] MSAI   — +1 new rows ✓
  [2205/3851] MSBI   — +1 new rows ✓
  [2206/3851] MSBIP  — +1 new rows ✓
  [2207/3851] MSEX   — +1 new rows ✓
  [2208/3851] MSFD   — +1 new rows ✓
  [2209/3851] MSFL   — +1 new rows ✓
  [2210/3851] MSFT   — +1 new rows ✓
  [2211/3851] MSFU   — +1 new rows ✓
  [2212/3851] MSGM   — +1 new rows ✓
  [2213/3851] MSGY   — +1 new rows ✓
  [2214/3851] MSLE   — +1 new rows ✓
  [2215/3851] MSR    — +1 new rows ✓
  [2216/3851] MSS    — +1 new rows ✓
  [2217/3851] MST    — +1 new rows ✓
  [2218/3851] MSTP   — +1 new rows ✓
  [2219/3851] MSTR   — +1 new rows ✓
  [2220/3851] MSTX   — +1 new rows ✓
  [2221/3851] MTC    — +1 new rows ✓
  [2222/3851] MTCH   — +1 new rows ✓
  [2223/3851] MTEN   — +1 new rows ✓
  [2224/3851] MTEX   — +1 new rows ✓
  [2225/3851] MTLS   — +1 new rows ✓
  [2226/3851] MTRX   — +1 new rows ✓
  [2227/3851] MTSI   — +1 new rows ✓
  [2228/3851] MTVA   — +1 new rows ✓
  [2229/3851] MTYY   — +1 new rows ✓
  [2230/3851] MU     — +1 new rows ✓
  [2231/3851] MUD    — +1 new rows ✓
  [2232/3851] MULL   — +1 new rows ✓
  [2233/3851] MULT   — +1 new rows ✓
  [2234/3851] MUU    — +1 new rows ✓
  [2235/3851] MUYY   — +1 new rows ✓
  [2236/3851] MVBF   — +1 new rows ✓
  [2237/3851] MVIS   — +1 new rows ✓
  [2238/3851] MVLL   — +1 new rows ✓
  [2239/3851] MVST   — +1 new rows ✓
  [2240/3851] MWH    — +1 new rows ✓
  [2241/3851] MXL    — +1 new rows ✓
  [2242/3851] MYCF   — +1 new rows ✓
  [2243/3851] MYCG   — +1 new rows ✓
  [2244/3851] MYCH   — +1 new rows ✓
  [2245/3851] MYCI   — +1 new rows ✓
  [2246/3851] MYCJ   — +1 new rows ✓
  [2247/3851] MYCK   — +1 new rows ✓
  [2248/3851] MYCL   — +1 new rows ✓
  [2249/3851] MYCM   — +1 new rows ✓
  [2250/3851] MYCN   — +1 new rows ✓
  [2251/3851] MYCO   — +1 new rows ✓
  [2252/3851] MYFW   — +1 new rows ✓
  [2253/3851] MYGN   — +1 new rows ✓
  [2254/3851] MYHA   — +1 new rows ✓
  [2255/3851] MYHB   — +1 new rows ✓
  [2256/3851] MYHC   — +1 new rows ✓
  [2257/3851] MYHD   — +1 new rows ✓
  [2258/3851] MYHE   — +1 new rows ✓
  [2259/3851] MYMF   — +1 new rows ✓
  [2260/3851] MYMG   — +1 new rows ✓
  [2261/3851] MYMH   — +1 new rows ✓
  [2262/3851] MYMI   — +1 new rows ✓
  [2263/3851] MYMJ   — +1 new rows ✓
  [2264/3851] MYMK   — +1 new rows ✓
  [2265/3851] MYRG   — +1 new rows ✓
  [2266/3851] MYSE   — +1 new rows ✓
  [2267/3851] MYSZ   — +1 new rows ✓
  [2268/3851] MZTI   — +1 new rows ✓
  [2270/3851] NAAS   — +1 new rows ✓
  [2271/3851] NAKA   — +1 new rows ✓
  [2272/3851] NAMM   — +1 new rows ✓
  [2273/3851] NAMS   — +1 new rows ✓
  [2274/3851] NAMSW  — +1 new rows ✓
  [2275/3851] NATH   — +1 new rows ✓
  [2276/3851] NATO   — +1 new rows ✓
  [2277/3851] NATR   — +1 new rows ✓
  [2278/3851] NAUT   — +1 new rows ✓
  [2279/3851] NAVN   — +1 new rows ✓
  [2280/3851] NBBK   — +1 new rows ✓
  [2281/3851] NBIG   — +1 new rows ✓
  [2282/3851] NBIL   — +1 new rows ✓
  [2283/3851] NBIS   — +1 new rows ✓
  [2284/3851] NBIX   — +1 new rows ✓
  [2285/3851] NBN    — +1 new rows ✓
  [2286/3851] NBP    — +1 new rows ✓
  [2287/3851] NBTB   — +1 new rows ✓
  [2288/3851] NBTX   — +1 new rows ✓
  [2289/3851] NCEL   — +1 new rows ✓
  [2290/3851] NCEW   — +1 new rows ✓
  [2291/3851] NCI    — +1 new rows ✓
  [2292/3851] NCIQ   — +1 new rows ✓
  [2293/3851] NCMI   — +1 new rows ✓
  [2294/3851] NCNA   — +1 new rows ✓
  [2295/3851] NCNO   — +1 new rows ✓
  [2296/3851] NCPB   — +1 new rows ✓
  [2297/3851] NCPL   — +1 new rows ✓
  [2298/3851] NCSM   — +1 new rows ✓
  [2299/3851] NCT    — +1 new rows ✓
  [2300/3851] NCTY   — +1 new rows ✓
  [2301/3851] NDAA   — +1 new rows ✓
  [2302/3851] NDAQ   — +1 new rows ✓
  [2303/3851] NDLS   — +1 new rows ✓
  [2304/3851] NDRA   — +1 new rows ✓
  [2305/3851] NDSN   — +1 new rows ✓
  [2306/3851] NECB   — +1 new rows ✓
  [2307/3851] NEGG   — +1 new rows ✓
  [2308/3851] NEMG   — +1 new rows ✓
  [2309/3851] NEO    — +1 new rows ✓
  [2310/3851] NEOG   — +1 new rows ✓
  [2311/3851] NEON   — +1 new rows ✓
  [2312/3851] NEPH   — +1 new rows ✓
  [2313/3851] NERV   — +1 new rows ✓
  [2314/3851] NESR   — +1 new rows ✓
  [2315/3851] NEUP   — +1 new rows ✓
  [2316/3851] NEWT   — +1 new rows ✓
  [2317/3851] NEWTG  — +1 new rows ✓
  [2318/3851] NEWTH  — +1 new rows ✓
  [2319/3851] NEWTI  — +1 new rows ✓
  [2320/3851] NEWTO  — +1 new rows ✓
  [2321/3851] NEWTP  — +1 new rows ✓
  [2322/3851] NEWZ   — +1 new rows ✓
  [2323/3851] NEXM   — +1 new rows ✓
  [2324/3851] NEXN   — +1 new rows ✓
  [2325/3851] NEXR   — +1 new rows ✓
  [2326/3851] NFE    — +1 new rows ✓
  [2327/3851] NFLX   — +1 new rows ✓
  [2328/3851] NFRX   — +1 new rows ✓
  [2329/3851] NFTY   — +1 new rows ✓
  [2330/3851] NFXL   — +1 new rows ✓
  [2331/3851] NFXS   — +1 new rows ✓
  [2332/3851] NGHT   — +1 new rows ✓
  [2333/3851] NGNE   — +1 new rows ✓
  [2334/3851] NHPAP  — +1 new rows ✓
  [2335/3851] NHPBP  — +1 new rows ✓
  [2336/3851] NICE   — +1 new rows ✓
  [2337/3851] NIKL   — +1 new rows ✓
  [2338/3851] NIOG   — +1 new rows ✓
  [2339/3851] NIU    — +1 new rows ✓
  [2340/3851] NIVF   — +1 new rows ✓
  [2341/3851] NIXT   — +1 new rows ✓
  [2342/3851] NIXX   — +1 new rows ✓
  [2343/3851] NKSH   — +1 new rows ✓
  [2344/3851] NKTR   — +1 new rows ✓
  [2345/3851] NKTX   — +1 new rows ✓
  [2346/3851] NMFCZ  — +1 new rows ✓
  [2347/3851] NMIH   — +1 new rows ✓
  [2348/3851] NMTC   — +1 new rows ✓
  [2349/3851] NN     — +1 new rows ✓
  [2350/3851] NNBR   — +1 new rows ✓
  [2351/3851] NNDM   — +1 new rows ✓
  [2352/3851] NNE    — +1 new rows ✓
  [2353/3851] NNNN   — +1 new rows ✓
  [2354/3851] NNOX   — +1 new rows ✓
  [2355/3851] NODK   — +1 new rows ✓
  [2356/3851] NOVT   — +1 new rows ✓
  [2357/3851] NOVTU  — +1 new rows ✓
  [2358/3851] NOWL   — +1 new rows ✓
  [2359/3851] NPCE   — +1 new rows ✓
  [2360/3851] NPFI   — +1 new rows ✓
  [2361/3851] NPT    — +1 new rows ✓
  [2362/3851] NRC    — +1 new rows ✓
  [2363/3851] NRDS   — +1 new rows ✓
  [2364/3851] NRES   — +1 new rows ✓
  [2365/3851] NRIM   — +1 new rows ✓
  [2366/3851] NRIX   — +1 new rows ✓
  [2367/3851] NRXP   — +1 new rows ✓
  [2368/3851] NSI    — +1 new rows ✓
  [2369/3851] NSIT   — +1 new rows ✓
  [2370/3851] NSPR   — +1 new rows ✓
  [2371/3851] NSSC   — +1 new rows ✓
  [2372/3851] NTAP   — +1 new rows ✓
  [2373/3851] NTCL   — +1 new rows ✓
  [2374/3851] NTCT   — +1 new rows ✓
  [2375/3851] NTES   — +1 new rows ✓
  [2376/3851] NTGR   — +1 new rows ✓
  [2377/3851] NTLA   — +1 new rows ✓
  [2378/3851] NTNX   — +1 new rows ✓
  [2379/3851] NTRA   — +1 new rows ✓
  [2380/3851] NTRP   — +1 new rows ✓
  [2381/3851] NTRS   — +1 new rows ✓
  [2382/3851] NTRSO  — +1 new rows ✓
  [2383/3851] NTSK   — +1 new rows ✓
  [2384/3851] NTWK   — +1 new rows ✓
  [2385/3851] NUG    — +1 new rows ✓
  [2386/3851] NUIF   — +1 new rows ✓
  [2387/3851] NUSB   — +1 new rows ✓
  [2388/3851] NUTX   — +1 new rows ✓
  [2389/3851] NUVL   — +1 new rows ✓
  [2390/3851] NUWE   — +1 new rows ✓
  [2391/3851] NVAX   — +1 new rows ✓
  [2392/3851] NVCR   — +1 new rows ✓
  [2393/3851] NVCT   — +1 new rows ✓
  [2394/3851] NVD    — +1 new rows ✓
  [2395/3851] NVDA   — +1 new rows ✓
  [2396/3851] NVDD   — +1 new rows ✓
  [2397/3851] NVDG   — +1 new rows ✓
  [2398/3851] NVDL   — +1 new rows ✓
  [2399/3851] NVDS   — +1 new rows ✓
  [2400/3851] NVDU   — +1 new rows ✓
  [2401/3851] NVEC   — +1 new rows ✓
  [2402/3851] NVMI   — +1 new rows ✓
  [2403/3851] NVNI   — +1 new rows ✓
  [2404/3851] NVNO   — +1 new rows ✓
  [2405/3851] NVPS   — +1 new rows ✓
  [2406/3851] NVTS   — +1 new rows ✓
  [2407/3851] NVVE   — +1 new rows ✓
  [2408/3851] NVX    — +1 new rows ✓
  [2409/3851] NWE    — +1 new rows ✓
  [2410/3851] NWFL   — +1 new rows ✓
  [2411/3851] NWL    — +1 new rows ✓
  [2412/3851] NWPX   — +1 new rows ✓
  [2413/3851] NWS    — +1 new rows ✓
  [2414/3851] NWSA   — +1 new rows ✓
  [2415/3851] NWTG   — +1 new rows ✓
  [2416/3851] NXPI   — +1 new rows ✓
  [2417/3851] NXPL   — +1 new rows ✓
  [2418/3851] NXST   — +1 new rows ✓
  [2419/3851] NXT    — +1 new rows ✓
  [2420/3851] NXTC   — +1 new rows ✓
  [2421/3851] NXTG   — +1 new rows ✓
  [2422/3851] NXTS   — +1 new rows ✓
  [2423/3851] NXTT   — +1 new rows ✓
  [2424/3851] NXXT   — +1 new rows ✓
  [2425/3851] NYAX   — +1 new rows ✓
  [2426/3851] NYXH   — +1 new rows ✓
  [2427/3851] NZAC   — +1 new rows ✓
  [2428/3851] OBAI   — +1 new rows ✓
  [2429/3851] OBIL   — +1 new rows ✓
  [2430/3851] OBIO   — +1 new rows ✓
  [2431/3851] OBT    — +1 new rows ✓
  [2432/3851] OBTC   — +1 new rows ✓
  [2433/3851] OCC    — +1 new rows ✓
  [2434/3851] OCCIM  — +1 new rows ✓
  [2435/3851] OCCIN  — +1 new rows ✓
  [2436/3851] OCFC   — +1 new rows ✓
  [2437/3851] OCG    — +1 new rows ✓
  [2438/3851] OCGN   — +1 new rows ✓
  [2439/3851] OCS    — +1 new rows ✓
  [2440/3851] OCTV   — +1 new rows ✓
  [2441/3851] OCUL   — +1 new rows ✓
  [2442/3851] ODD    — +1 new rows ✓
  [2443/3851] ODDS   — +1 new rows ✓
  [2444/3851] ODFL   — +1 new rows ✓
  [2445/3851] ODTE   — +1 new rows ✓
  [2446/3851] OESX   — +1 new rows ✓
  [2447/3851] OFIX   — +1 new rows ✓
  [2448/3851] OFLX   — +1 new rows ✓
  [2449/3851] OFSSH  — +1 new rows ✓
  [2450/3851] OFSSO  — +1 new rows ✓
  [2451/3851] OGI    — +1 new rows ✓
  [2452/3851] OIO    — +1 new rows ✓
  [2453/3851] OKLL   — +1 new rows ✓
  [2454/3851] OKTA   — +1 new rows ✓
  [2455/3851] OKTG   — +1 new rows ✓
  [2456/3851] OKUR   — +1 new rows ✓
  [2457/3851] OLB    — +1 new rows ✓
  [2458/3851] OLED   — +1 new rows ✓
  [2459/3851] OLLI   — +1 new rows ✓
  [2460/3851] OLMA   — +1 new rows ✓
  [2461/3851] OLOX   — +1 new rows ✓
  [2462/3851] OLPX   — +1 new rows ✓
  [2463/3851] OM     — +1 new rows ✓
  [2464/3851] OMAB   — +1 new rows ✓
  [2465/3851] OMCL   — +1 new rows ✓
  [2466/3851] OMDA   — +1 new rows ✓
  [2467/3851] OMER   — +1 new rows ✓
  [2468/3851] OMEX   — +1 new rows ✓
  [2469/3851] OMH    — +1 new rows ✓
  [2470/3851] ON     — +1 new rows ✓
  [2471/3851] ONB    — +1 new rows ✓
  [2472/3851] ONBPO  — +1 new rows ✓
  [2473/3851] ONBPP  — +1 new rows ✓
  [2474/3851] ONC    — +1 new rows ✓
  [2475/3851] ONCO   — +1 new rows ✓
  [2476/3851] ONCY   — +1 new rows ✓
  [2477/3851] ONEQ   — +1 new rows ✓
  [2478/3851] ONEW   — +1 new rows ✓
  [2479/3851] OPCH   — +1 new rows ✓
  [2480/3851] OPEN   — +1 new rows ✓
  [2481/3851] OPI    — +1 new rows ✓
  [2482/3851] OPPJ   — +1 new rows ✓
  [2483/3851] OPRA   — +1 new rows ✓
  [2484/3851] OPRT   — +1 new rows ✓
  [2485/3851] OPRX   — +1 new rows ✓
  [2486/3851] OPTZ   — +1 new rows ✓
  [2487/3851] OPXS   — +1 new rows ✓
  [2488/3851] ORBS   — +1 new rows ✓
  [2489/3851] ORBX   — +1 new rows ✓
  [2490/3851] ORCS   — +1 new rows ✓
  [2491/3851] ORCU   — +1 new rows ✓
  [2492/3851] ORCX   — +1 new rows ✓
  [2493/3851] ORGN   — +1 new rows ✓
  [2494/3851] ORGO   — +1 new rows ✓
  [2495/3851] ORIC   — +1 new rows ✓
  [2496/3851] ORIO   — +1 new rows ✓
  [2497/3851] ORKA   — +1 new rows ✓
  [2498/3851] ORKT   — +1 new rows ✓
  [2499/3851] ORLY   — +1 new rows ✓
  [2500/3851] ORMP   — +1 new rows ✓
  [2501/3851] ORR    — +1 new rows ✓
  [2502/3851] ORRF   — +1 new rows ✓
  [2503/3851] OSBC   — +1 new rows ✓
  [2504/3851] OSCG   — +1 new rows ✓
  [2505/3851] OSCX   — +1 new rows ✓
  [2506/3851] OSIS   — +1 new rows ✓
  [2507/3851] OSPN   — +1 new rows ✓
  [2508/3851] OST    — +1 new rows ✓
  [2509/3851] OSUR   — +1 new rows ✓
  [2510/3851] OSW    — +1 new rows ✓
  [2511/3851] OTEX   — +1 new rows ✓
  [2512/3851] OTLK   — +1 new rows ✓
  [2513/3851] OTLY   — +1 new rows ✓
  [2514/3851] OTTR   — +1 new rows ✓
  [2515/3851] OUST   — +1 new rows ✓
  [2516/3851] OVBC   — +1 new rows ✓
  [2517/3851] OVLY   — +1 new rows ✓
  [2518/3851] OWLS   — +1 new rows ✓
  [2519/3851] OXLCG  — +1 new rows ✓
  [2520/3851] OXLCI  — +1 new rows ✓
  [2521/3851] OXLCL  — +1 new rows ✓
  [2522/3851] OXLCM  — +1 new rows ✓
  [2523/3851] OXLCN  — +1 new rows ✓
  [2524/3851] OXLCO  — +1 new rows ✓
  [2525/3851] OXLCZ  — +1 new rows ✓
  [2526/3851] OXSQG  — +1 new rows ✓
  [2527/3851] OXSQH  — +1 new rows ✓
  [2528/3851] OZEM   — +1 new rows ✓
  [2529/3851] OZK    — +1 new rows ✓
  [2530/3851] PAA    — +1 new rows ✓
  [2531/3851] PABD   — +1 new rows ✓
  [2532/3851] PABU   — +1 new rows ✓
  [2533/3851] PACB   — +1 new rows ✓
  [2534/3851] PAGP   — +1 new rows ✓
  [2535/3851] PAHC   — +1 new rows ✓
  [2536/3851] PAL    — +1 new rows ✓
  [2537/3851] PALD   — +1 new rows ✓
  [2538/3851] PALI   — +1 new rows ✓
  [2539/3851] PALU   — +1 new rows ✓
  [2540/3851] PAMT   — +1 new rows ✓
  [2541/3851] PANG   — +1 new rows ✓
  [2542/3851] PANW   — +1 new rows ✓
  [2543/3851] PARK   — +1 new rows ✓
  [2544/3851] PASG   — +1 new rows ✓
  [2545/3851] PATK   — +1 new rows ✓
  [2546/3851] PATN   — +1 new rows ✓
  [2547/3851] PAVM   — +1 new rows ✓
  [2548/3851] PAVS   — +1 new rows ✓
  [2549/3851] PAYP   — +1 new rows ✓
  [2550/3851] PAYX   — +1 new rows ✓
  [2551/3851] PBEU   — +1 new rows ✓
  [2552/3851] PBLS   — +1 new rows ✓
  [2553/3851] PBM    — +1 new rows ✓
  [2554/3851] PBOG   — +1 new rows ✓
  [2555/3851] PBPH   — +1 new rows ✓
  [2556/3851] PBQQ   — +1 new rows ✓
  [2557/3851] PBRG   — +1 new rows ✓
  [2558/3851] PBSC   — +1 new rows ✓
  [2559/3851] PBYI   — +1 new rows ✓
  [2560/3851] PC     — +1 new rows ✓
  [2561/3851] PCAR   — +1 new rows ✓
  [2562/3851] PCB    — +1 new rows ✓
  [2563/3851] PCLA   — +1 new rows ✓
  [2564/3851] PCMM   — +1 new rows ✓
  [2565/3851] PCPI   — +1 new rows ✓
  [2566/3851] PCRX   — +1 new rows ✓
  [2567/3851] PCSA   — +1 new rows ✓
  [2568/3851] PCT    — +1 new rows ✓
  [2569/3851] PCTTU  — +1 new rows ✓
  [2570/3851] PCTY   — +1 new rows ✓
  [2571/3851] PCVX   — +1 new rows ✓
  [2572/3851] PDBA   — +1 new rows ✓
  [2573/3851] PDD    — +1 new rows ✓
  [2574/3851] PDDL   — +1 new rows ✓
  [2575/3851] PDEX   — +1 new rows ✓
  [2576/3851] PDFS   — +1 new rows ✓
  [2577/3851] PDP    — +1 new rows ✓
  [2578/3851] PDSB   — +1 new rows ✓
  [2579/3851] PDYN   — +1 new rows ✓
  [2580/3851] PEBK   — +1 new rows ✓
  [2581/3851] PEBO   — +1 new rows ✓
  [2582/3851] PECO   — +1 new rows ✓
  [2583/3851] PEGA   — +1 new rows ✓
  [2584/3851] PENG   — +1 new rows ✓
  [2585/3851] PENN   — +1 new rows ✓
  [2586/3851] PEP    — +1 new rows ✓
  [2587/3851] PEPS   — +1 new rows ✓
  [2588/3851] PERI   — +1 new rows ✓
  [2589/3851] PETS   — +1 new rows ✓
  [2590/3851] PETZ   — +1 new rows ✓
  [2591/3851] PEY    — +1 new rows ✓
  [2592/3851] PEZ    — +1 new rows ✓
  [2593/3851] PFBC   — +1 new rows ✓
  [2594/3851] PFDE   — +1 new rows ✓
  [2595/3851] PFF    — +1 new rows ✓
  [2596/3851] PFG    — +1 new rows ✓
  [2597/3851] PFI    — +1 new rows ✓
  [2598/3851] PFIS   — +1 new rows ✓
  [2599/3851] PFM    — +1 new rows ✓
  [2600/3851] PFOE   — +1 new rows ✓
  [2601/3851] PFSA   — +1 new rows ✓
  [2602/3851] PFX    — +1 new rows ✓
  [2603/3851] PFXNZ  — +1 new rows ✓
  [2604/3851] PGC    — +1 new rows ✓
  [2605/3851] PGEN   — +1 new rows ✓
  [2606/3851] PGJ    — +1 new rows ✓
  [2607/3851] PGNY   — +1 new rows ✓
  [2608/3851] PGY    — +1 new rows ✓
  [2609/3851] PHAR   — +1 new rows ✓
  [2610/3851] PHAT   — +1 new rows ✓
  [2611/3851] PHIO   — +1 new rows ✓
  [2612/3851] PHO    — +1 new rows ✓
  [2613/3851] PHOE   — +1 new rows ✓
  [2614/3851] PHUN   — +1 new rows ✓
  [2615/3851] PHVS   — +1 new rows ✓
  [2616/3851] PI     — +1 new rows ✓
  [2617/3851] PID    — +1 new rows ✓
  [2618/3851] PIE    — +1 new rows ✓
  [2619/3851] PIII   — +1 new rows ✓
  [2620/3851] PIO    — +1 new rows ✓
  [2621/3851] PIZ    — +1 new rows ✓
  [2622/3851] PKBK   — +1 new rows ✓
  [2623/3851] PKOH   — +1 new rows ✓
  [2624/3851] PKW    — +1 new rows ✓
  [2625/3851] PLA    — +1 new rows ✓
  [2626/3851] PLAB   — +1 new rows ✓
  [2627/3851] PLAY   — +1 new rows ✓
  [2628/3851] PLBC   — +1 new rows ✓
  [2629/3851] PLBY   — +1 new rows ✓
  [2630/3851] PLCE   — +1 new rows ✓
  [2631/3851] PLMR   — +1 new rows ✓
  [2632/3851] PLPC   — +1 new rows ✓
  [2633/3851] PLRX   — +1 new rows ✓
  [2634/3851] PLRZ   — +1 new rows ✓
  [2635/3851] PLSE   — +1 new rows ✓
  [2636/3851] PLTD   — +1 new rows ✓
  [2637/3851] PLTG   — +1 new rows ✓
  [2638/3851] PLTK   — +1 new rows ✓
  [2639/3851] PLTR   — +1 new rows ✓
  [2640/3851] PLTU   — +1 new rows ✓
  [2641/3851] PLTZ   — +1 new rows ✓
  [2642/3851] PLUG   — +1 new rows ✓
  [2643/3851] PLUL   — +1 new rows ✓

$RDIB: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

1 Failed download:
['RDIB']: possibly delisted; no price data found  (1d 2026-06-27 -> 2026-06-28)

  [2861/3851] RDIB   — no new data
  [2862/3851] RDNT   — +1 new rows ✓
  [2863/3851] RDNW   — +1 new rows ✓
  [2864/3851] RDTL   — +1 new rows ✓
  [2865/3851] RDTY   — +1 new rows ✓
  [2866/3851] RDVT   — +1 new rows ✓
  [2867/3851] RDVY   — +1 new rows ✓
  [2868/3851] RDWR   — +1 new rows ✓
  [2869/3851] REAI   — +1 new rows ✓
  [2870/3851] REAL   — +1 new rows ✓
  [2871/3851] REBN   — +1 new rows ✓
  [2872/3851] REE    — +1 new rows ✓
  [2873/3851] REG    — +1 new rows ✓
  [2874/3851] REGCO  — +1 new rows ✓
  [2875/3851] REGCP  — +1 new rows ✓
  [2876/3851] REGN   — +1 new rows ✓
  [2877/3851] REIT   — +1 new rows ✓
  [2878/3851] REKR   — +1 new rows ✓
  [2879/3851] RELL   — +1 new rows ✓
  [2880/3851] RELY   — +1 new rows ✓
  [2881/3851] REMG   — +1 new rows ✓
  [2882/3851] RENT   — +1 new rows ✓
  [2883/3851] RENX   — +1 new rows ✓
  [2884/3851] REPL   — +1 new rows ✓
  [2885/3851] RETO   — +1 new rows ✓
  [2886/3851] REVB   — +1 new rows ✓
  [2887/3851] REXC   — +1 new rows ✓
  [2888/3851] REYN   — +1 new rows ✓
  [2889/3851] RFDI   — +1 new rows ✓
  [2890/3851] RFEM   — +1 new rows ✓
  [2891/3851] RFIL   — +1 new rows ✓
  [2892/3851] RGC    — +1 new rows ✓
  [2893/3851] RGCO   — +1 new rows ✓
  [2894/3851] RGEN   — +1 new rows ✓
  [2895/3851] RGLD   — +1 new rows ✓
  [2896/3851] RGLO   — +1 new rows ✓
  [2897/3851] RGNX   — +1 new rows ✓
  [2898/3851] RGS    — +1 new rows ✓
  [2899/3851] RGTI   — +1 new rows ✓
  [2900/3851] RGTX   — +1 new rows ✓
  [2901/3851] RGTZ   — +1 new rows ✓
  [2902/3851] RICK   — +1 new rows ✓
  [2903/3851] RIFR   — +1 new rows ✓
  [2904/3851] RIGL   — +1 new rows ✓
  [2905/3851] RILY   — +1 new rows ✓
  [2906/3851] RILYG  — +1 new rows ✓
  [2907/3851] RILYL  — +1 new rows ✓
  [2908/3851] RILYN  — +1 new rows ✓
  [2909/3851] RILYP  — +1 new rows ✓
  [2910/3851] RILYT  — +1 new rows ✓
  [2911/3851] RILYZ  — +1 new rows ✓
  [2912/3851] RIME   — +1 new rows ✓
  [2913/3851] RING   — +1 new rows ✓
  [2914/3851] RINT   — +1 new rows ✓
  [2915/3851] RIOT   — +1 new rows ✓
  [2916/3851] RIVN   — +1 new rows ✓
  [2917/3851] RJET   — +1 new rows ✓
  [2918/3851] RKDA   — +1 new rows ✓
  [2919/3851] RKLB   — +1 new rows ✓
  [2920/3851] RKLX   — +1 new rows ✓
  [2921/3851] RKLZ   — +1 new rows ✓
  [2922/3851] RKNG   — +1 new rows ✓
  [2923/3851] RKTO   — +1 new rows ✓
  [2924/3851] RLAY   — +1 new rows ✓
  [2925/3851] RLMD   — +1 new rows ✓
  [2926/3851] RLYB   — +1 new rows ✓
  [2927/3851] RMBS   — +1 new rows ✓
  [2928/3851] RMIX   — +1 new rows ✓
  [2929/3851] RMR    — +1 new rows ✓
  [2930/3851] RMSG   — +1 new rows ✓
  [2931/3851] RMTI   — +1 new rows ✓
  [2932/3851] RNAC   — +1 new rows ✓
  [2933/3851] RNAZ   — +1 new rows ✓
  [2934/3851] RNEM   — +1 new rows ✓
  [2935/3851] RNIN   — +1 new rows ✓
  [2936/3851] RNRG   — +1 new rows ✓
  [2937/3851] RNTX   — +1 new rows ✓
  [2938/3851] ROAD   — +1 new rows ✓
  [2939/3851] ROBT   — +1 new rows ✓
  [2940/3851] ROCK   — +1 new rows ✓
  [2941/3851] ROCQ   — +1 new rows ✓
  [2942/3851] ROCY   — +1 new rows ✓
  [2943/3851] ROE    — +1 new rows ✓
  [2944/3851] ROIV   — +1 new rows ✓
  [2945/3851] ROKU   — +1 new rows ✓
  [2946/3851] ROOT   — +1 new rows ✓
  [2947/3851] ROP    — +1 new rows ✓
  [2948/3851] ROST   — +1 new rows ✓
  [2949/3851] RPAY   — +1 new rows ✓
  [2950/3851] RPD    — +1 new rows ✓
  [2951/3851] RPGL   — +1 new rows ✓
  [2952/3851] RPID   — +1 new rows ✓
  [2953/3851] RPRX   — +1 new rows ✓
  [2954/3851] RRBI   — +1 new rows ✓
  [2955/3851] RRGB   — +1 new rows ✓
  [2956/3851] RRR    — +1 new rows ✓
  [2957/3851] RTB    — +1 new rows ✓
  [2958/3851] RTH    — +1 new rows ✓
  [2959/3851] RTXG   — +1 new rows ✓
  [2960/3851] RUBI   — +1 new rows ✓
  [2961/3851] RUN    — +1 new rows ✓
  [2962/3851] RUNN   — +1 new rows ✓
  [2963/3851] RUSC   — +1 new rows ✓
  [2964/3851] RUSHA  — +1 new rows ✓
  [2965/3851] RUSHB  — +1 new rows ✓
  [2966/3851] RVMD   — +1 new rows ✓
  [2967/3851] RVNL   — +1 new rows ✓
  [2968/3851] RVSN   — +1 new rows ✓
  [2969/3851] RWAYI  — +1 new rows ✓
  [2970/3851] RWAYL  — +1 new rows ✓
  [2971/3851] RWIN   — +1 new rows ✓
  [2972/3851] RXRX   — +1 new rows ✓
  [2973/3851] RXST   — +1 new rows ✓
  [2974/3851] RXT    — +1 new rows ✓
  [2975/3851] RYAAY  — +1 new rows ✓
  [2976/3851] RYET   — +1 new rows ✓
  [2977/3851] RYM    — +1 new rows ✓
  [2978/3851] RYTM   — +1 new rows ✓
  [2979/3851] RZLT   — +1 new rows ✓
  [2980/3851] SABR   — +1 new rows ✓
  [2981/3851] SABS   — +1 new rows ✓
  [2982/3851] SAFT   — +1 new rows ✓
  [2983/3851] SAFX   — +1 new rows ✓
  [2984/3851] SAIA   — +1 new rows ✓
  [2985/3851] SAIC   — +1 new rows ✓
  [2986/3851] SAIH   — +1 new rows ✓
  [2987/3851] SAIL   — +1 new rows ✓
  [2988/3851] SANA   — +1 new rows ✓
  [2989/3851] SANG   — +1 new rows ✓
  [2990/3851] SANM   — +1 new rows ✓
  [2991/3851] SARK   — +1 new rows ✓
  [2992/3851] SATA   — +1 new rows ✓
  [2993/3851] SATG   — +1 new rows ✓
  [2994/3851] SBAC   — +1 new rows ✓
  [2995/3851] SBCF   — +1 new rows ✓
  [2996/3851] SBET   — +1 new rows ✓
  [2997/3851] SBFG   — +1 new rows ✓
  [2998/3851] SBFM   — +1 new rows ✓
  [2999/3851] SBGI   — +1 new rows ✓
  [3000/3851] SBLK   — +1 new rows ✓
  [3001/3851] SBRA   — +1 new rows ✓
  [3002/3851] SBU    — +1 new rows ✓
  [3003/3851] SBUX   — +1 new rows ✓
  [3004/3851] SCA    — +1 new rows ✓
  [3005/3851] SCDS   — +1 new rows ✓
  [3006/3851] SCHL   — +1 new rows ✓
  [3007/3851] SCKT   — +1 new rows ✓
  [3008/3851] SCLX   — +1 new rows ✓
  [3009/3851] SCNI   — +1 new rows ✓
  [3010/3851] SCNX   — +1 new rows ✓
  [3011/3851] SCOR   — +1 new rows ✓
  [3012/3851] SCSC   — +1 new rows ✓
  [3013/3851] SCWO   — +1 new rows ✓
  [3014/3851] SCYX   — +1 new rows ✓
  [3015/3851] SCZ    — +1 new rows ✓
  [3016/3851] SDA    — +1 new rows ✓
  [3017/3851] SDG    — +1 new rows ✓
  [3018/3851] SDGR   — +1 new rows ✓
  [3019/3851] SDOT   — +1 new rows ✓
  [3020/3851] SDSI   — +1 new rows ✓
  [3021/3851] SDST   — +1 new rows ✓
  [3022/3851] SDTY   — +1 new rows ✓
  [3023/3851] SDVY   — +1 new rows ✓
  [3024/3851] SEAT   — +1 new rows ✓
  [3025/3851] SEDG   — +1 new rows ✓
  [3026/3851] SEED   — +1 new rows ✓
  [3027/3851] SEEM   — +1 new rows ✓
  [3028/3851] SEER   — +1 new rows ✓
  [3029/3851] SEGG   — +1 new rows ✓
  [3030/3851] SEIC   — +1 new rows ✓
  [3031/3851] SEIE   — +1 new rows ✓
  [3032/3851] SEIS   — +1 new rows ✓
  [3033/3851] SENEA  — +1 new rows ✓
  [3034/3851] SENEB  — +1 new rows ✓
  [3035/3851] SENS   — +1 new rows ✓
  [3036/3851] SEPN   — +1 new rows ✓
  [3037/3851] SERV   — +1 new rows ✓
  [3038/3851] SETM   — +1 new rows ✓
  [3039/3851] SEZL   — +1 new rows ✓
  [3040/3851] SFBC   — +1 new rows ✓
  [3041/3851] SFD    — +1 new rows ✓
  [3042/3851] SFHG   — +1 new rows ✓
  [3043/3851] SFIX   — +1 new rows ✓
  [3044/3851] SFLO   — +1 new rows ✓
  [3045/3851] SFM    — +1 new rows ✓
  [3046/3851] SFNC   — +1 new rows ✓
  [3047/3851] SFST   — +1 new rows ✓
  [3048/3851] SGA    — +1 new rows ✓
  [3049/3851] SGC    — +1 new rows ✓
  [3050/3851] SGHT   — +1 new rows ✓
  [3051/3851] SGLY   — +1 new rows ✓
  [3052/3851] SGML   — +1 new rows ✓
  [3053/3851] SGP    — +1 new rows ✓
  [3054/3851] SGRY   — +1 new rows ✓
  [3055/3851] SGVA   — +1 new rows ✓
  [3056/3851] SHAZ   — +1 new rows ✓
  [3057/3851] SHBI   — +1 new rows ✓
  [3058/3851] SHC    — +1 new rows ✓
  [3059/3851] SHEN   — +1 new rows ✓
  [3060/3851] SHFS   — +1 new rows ✓
  [3061/3851] SHIP   — +1 new rows ✓
  [3062/3851] SHLS   — +1 new rows ✓
  [3063/3851] SHOE   — +1 new rows ✓
  [3064/3851] SHOO   — +1 new rows ✓
  [3065/3851] SHOP   — +1 new rows ✓
  [3066/3851] SHPH   — +1 new rows ✓
  [3067/3851] SHPU   — +1 new rows ✓
  [3068/3851] SHRY   — +1 new rows ✓
  [3069/3851] SHY    — +1 new rows ✓
  [3070/3851] SIBN   — +1 new rows ✓
  [3071/3851] SIDU   — +1 new rows ✓
  [3072/3851] SIEB   — +1 new rows ✓
  [3073/3851] SIFY   — +1 new rows ✓
  [3074/3851] SIGI   — +1 new rows ✓
  [3075/3851] SILC   — +1 new rows ✓
  [3076/3851] SILO   — +1 new rows ✓
  [3077/3851] SIMO   — +1 new rows ✓
  [3078/3851] SINT   — +1 new rows ✓
  [3079/3851] SION   — +1 new rows ✓
  [3080/3851] SIRI   — +1 new rows ✓
  [3081/3851] SITM   — +1 new rows ✓
  [3082/3851] SJCP   — +1 new rows ✓
  [3083/3851] SJLD   — +1 new rows ✓
  [3084/3851] SKIN   — +1 new rows ✓
  [3085/3851] SKK    — +1 new rows ✓
  [3086/3851] SKOR   — +1 new rows ✓
  [3087/3851] SKRE   — +1 new rows ✓
  [3088/3851] SKWD   — +1 new rows ✓
  [3089/3851] SKYA   — +1 new rows ✓
  [3090/3851] SKYE   — +1 new rows ✓
  [3091/3851] SKYQ   — +1 new rows ✓
  [3092/3851] SKYT   — +1 new rows ✓
  [3093/3851] SKYU   — +1 new rows ✓
  [3094/3851] SKYW   — +1 new rows ✓
  [3095/3851] SKYY   — +1 new rows ✓
  [3096/3851] SLAB   — +1 new rows ✓
  [3097/3851] SLDB   — +1 new rows ✓
  [3098/3851] SLDE   — +1 new rows ✓
  [3099/3851] SLE    — +1 new rows ✓
  [3100/3851] SLGL   — +1 new rows ✓
  [3101/3851] SLM    — +1 new rows ✓
  [3102/3851] SLMBP  — +1 new rows ✓
  [3103/3851] SLMT   — +1 new rows ✓
  [3104/3851] SLN    — +1 new rows ✓
  [3105/3851] SLNG   — +1 new rows ✓
  [3106/3851] SLNH   — +1 new rows ✓
  [3107/3851] SLNHP  — +1 new rows ✓
  [3108/3851] SLP    — +1 new rows ✓
  [3109/3851] SLQD   — +1 new rows ✓
  [3110/3851] SLS    — +1 new rows ✓
  [3111/3851] SLVO   — +1 new rows ✓
  [3112/3851] SLVR   — +1 new rows ✓
  [3113/3851] SLXN   — +1 new rows ✓
  [3114/3851] SMBC   — +1 new rows ✓
  [3115/3851] SMCF   — +1 new rows ✓
  [3116/3851] SMCI   — +1 new rows ✓
  [3117/3851] SMCIP  — +1 new rows ✓
  [3118/3851] SMCL   — +1 new rows ✓
  [3119/3851] SMCO   — +1 new rows ✓
  [3120/3851] SMCX   — +1 new rows ✓
  [3121/3851] SMCZ   — +1 new rows ✓
  [3122/3851] SMH    — +1 new rows ✓
  [3123/3851] SMHC   — +1 new rows ✓
  [3124/3851] SMHX   — +1 new rows ✓
  [3125/3851] SMID   — +1 new rows ✓
  [3126/3851] SMMT   — +1 new rows ✓
  [3127/3851] SMOM   — +1 new rows ✓
  [3128/3851] SMPL   — +1 new rows ✓
  [3129/3851] SMRI   — +1 new rows ✓
  [3130/3851] SMSI   — +1 new rows ✓
  [3131/3851] SMST   — +1 new rows ✓
  [3132/3851] SMTC   — +1 new rows ✓
  [3133/3851] SMTI   — +1 new rows ✓
  [3134/3851] SMX    — +1 new rows ✓
  [3135/3851] SNAG   — +1 new rows ✓
  [3136/3851] SNDK   — +1 new rows ✓
  [3137/3851] SNDL   — +1 new rows ✓
  [3138/3851] SNDX   — +1 new rows ✓
  [3139/3851] SNES   — +1 new rows ✓
  [3140/3851] SNEX   — +1 new rows ✓
  [3141/3851] SNGX   — +1 new rows ✓
  [3142/3851] SNOA   — +1 new rows ✓
  [3143/3851] SNPS   — +1 new rows ✓
  [3144/3851] SNSR   — +1 new rows ✓
  [3145/3851] SNTG   — +1 new rows ✓
  [3146/3851] SNTI   — +1 new rows ✓
  [3147/3851] SNWV   — +1 new rows ✓
  [3148/3851] SNY    — +1 new rows ✓
  [3149/3851] SOBR   — +1 new rows ✓
  [3150/3851] SOCL   — +1 new rows ✓
  [3151/3851] SOFA   — +1 new rows ✓
  [3152/3851] SOFI   — +1 new rows ✓
  [3153/3851] SOFX   — +1 new rows ✓
  [3154/3851] SOGP   — +1 new rows ✓
  [3155/3851] SOHU   — +1 new rows ✓
  [3156/3851] SOLC   — +1 new rows ✓
  [3157/3851] SOLS   — +1 new rows ✓
  [3158/3851] SOLT   — +1 new rows ✓
  [3159/3851] SOLZ   — +1 new rows ✓
  [3160/3851] SONM   — +1 new rows ✓
  [3161/3851] SONO   — +1 new rows ✓
  [3162/3851] SOUN   — +1 new rows ✓
  [3163/3851] SOUX   — +1 new rows ✓
  [3164/3851] SOWG   — +1 new rows ✓
  [3165/3851] SOXQ   — +1 new rows ✓
  [3166/3851] SOXX   — +1 new rows ✓
  [3167/3851] SPAM   — +1 new rows ✓
  [3168/3851] SPAQ   — +1 new rows ✓
  [3169/3851] SPBC   — +1 new rows ✓
  [3170/3851] SPCB   — +1 new rows ✓
  [3171/3851] SPCK   — +1 new rows ✓
  [3172/3851] SPCT   — +1 new rows ✓
  [3173/3851] SPCX   — +1 new rows ✓
  [3174/3851] SPFI   — +1 new rows ✓
  [3175/3851] SPHL   — +1 new rows ✓
  [3176/3851] SPIT   — +1 new rows ✓
  [3177/3851] SPPL   — +1 new rows ✓
  [3178/3851] SPRB   — +1 new rows ✓
  [3179/3851] SPRC   — +1 new rows ✓
  [3180/3851] SPRO   — +1 new rows ✓
  [3181/3851] SPRX   — +1 new rows ✓
  [3182/3851] SPRY   — +1 new rows ✓
  [3183/3851] SPSC   — +1 new rows ✓
  [3184/3851] SPT    — +1 new rows ✓
  [3185/3851] SPXD   — +1 new rows ✓
  [3186/3851] SPYQ   — +1 new rows ✓
  [3187/3851] SQFT   — +1 new rows ✓
  [3188/3851] SQLV   — +1 new rows ✓
  [3189/3851] SQQQ   — +1 new rows ✓
  [3190/3851] SQS    — +1 new rows ✓
  [3191/3851] SRAD   — +1 new rows ✓
  [3192/3851] SRCE   — +1 new rows ✓
  [3193/3851] SRET   — +1 new rows ✓
  [3194/3851] SRPT   — +1 new rows ✓
  [3195/3851] SRRK   — +1 new rows ✓
  [3196/3851] SRZN   — +1 new rows ✓
  [3197/3851] SSM    — +1 new rows ✓
  [3198/3851] SSNC   — +1 new rows ✓
  [3199/3851] SSRM   — +1 new rows ✓
  [3200/3851] SSS    — +1 new rows ✓
  [3201/3851] SSSSL  — +1 new rows ✓
  [3202/3851] SSTI   — +1 new rows ✓
  [3203/3851] SSYS   — +1 new rows ✓
  [3204/3851] STAA   — +1 new rows ✓
  [3205/3851] STBA   — +1 new rows ✓
  [3206/3851] STEP   — +1 new rows ✓
  [3207/3851] STEX   — +1 new rows ✓
  [3208/3851] STFS   — +1 new rows ✓
  [3209/3851] STGW   — +1 new rows ✓
  [3210/3851] STHO   — +1 new rows ✓
  [3211/3851] STI    — +1 new rows ✓
  [3212/3851] STIM   — +1 new rows ✓
  [3213/3851] STKE   — +1 new rows ✓
  [3214/3851] STKH   — +1 new rows ✓
  [3215/3851] STLD   — +1 new rows ✓
  [3216/3851] STNC   — +1 new rows ✓
  [3217/3851] STNE   — +1 new rows ✓
  [3218/3851] STOK   — +1 new rows ✓
  [3219/3851] STRA   — +1 new rows ✓
  [3220/3851] STRC   — +1 new rows ✓
  [3221/3851] STRD   — +1 new rows ✓
  [3222/3851] STRF   — +1 new rows ✓
  [3223/3851] STRK   — +1 new rows ✓
  [3224/3851] STRL   — +1 new rows ✓
  [3225/3851] STRO   — +1 new rows ✓
  [3226/3851] STRR   — +1 new rows ✓
  [3227/3851] STRS   — +1 new rows ✓
  [3228/3851] STRT   — +1 new rows ✓
  [3229/3851] STRZ   — +1 new rows ✓
  [3230/3851] STTK   — +1 new rows ✓
  [3231/3851] STX    — +1 new rows ✓
  [3232/3851] SUGP   — +1 new rows ✓
  [3233/3851] SUIS   — +1 new rows ✓
  [3234/3851] SUNE   — +1 new rows ✓
  [3235/3851] SUPN   — +1 new rows ✓
  [3236/3851] SUPP   — +1 new rows ✓
  [3237/3851] SUPX   — +1 new rows ✓
  [3238/3851] SURG   — +1 new rows ✓
  [3239/3851] SUSB   — +1 new rows ✓
  [3240/3851] SUSC   — +1 new rows ✓
  [3241/3851] SUSL   — +1 new rows ✓
  [3242/3851] SVRE   — +1 new rows ✓
  [3243/3851] SVRN   — +1 new rows ✓
  [3244/3851] SWBI   — +1 new rows ✓
  [3245/3851] SWIM   — +1 new rows ✓
  [3246/3851] SWKHL  — +1 new rows ✓
  [3247/3851] SWKS   — +1 new rows ✓
  [3248/3851] SWMR   — +1 new rows ✓
  [3249/3851] SWP    — +1 new rows ✓
  [3250/3851] SWVL   — +1 new rows ✓
  [3251/3851] SXTC   — +1 new rows ✓
  [3252/3851] SXTP   — +1 new rows ✓
  [3253/3851] SYBT   — +1 new rows ✓
  [3254/3851] SYM    — +1 new rows ✓
  [3255/3851] SYNA   — +1 new rows ✓
  [3256/3851] SYRE   — +1 new rows ✓
  [3257/3851] SYZ    — +1 new rows ✓
  [3258/3851] TANH   — +1 new rows ✓
  [3259/3851] TAOP   — +1 new rows ✓
  [3260/3851] TAOX   — +1 new rows ✓
  [3261/3851] TAOZ   — +1 new rows ✓
  [3262/3851] TARA   — +1 new rows ✓
  [3263/3851] TARK   — +1 new rows ✓
  [3264/3851] TARS   — +1 new rows ✓
  [3265/3851] TASK   — +1 new rows ✓
  [3266/3851] TATT   — +1 new rows ✓
  [3267/3851] TAX    — +1 new rows ✓
  [3268/3851] TAXE   — +1 new rows ✓
  [3269/3851] TAXI   — +1 new rows ✓
  [3270/3851] TAXS   — +1 new rows ✓
  [3271/3851] TAXT   — +1 new rows ✓
  [3272/3851] TAYD   — +1 new rows ✓
  [3273/3851] TBBK   — +1 new rows ✓
  [3274/3851] TBCH   — +1 new rows ✓
  [3275/3851] TBH    — +1 new rows ✓
  [3276/3851] TBIL   — +1 new rows ✓
  [3277/3851] TBLD   — +1 new rows ✓
  [3278/3851] TBPH   — +1 new rows ✓
  [3279/3851] TBRG   — +1 new rows ✓
  [3280/3851] TC     — +1 new rows ✓
  [3281/3851] TCAN   — +1 new rows ✓
  [3282/3851] TCBI   — +1 new rows ✓
  [3283/3851] TCBIO  — +1 new rows ✓
  [3284/3851] TCBK   — +1 new rows ✓
  [3285/3851] TCHI   — +1 new rows ✓
  [3286/3851] TCMD   — +1 new rows ✓
  [3287/3851] TCOM   — +1 new rows ✓
  [3288/3851] TCRT   — +1 new rows ✓
  [3289/3851] TCX    — +1 new rows ✓
  [3290/3851] TDI    — +1 new rows ✓
  [3291/3851] TDIC   — +1 new rows ✓
  [3292/3851] TDIV   — +1 new rows ✓
  [3293/3851] TDOG   — +1 new rows ✓
  [3294/3851] TDSB   — +1 new rows ✓
  [3295/3851] TDSC   — +1 new rows ✓
  [3296/3851] TDTH   — +1 new rows ✓
  [3297/3851] TDUP   — +1 new rows ✓
  [3298/3851] TEAD   — +1 new rows ✓
  [3299/3851] TEAM   — +1 new rows ✓
  [3300/3851] TECH   — +1 new rows ✓
  [3301/3851] TECX   — +1 new rows ✓
  [3302/3851] TECY   — +1 new rows ✓
  [3303/3851] TEKX   — +1 new rows ✓
  [3304/3851] TEKY   — +1 new rows ✓
  [3305/3851] TELA   — +1 new rows ✓
  [3306/3851] TEM    — +1 new rows ✓
  [3307/3851] TENB   — +1 new rows ✓
  [3308/3851] TENX   — +1 new rows ✓
  [3309/3851] TER    — +1 new rows ✓
  [3310/3851] TERG   — +1 new rows ✓
  [3311/3851] TEXN   — +1 new rows ✓
  [3312/3851] TEXX   — +1 new rows ✓
  [3313/3851] TFGZ   — +1 new rows ✓
  [3314/3851] TFNS   — +1 new rows ✓
  [3315/3851] TGL    — +1 new rows ✓
  [3316/3851] TGTX   — +1 new rows ✓
  [3317/3851] TH     — +1 new rows ✓
  [3318/3851] THCH   — +1 new rows ✓
  [3319/3851] THFF   — +1 new rows ✓
  [3320/3851] THH    — +1 new rows ✓
  [3321/3851] THMZ   — +1 new rows ✓
  [3322/3851] THRM   — +1 new rows ✓
  [3323/3851] THRV   — +1 new rows ✓
  [3324/3851] THRY   — +1 new rows ✓
  [3325/3851] THYM   — +1 new rows ✓
  [3326/3851] THYP   — +1 new rows ✓
  [3327/3851] TIGO   — +1 new rows ✓
  [3328/3851] TIGR   — +1 new rows ✓
  [3329/3851] TIL    — +1 new rows ✓
  [3330/3851] TILC   — +1 new rows ✓
  [3331/3851] TILE   — +1 new rows ✓
  [3332/3851] TIPT   — +1 new rows ✓
  [3333/3851] TISC   — +1 new rows ✓
  [3334/3851] TITN   — +1 new rows ✓
  [3335/3851] TJGC   — +1 new rows ✓
  [3336/3851] TKLF   — +1 new rows ✓
  [3337/3851] TKNO   — +1 new rows ✓
  [3338/3851] TKNS   — +1 new rows ✓
  [3339/3851] TLA    — +1 new rows ✓
  [3340/3851] TLG    — +1 new rows ✓
  [3341/3851] TLIH   — +1 new rows ✓
  [3342/3851] TLN    — +1 new rows ✓
  [3343/3851] TLPH   — +1 new rows ✓
  [3344/3851] TLRY   — +1 new rows ✓
  [3345/3851] TLS    — +1 new rows ✓
  [3346/3851] TLT    — +1 new rows ✓
  [3347/3851] TLX    — +1 new rows ✓
  [3348/3851] TMB    — +1 new rows ✓
  [3349/3851] TMCI   — +1 new rows ✓
  [3350/3851] TMDX   — +1 new rows ✓
  [3351/3851] TMED   — +1 new rows ✓
  [3352/3851] TMNL   — +1 new rows ✓
  [3353/3851] TMNS   — +1 new rows ✓
  [3354/3851] TMSF   — +1 new rows ✓
  [3355/3851] TMUS   — +1 new rows ✓
  [3356/3851] TMUSI  — +1 new rows ✓
  [3357/3851] TMUSL  — +1 new rows ✓
  [3358/3851] TMUSZ  — +1 new rows ✓
  [3359/3851] TMYY   — +1 new rows ✓
  [3360/3851] TNDM   — +1 new rows ✓
  [3361/3851] TNGX   — +1 new rows ✓
  [3362/3851] TNMG   — +1 new rows ✓
  [3363/3851] TNON   — +1 new rows ✓
  [3364/3851] TNXP   — +1 new rows ✓
  [3365/3851] TNXT   — +1 new rows ✓
  [3366/3851] TNYA   — +1 new rows ✓
  [3367/3851] TONX   — +1 new rows ✓
  [3368/3851] TOP    — +1 new rows ✓
  [3369/3851] TOUR   — +1 new rows ✓
  [3370/3851] TOWN   — +1 new rows ✓
  [3371/3851] TPG    — +1 new rows ✓
  [3372/3851] TPGXL  — +1 new rows ✓
  [3373/3851] TPLS   — +1 new rows ✓
  [3374/3851] TPST   — +1 new rows ✓
  [3375/3851] TQQQ   — +1 new rows ✓
  [3376/3851] TRAW   — +1 new rows ✓
  [3377/3851] TRAX   — +1 new rows ✓
  [3378/3851] TRBF   — +1 new rows ✓
  [3379/3851] TRDA   — +1 new rows ✓
  [3380/3851] TREE   — +1 new rows ✓
  [3381/3851] TRI    — +1 new rows ✓
  [3382/3851] TRIB   — +1 new rows ✓
  [3383/3851] TRINI  — +1 new rows ✓
  [3384/3851] TRINZ  — +1 new rows ✓
  [3385/3851] TRIP   — +1 new rows ✓
  [3386/3851] TRMB   — +1 new rows ✓
  [3387/3851] TRMD   — +1 new rows ✓
  [3388/3851] TRMK   — +1 new rows ✓
  [3389/3851] TRNR   — +1 new rows ✓
  [3390/3851] TRNS   — +1 new rows ✓
  [3391/3851] TROO   — +1 new rows ✓
  [3392/3851] TROW   — +1 new rows ✓
  [3393/3851] TRS    — +1 new rows ✓
  [3394/3851] TRST   — +1 new rows ✓
  [3395/3851] TRUC   — +1 new rows ✓
  [3396/3851] TRUD   — +1 new rows ✓
  [3397/3851] TRUF   — +1 new rows ✓
  [3398/3851] TRUG   — +1 new rows ✓
  [3399/3851] TRUH   — +1 new rows ✓
  [3400/3851] TRUI   — +1 new rows ✓

---
## 8. Quick exploration — your portfolio tickers

In [7]:
import warnings

missing = ["KGC", "NVO", "TSM", "WPM"]

for ticker in missing:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        df = yf.download(ticker, start=START_DATE, end=END_DATE, progress=False, auto_adjust=True)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    df = df.reset_index()
    df["ticker"] = ticker
    max_price = df["Close"].max()
    push_csv_to_github(
        df             = df,
        repo           = GITHUB_REPO,
        path           = f"{STOCKS_PREFIX}/prices_{ticker}.csv",
        token          = GITHUB_TOKEN,
        commit_message = f"Add {ticker} prices ({len(df)} rows, max ${max_price:.2f})",
    )
    print(f"✓ {ticker} — {len(df)} rows, max ${max_price:.2f}")

✓ KGC — 4145 rows, max $37.97
✓ NVO — 4145 rows, max $137.40
✓ TSM — 4145 rows, max $467.67
✓ WPM — 4145 rows, max $165.21

In [6]:
print("finished")

finished